version: "2"
linters:
  default: all
  disable:
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - dupword
    - err113
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godot
    - godox
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - maintidx
    - mnd
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - revive
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/pkg/errors
              desc: Use standard library errors package or fmt.Errorf with %w
    dogsled:
      max-blank-identifiers: 2
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: false
      check-blank: false
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 75
    gosec:
      excludes:
        - G104
        - G307
        - G115
        - G404
        - G601
    misspell:
      locale: US
      ignore-rules:
        - cancelled
        - cancelling
        - marshalled
        - marshalling
        - analyses
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    staticcheck:
      checks:
        - all
        - -SA9003
        - -ST1003
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - dupl
          - errcheck
          - errchkjson
          - goconst
          - gocyclo
          - gosec
          - staticcheck
        path: _test\.go
      - linters:
          - deadcode
          - unused
        path: test_helpers\.go
      - linters:
          - funlen
          - gocognit
          - gocyclo
          - lll
        path: (wrapper|client|managers)\.go
      - linters:
          - dupl
        path: ^internal/api/
      - linters:
          - dupl
        path: ^internal/adapters/
      - linters:
          - dupl
        path: ^internal/factory/
      - linters:
          - dupl
        path: ^internal/common/builders/
      - linters:
          - dupl
        path: ^pkg/watch/
      - linters:
          - dupl
        path: ^tests/mocks/
      - linters:
          - lll
        source: '^//go:generate '
      - linters:
          - errcheck
          - gosec
          - ineffassign
          - staticcheck
          - unused
        path: ^examples/
      - linters:
          - dupl
          - errcheck
          - staticcheck
          - unused
        path: ^cmd/
      - linters:
          - bodyclose
          - errcheck
          - staticcheck
        path: ^benchmarks/
      - linters:
          - staticcheck
        path: internal/adapters/
        text: deprecated
      - linters:
          - staticcheck
        path: _test\.go
        text: do not pass a nil Context
    paths:
      - .*\.pb\.go$
      - .*\.gen\.go$
      - internal/api/.*/wrapper\.go$
      - internal/api/.*/client\.go$
      - internal/api/.*/managers\.go$
      - vendor
      - third_party
      - testdata
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go$
      - .*\.gen\.go$
      - internal/api/.*/wrapper\.go$
      - internal/api/.*/client\.go$
      - internal/api/.*/managers\.go$
      - vendor
      - third_party
      - testdata
      - third_party$
      - builtin$
      - examples$
