version: "2"
linters:
  default: all
  disable:
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - dupword
    - embeddedstructfieldcheck  # Embedded struct formatting is stylistic
    - err113
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funcorder                 # Function ordering is developer's choice
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - godoclint                 # Doc comment style (v2.8+ only)
    - godot
    - godox
    - gosmopolitan              # I18n linter - not needed for this project
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - maintidx
    - mnd
    - modernize                 # Modernization suggestions (v2.8+ only) - not always appropriate
    - nestif
    - noinlineerr               # Inline error handling is idiomatic Go
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - revive
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unparam
    - usetesting
    - varnamelen
    - wrapcheck
    - wsl                       # Whitespace linter (deprecated version)
    - wsl_v5                    # Whitespace linter (new version) - very opinionated
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/pkg/errors
              desc: Use standard library errors package or fmt.Errorf with %w
    dogsled:
      max-blank-identifiers: 2
    dupl:
      threshold: 75
    errcheck:
      check-type-assertions: false
      check-blank: false
    errorlint:
      errorf: true      # Check for error wrapping with %w
      asserts: true     # Check for error type assertions
      comparison: true  # Check for error comparisons
    gocritic:
      disabled-checks:
        - dupImport
        - hugeParam           # API design uses value types intentionally
        - ifElseChain
        - octalLiteral
        - paramTypeCombine    # Style preference - no benefit to combining
        - rangeValCopy        # Performance impact negligible, pointers reduce clarity
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 50
    gosec:
      excludes:
        - G104  # Duplicated errcheck
        - G307  # Duplicated errcheck on file defer Close()
        - G115  # Integer overflow conversion - SLURM resource counts unlikely to overflow int32
        - G404  # Use of weak random generator - acceptable for test data and non-cryptographic randomness
        - G601  # Implicit memory aliasing - fixed in Go 1.22+ with new loop variable scoping
        - G602  # Slice index out of range - covered by bounds checking
    misspell:
      locale: US
      ignore-rules:
        - cancelled
        - cancelling
        - marshalled
        - marshalling
        - analyses
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    staticcheck:
      checks:
        - all
        - -SA9003   # Empty branch - placeholder branches reserved for future implementation
        - -ST1003   # Package naming - version packages use underscores to match SLURM API versions
        - -QF1001   # De Morgan's law - readability preference
        - -QF1003   # Tagged switch - style preference
        - -QF1008   # Embedded field selector - intentional for clarity
    unparam:
      check-exported: false
    usestdlibvars:
      http-method: true
      http-status-code: true
      time-weekday: true
      time-month: true
      time-layout: true
      crypto-hash: true
    perfsprint:
      # Enable performance optimizations for sprintf
      int-conversion: true      # Use strconv instead of fmt.Sprintf for integers
      err-error: false          # Disable fmt.Errorf -> errors.New (conflicts with custom errors package)
      errorf: false             # Disable fmt.Errorf -> errors.New (conflicts with custom errors package)
      sprintf1: true            # Use string concatenation for simple cases
    goconst:
      min-len: 3                # Minimum string length to check
      min-occurrences: 3        # Minimum number of occurrences
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - dupl
          - errcheck
          - errchkjson
          - errorlint
          - goconst
          - gocyclo
          - gocritic
          - gosec
          - prealloc
          - staticcheck
        path: _test\.go
      - linters:
          - deadcode
          - unused
        path: test_helpers\.go
      - linters:
          - funlen
          - gocognit
          - gocyclo
          - lll
        path: (wrapper|client|managers)\.go
      - linters:
          - dupl
        path: ^internal/api/
      - linters:
          - dupl
        path: ^internal/adapters/
      - linters:
          - dupl
        path: ^internal/factory/
      - linters:
          - dupl
        path: ^internal/common/builders/
      - linters:
          - dupl
        path: ^pkg/watch/
      - linters:
          - dupl
        path: ^tests/mocks/
      - linters:
          - dupl
        path: ^internal/interfaces/
      - linters:
          - dupl
        path: ^interfaces/
      - linters:
          - dupl
        path: ^internal/common/types/
      - linters:
          - dupl
        path: ^internal/managers/base/
      - linters:
          - dupl
        path: ^pkg/retry/
      - linters:
          - dupl
        path: ^pkg/analytics/
      - linters:
          - dupl
          - gocyclo
        path: client\.go$
      - linters:
          - gocyclo
        path: _converters\.go$
      - linters:
          - gocyclo
        path: manager_impl\.go$
      - linters:
          - lll
        source: '^//go:generate '
      - linters:
          - dupl
          - errcheck
          - errorlint
          - goconst
          - gocritic
          - gosec
          - ineffassign
          - perfsprint
          - prealloc
          - staticcheck
          - unused
        path: ^examples/
      - linters:
          - dupl
          - errcheck
          - errorlint
          - goconst
          - gocritic
          - perfsprint
          - staticcheck
          - unused
        path: ^cmd/
      - linters:
          - bodyclose
          - errcheck
          - goconst
          - gocritic
          - perfsprint
          - staticcheck
        path: ^benchmarks/
      - linters:
          - goconst
          - gocritic
        path: ^tests/
      - linters:
          - goconst
        path: ^pkg/errors/  # Error messages are intentionally repeated for clarity
      - linters:
          - goconst
        path: internal/adapters/.*_adapter\.go
        text: "`true`|`error`|`cpu`|`yes`|`state_change`"  # Simple API parameter strings
      - linters:
          - goconst
        path: internal/api/.*/.*_manager_impl\.go  # Complex business logic, repeated strings are expected
      - linters:
          - gocritic
        path: ^internal/factory/
        text: importShadow  # Factory pattern - config/auth/pool variable shadowing is idiomatic
      - linters:
          - gocritic
        path: ^internal/adapters/
        text: importShadow|unnamedResult|typeAssertChain|singleCaseSwitch|nestingReduce  # Adapter layer - minor style issues
      - linters:
          - gocritic
        path: ^internal/api/
        text: importShadow|unnamedResult|emptyStringTest|nestingReduce  # Business logic layer - minor style issues
      - linters:
          - gocritic
        path: ^internal/managers/
        text: unnamedResult  # Base managers - generic return types
      - linters:
          - gocritic
        path: ^client\.go$
        text: importShadow  # WithAuth function parameter name matches package name (idiomatic)
      - linters:
          - gocritic
        path: ^pkg/errors/
        text: appendCombine|typeAssertChain  # Minor style issues - sequential logic is clearer
      - linters:
          - gocritic
        path: ^pkg/performance/cache\.go$
        text: emptyStringTest  # False positive - checking length before indexing, not string comparison
      - linters:
          - staticcheck
        path: internal/adapters/
        text: deprecated
      - linters:
          - staticcheck
        path: _test\.go
        text: do not pass a nil Context
    paths:
      - .*\.pb\.go$
      - .*\.gen\.go$
      - internal/api/.*/wrapper\.go$
      - internal/api/.*/client\.go$
      - internal/api/.*/managers\.go$
      - vendor
      - third_party
      - testdata
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  # Formatters should only run with --fix, not during regular linting
  # enable:
  #   - gci
  #   - gofmt
  #   - gofumpt
  #   - goimports
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go$
      - .*\.gen\.go$
      - internal/api/.*/wrapper\.go$
      - internal/api/.*/client\.go$
      - internal/api/.*/managers\.go$
      - vendor
      - third_party
      - testdata
      - third_party$
      - builtin$
      - examples$
