version: "2"
linters:
  default: all
  disable:
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - dupword
    - embeddedstructfieldcheck  # Embedded struct formatting is stylistic
    - err113
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funcorder                 # Function ordering is developer's choice
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godoclint                 # Doc comment style (v2.8+ only)
    - godot
    - godox
    - gosmopolitan              # I18n linter - not needed for this project
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - maintidx
    - mnd
    - modernize                 # Modernization suggestions (v2.8+ only) - not always appropriate
    - nestif
    - nilerr
    - noinlineerr               # Inline error handling is idiomatic Go
    - nlreturn
    - noctx
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - revive
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl                       # Whitespace linter (deprecated version)
    - wsl_v5                    # Whitespace linter (new version) - very opinionated
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/pkg/errors
              desc: Use standard library errors package or fmt.Errorf with %w
    dogsled:
      max-blank-identifiers: 2
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: false
      check-blank: false
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 75
    gosec:
      excludes:
        - G104  # Duplicated errcheck
        - G307  # Duplicated errcheck on file defer Close()
        - G115  # Integer overflow conversion - SLURM resource counts unlikely to overflow int32
        - G404  # Use of weak random generator - acceptable for test data and non-cryptographic randomness
        - G601  # Implicit memory aliasing - fixed in Go 1.22+ with new loop variable scoping
        - G602  # Slice index out of range - covered by bounds checking
    misspell:
      locale: US
      ignore-rules:
        - cancelled
        - cancelling
        - marshalled
        - marshalling
        - analyses
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    staticcheck:
      checks:
        - all
        - -SA9003   # Empty branch - placeholder branches reserved for future implementation
        - -ST1003   # Package naming - version packages use underscores to match SLURM API versions
        - -QF1001   # De Morgan's law - readability preference
        - -QF1003   # Tagged switch - style preference
        - -QF1008   # Embedded field selector - intentional for clarity
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - dupl
          - errcheck
          - errchkjson
          - goconst
          - gocyclo
          - gosec
          - staticcheck
        path: _test\.go
      - linters:
          - deadcode
          - unused
        path: test_helpers\.go
      - linters:
          - funlen
          - gocognit
          - gocyclo
          - lll
        path: (wrapper|client|managers)\.go
      - linters:
          - dupl
        path: ^internal/api/
      - linters:
          - dupl
        path: ^internal/adapters/
      - linters:
          - dupl
        path: ^internal/factory/
      - linters:
          - dupl
        path: ^internal/common/builders/
      - linters:
          - dupl
        path: ^pkg/watch/
      - linters:
          - dupl
        path: ^tests/mocks/
      - linters:
          - lll
        source: '^//go:generate '
      - linters:
          - dupl
          - errcheck
          - gosec
          - ineffassign
          - staticcheck
          - unused
        path: ^examples/
      - linters:
          - dupl
          - errcheck
          - staticcheck
          - unused
        path: ^cmd/
      - linters:
          - bodyclose
          - errcheck
          - staticcheck
        path: ^benchmarks/
      - linters:
          - staticcheck
        path: internal/adapters/
        text: deprecated
      - linters:
          - staticcheck
        path: _test\.go
        text: do not pass a nil Context
    paths:
      - .*\.pb\.go$
      - .*\.gen\.go$
      - internal/api/.*/wrapper\.go$
      - internal/api/.*/client\.go$
      - internal/api/.*/managers\.go$
      - vendor
      - third_party
      - testdata
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  # Formatters should only run with --fix, not during regular linting
  # enable:
  #   - gci
  #   - gofmt
  #   - gofumpt
  #   - goimports
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go$
      - .*\.gen\.go$
      - internal/api/.*/wrapper\.go$
      - internal/api/.*/client\.go$
      - internal/api/.*/managers\.go$
      - vendor
      - third_party
      - testdata
      - third_party$
      - builtin$
      - examples$
