# SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
# SPDX-License-Identifier: Apache-2.0

# This file configures golangci-lint for the slurm-client project
# Run with: golangci-lint run

run:
  # Timeout for analysis
  timeout: 10m

linters:
  enable-all: true

  disable:
    # Disable overly opinionated/noisy linters (891+ errors each)
    - testifylint    # 891 errors - testify style opinions
    - perfsprint     # 527 errors - performance Sprint opinions
    - forbidigo      # 428 errors - bans common functions
    - gocritic       # 462 errors - too opinionated
    - usestdlibvars  # 59 errors - prefer stdlib constants

    # Disable complexity linters (covered by gocyclo)
    - cyclop
    - funlen
    - maintidx
    - nestif
    - gocognit

    # Disable less critical linters
    - lll            # Line length - style not critical
    - revive         # Style rules - mostly non-critical
    - unconvert      # Unnecessary conversions - non-functional
    - goconst        # Magic strings - low priority
    - unparam        # 94 errors - unused params often intentional for interfaces
    - noctx          # 32 errors - missing context, often intentional
    - prealloc       # 17 errors - preallocate slices, performance not critical
    - errorlint      # 55 errors - error wrapping opinions
    - forcetypeassert # 14 errors - force type assertion checks
    - containedctx   # 45 errors - context in struct
    - dupword        # 10 errors - duplicate words
    - canonicalheader # 13 errors - HTTP header canonicalization
    - wastedassign   # 3 errors - wasted assignments
    - nilerr         # 3 errors - nil error returns
    - usetesting     # 2 errors - testing helper usage
    - contextcheck   # 2 errors - context usage

    # Disable Go 1.22+ style linters (not critical for functionality)
    - intrange       # 128 errors - suggests integer range syntax, purely stylistic
    - copyloopvar    # 4 errors - Go 1.22+ removes need for loop var copies

    # Disable formatting linters (use standard gofmt)
    - gci            # 65 errors - import ordering, can auto-fix but not critical
    - gofumpt        # 32 errors - stricter gofmt, standard gofmt is sufficient

    # Disable opinionated style linters
    - nonamedreturns # 3 errors - named returns improve readability in complex functions

    # Disable some linters that are too strict or not applicable
    - exhaustive
    - gochecknoglobals
    - gochecknoinits
    - godot
    - godox
    - err113          # Renamed from goerr113
    - nlreturn
    - testpackage
    - wrapcheck
    - wsl             # Whitespace linter
    - mnd             # Magic number detector (renamed from gomnd)
    - interfacebloat
    - ireturn
    - varnamelen
    - tagliatelle
    - paralleltest
    - tparallel
    - thelper
    - exhaustruct

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "Use standard library errors package or fmt.Errorf with %w"

  dogsled:
    # Maximum number of blank identifiers in assignment
    max-blank-identifiers: 2

  dupl:
    # Minimum lines to consider as duplicate
    threshold: 100

  errcheck:
    # Report about not checking errors in type assertions
    check-type-assertions: false  # Allow `_, _ = value.(type)` patterns
    # Report about assignment of errors to blank identifier
    check-blank: false  # Allow `_ = func()` patterns for intentional error ignoring

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

  gocyclo:
    # Minimal cyclomatic complexity to report
    # Set to 75 to allow complex but necessary API conversion and builder functions
    # These functions map many optional fields and are inherently complex
    # They are well-tested and splitting them would reduce code clarity
    min-complexity: 75

  gosec:
    excludes:
      - G104 # Duplicated errcheck
      - G307 # Duplicated errcheck on file defer Close()
      - G115 # Integer overflow conversion - SLURM resource counts unlikely to overflow int32
      - G404 # Use of weak random generator - acceptable for test data and non-cryptographic randomness
      - G601 # Implicit memory aliasing - fixed in Go 1.22+ with new loop variable scoping

  misspell:
    # Locale to use
    locale: US
    # Ignore British English spellings that are intentional
    ignore-words:
      - cancelled
      - cancelling
      - marshalled
      - marshalling
      - analyses

  nakedret:
    # Maximum length of function to check for naked returns
    max-func-lines: 30

  stylecheck:
    # Disable package naming check (ST1003) - version packages use underscores to match SLURM API versions
    checks: ["all", "-ST1003"]

  staticcheck:
    # Disable SA9003 (empty branch) - placeholder branches reserved for future implementation
    checks: ["all", "-SA9003"]

  prealloc:
    # Report preallocation suggestions only on simple loops
    simple: true
    range-loops: true
    for-loops: false

  unparam:
    # Report unused function parameters
    check-exported: false

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
    - "internal/api/.*/wrapper\\.go$"
    - "internal/api/.*/client\\.go$"
    - "internal/api/.*/managers\\.go$"

  exclude-dirs:
    - vendor
    - third_party
    - testdata

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
        - staticcheck
        - bodyclose     # Error cases often have nil responses
        - errchkjson    # JSON encoding in tests is for display/debugging

    # Exclude test helper files
    - path: test_helpers\.go
      linters:
        - unused
        - deadcode

    # Exclude known issues in generated files
    - path: (wrapper|client|managers)\.go
      linters:
        - gocyclo
        - gocognit
        - lll
        - funlen

    # Exclude dupl for internal/api/* - similar API operations have intentional duplication
    - path: ^internal/api/
      linters:
        - dupl

    # Exclude dupl for internal/adapters/* - similar adapter operations have intentional duplication
    - path: ^internal/adapters/
      linters:
        - dupl

    # Exclude dupl for internal/factory/* - factory patterns have intentional duplication
    - path: ^internal/factory/
      linters:
        - dupl

    # Exclude dupl for internal/common/builders/* - builder patterns have intentional duplication
    - path: ^internal/common/builders/
      linters:
        - dupl

    # Exclude dupl for pkg/watch/* - polling patterns have intentional duplication
    - path: ^pkg/watch/
      linters:
        - dupl

    # Exclude dupl for tests/mocks/* - mock handlers have intentional duplication
    - path: ^tests/mocks/
      linters:
        - dupl

    # Exclude lll in long function declarations
    - source: "^//go:generate "
      linters:
        - lll

    # Exclude certain rules for example code
    - path: ^examples/
      linters:
        - errcheck
        - ineffassign
        - staticcheck
        - unused
        - gosec

    # Exclude certain rules for cmd/ binaries
    - path: ^cmd/
      linters:
        - staticcheck
        - unused
        - errcheck
        - dupl  # Similar operations have intentional code duplication

    # Exclude certain rules for benchmark tests
    - path: ^benchmarks/
      linters:
        - staticcheck
        - bodyclose  # Benchmarks focus on performance, not cleanup
        - errcheck

    # Allow deprecated API usage in adapters (following upstream SLURM API)
    - path: internal/adapters/
      text: "deprecated"
      linters:
        - staticcheck

    # Allow nil context in test files (common pattern for error path testing)
    - path: _test\.go
      text: "do not pass a nil Context"
      linters:
        - staticcheck

  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0

  # Show only new issues created after git revision
  # new-from-rev: origin/main