version: "2"
linters:
  default: all
  disable:
    - canonicalheader           # HTTP header canonicalization - not applicable to SLURM client
    - containedctx              # Embedded context fields have legitimate use cases in our middleware
    - copyloopvar               # Fixed in Go 1.22+ with improved loop variable scoping
    - cyclop                    # Cyclomatic complexity too strict for domain-specific business logic
    - dupl                      # Duplicate code detection too strict for adapter boilerplate patterns
    - embeddedstructfieldcheck  # Embedded struct formatting is stylistic
    - err113                    # Inline fmt.Errorf is idiomatic Go pattern
    - exhaustruct               # Allows zero-value fields for optional configuration
    - forbidigo                 # No specific patterns need to be forbidden for this project
    - funcorder                 # Function ordering is a developer's choice
    - funlen                    # Some functions legitimately need greater length for clarity
    - gochecknoglobals          # Limited global usage for test helpers and initialization is justified
    - gochecknoinits            # Init functions have legitimate use cases in our architecture
    - gocognit                  # Cognitive complexity too strict for API layer business logic
    - godoclint                 # Doc comment style (v2.8+ only) - we prefer flexible documentation
    - godot                     # Punctuation in comments is optional
    - godox                     # TODO/FIXME comments are useful for development tracking
    - gosmopolitan              # I18n linter - not needed for this project
    - interfacebloat            # Our manager interfaces intentionally provide comprehensive APIs
    - ireturn                   # Returning interfaces is intentional for flexibility and mocking
    - lll                       # Long lines improve readability over unnecessary breaking
    - maintidx                  # Maintainability index too strict for this domain
    - mnd                       # Constants like 1024 are clear without always being named
    - modernize                 # Modernization suggestions (v2.8+ only) - not always appropriate
    - nestif                    # Nested if statements are sometimes clearer than alternatives
    - noinlineerr               # Inline error handling is idiomatic Go
    - nlreturn                  # Blank lines before returns are stylistic
    - nonamedreturns            # Named returns improve clarity in appropriate contexts
    - paralleltest              # Not all tests can run in parallel (e.g., integration tests)
    - tagliatelle               # Struct tags follow SLURM API conventions which may differ
    - testpackage               # Internal test packages used to access unexported functions
    - tparallel                 # Over-aggressive for our test suite structure
    - varnamelen                # Short, meaningful names like i, v, id are idiomatic Go
    - wrapcheck                 # Error wrapping is good practice but linter is too strict
    - wsl                       # Whitespace linter (deprecated version)
    - wsl_v5                    # Whitespace linter (new version) - very opinionated
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/pkg/errors
              desc: Use standard library errors package or fmt.Errorf with %w
            - pkg: io/ioutil
              desc: io/ioutil is deprecated as of Go 1.16; use io or os packages directly
            - pkg: golang.org/x/net/context
              desc: Use standard library context package instead of golang.org/x/net/context
        mainAndNonTest:
          deny:
            - pkg: github.com/stretchr/testify/assert
              desc: Use require instead of assert for better test failure diagnostics
          files:
            - "!$test"
    dogsled:
      max-blank-identifiers: 2
    dupl:
      threshold: 75
    errcheck:
      check-type-assertions: true
      check-blank: false
    errorlint:
      errorf: true      # Check for error wrapping with %w
      asserts: true     # Check for error type assertions
      comparison: true  # Check for error comparisons
    exhaustive:
      check: [switch, map]  # Check both switches and maps
      explicit-exhaustive-switch: false  # Allow default cases
      default-signifies-exhaustive: true  # Treat default case as exhaustive
    gocritic:
      disabled-checks:
        - dupImport
        - hugeParam           # API design uses value types intentionally
        - ifElseChain
        - octalLiteral
        - paramTypeCombine    # Style preference - no benefit to combining
        - rangeValCopy        # Performance impact negligible, pointers reduce clarity
        - whyNoLint
        - wrapperFunc
        - importShadow        # Parameter shadowing package name is idiomatic in examples
        - deferInLoop         # Deferring inside loops is sometimes necessary for resource cleanup
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 20
    goheader:
      template-path: .goheader
    gosec:
      excludes:
        - G104  # Duplicated errcheck - errcheck linter is more comprehensive
        - G307  # Duplicated errcheck on file defer Close() - handled by errcheck linter
        - G601  # Implicit memory aliasing - fixed in Go 1.22+ with new loop variable scoping
        - G602  # Slice index out of range - covered by bounds checking
    misspell:
      locale: US
      ignore-rules:
        - cancelled
        - cancelling
        - marshalled
        - marshalling
        - analyses
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    staticcheck:
      checks:
        - all
        - -SA9003   # Empty branch - placeholder branches reserved for future implementation (27 violations)
        - -ST1003   # Package naming - version packages use underscores to match SLURM API versions (255 violations)
        - -QF1001   # De Morgan's law - readability preference (3 violations)
        - -QF1003   # Tagged switch - style preference (4 violations)
        - -QF1008   # Embedded field selector - intentional for clarity (9 violations)
    unparam:
      check-exported: false
    usestdlibvars:
      http-method: true
      http-status-code: true
      time-weekday: true
      time-month: true
      time-layout: true
      crypto-hash: true
    revive:
      enable-all-rules: false
      rules:
        - name: empty-block
          severity: warning
        - name: context-as-argument
          severity: warning
          disabled: false
        - name: context-keys-type
          severity: warning
          disabled: false
        - name: exported
          severity: warning
          disabled: false
        - name: unused-parameter
          severity: warning
          disabled: false
        - name: unreachable-code
          severity: warning
          disabled: false
        - name: error-naming
          severity: warning
          disabled: false
        - name: error-return
          severity: warning
          disabled: false
        - name: receiver-naming
          severity: warning
          disabled: false
        - name: indent-error-flow
          severity: warning
          disabled: false
        - name: blank-imports
          severity: warning
          disabled: false
        - name: var-declaration
          severity: warning
          disabled: false
        - name: unnecessary-stmt
          severity: warning
          disabled: false
    perfsprint:
      # Enable performance optimizations for sprintf
      int-conversion: true      # Use strconv instead of fmt.Sprintf for integers
      err-error: false          # Disable fmt.Errorf -> errors.New (conflicts with custom errors package)
      errorf: false             # Disable fmt.Errorf -> errors.New (conflicts with custom errors package)
      sprintf1: true            # Use string concatenation for simple cases
    goconst:
      min-len: 3                # Minimum string length to check
      min-occurrences: 3        # Minimum number of occurrences
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - dupl
          - errcheck
          - errchkjson
          - forcetypeassert
          - goconst
          - gocyclo
          - gosec
          - noctx
          - testifylint
          - thelper
          - unparam
        path: _test\.go
      - linters:
          - gosec
        path: (^internal/adapters/|^internal/api/|^internal/factory/|^internal/common/|^tests/|_test\.go$|^tests/mocks/)
        text: G115  # Integer overflow conversions are safe for SLURM API type transformations and test data
      - linters:
          - gosec
        path: ^pkg/retry/
        text: G404  # Weak random used for non-cryptographic jitter in exponential backoff
      - linters:
          - gosec
        path: ^internal/api/v0_0_43/
        text: G404  # Weak random used for generating synthetic test data in simulation functions
      - linters:
          - revive
        path: _test\.go
        text: context-as-argument
      - linters:
          - deadcode
          - unused
          - nilnil
        path: test_helpers\.go
      - linters:
          - depguard
        path: (test_helpers\.go|^tests/|^benchmarks/)
      - linters:
          - funlen
          - gocognit
          - gocyclo
          - lll
        path: (wrapper|client|managers)\.go
      - linters:
          - dupl
        path: ^internal/api/
      - linters:
          - dupl
          - revive
        path: ^internal/adapters/
        text: empty-block
      - linters:
          - revive
        path: ^internal/api/
        text: empty-block
      - linters:
          - revive
        path: ^internal/managers/
        text: empty-block
      - linters:
          - revive
        path: ^tests/benchmarks/
        text: empty-block
      - linters:
          - dupl
        path: ^internal/(factory|adapters/base)/  # Factory and base managers boilerplate
      - linters:
          - dupl
        path: ^internal/common/(builders|types)/  # Builder and type boilerplate patterns
      - linters:
          - dupl
        path: ^pkg/(streaming|watch)/  # Streaming and watch implementations
      - linters:
          - dupl
        path: ^tests/mocks/  # Mock implementations
      - linters:
          - dupl
        path: (^internal/)?interfaces/  # Interface definitions
      - linters:
          - dupl
        path: ^pkg/(retry|analytics)/  # Retry and analytics packages
      - linters:
          - dupl
          - gocyclo
        path: client\.go$
      - linters:
          - gocyclo
        path: _converters\.go$
      - linters:
          - gocyclo
        path: manager_impl\.go$
      - linters:
          - lll
        source: '^//go:generate '
      - linters:
          - goconst
        path: ^cmd/
      - linters:
          - bodyclose
          - errcheck
          - goconst
          - gocritic
          - noctx
          - perfsprint
          - staticcheck
          - testifylint
          - thelper
          - unparam
        path: ^benchmarks/
      - linters:
          - goconst
          - gocritic
          - noctx
          - testifylint
          - thelper
          - unparam
        path: ^tests/
      - linters:
          - revive
        path: client_options\.go
        text: unused-parameter  # Builder pattern functions intentionally have unused parameters
      - linters:
          - revive
        path: ^internal/factory/
        text: unused-parameter  # Factory builder functions intentionally have unused parameters
      - linters:
          - revive
        path: ^pkg/.*_options\.go
        text: unused-parameter  # Options functions intentionally have unused parameters
      - linters:
          - revive
        path: ^internal/api/.*_manager_impl\.go$
        text: unused-parameter  # Converter functions have consistent signatures across versions
      - linters:
          - revive
        path: ^internal/common/(standalone_stubs|association_manager_stub)\.go$
        text: unused-parameter  # Stub implementations need to match interface signatures
      - linters:
          - revive
        path: ^internal/adapters/.*_adapter\.go$
        text: unused-parameter  # Adapter implementations need to match interface signatures
      - linters:
          - revive
        path: ^pkg/streaming/test_helpers\.go$
        text: unused-parameter  # Test helper functions intentionally have unused parameters
      - linters:
          - revive
        path: _test\.go$
        text: unused-parameter  # Test functions often have unused parameters
      - linters:
          - revive
        path: (client\.go|interfaces\.go|pkg/errors/)
        text: exported  # Established public API types - renaming would break compatibility
      - linters:
          - revive
        path: (internal/factory/factory\.go|pkg/context/context\.go|pkg/performance/connection_pool\.go|pkg/pool/connection_pool\.go|internal/adapters/base/base_manager\.go)
        text: exported  # Backward compatibility type aliases and established internal types
      - linters:
          - exhaustive
        path: ^internal/common/slurm_error_codes\.go$
      - linters:
          - exhaustive
        path: ^pkg/context/context\.go$
      - linters:
          - exhaustive
        path: ^pkg/errors/builders\.go$
      - linters:
          - exhaustive
        path: ^pkg/errors/version_mapping\.go$
      - linters:
          - goconst
        path: ^pkg/errors/  # Error messages are intentionally repeated for clarity
      - linters:
          - goconst
        path: internal/adapters/.*_adapter\.go
        text: "`true`|`error`|`cpu`|`yes`|`state_change`"  # Simple API parameter strings
      - linters:
          - goconst
        path: internal/api/.*/.*_manager_impl\.go  # Complex business logic, repeated strings are expected
      - linters:
          - gocritic
        path: ^internal/adapters/
        text: unnamedResult|typeAssertChain  # Adapter layer - minor style issues
      - linters:
          - gocritic
        path: ^internal/api/
        text: unnamedResult|emptyStringTest  # Business logic layer - minor style issues
      - linters:
          - gocritic
        path: ^internal/managers/
        text: unnamedResult  # Base managers - generic return types
      - linters:
          - gocritic
        path: ^pkg/errors/
        text: appendCombine|typeAssertChain  # Minor style issues - sequential logic is clearer
      - linters:
          - gocritic
        path: ^pkg/performance/cache\.go$
        text: emptyStringTest  # False positive - checking length before indexing, not string comparison
      - linters:
          - testifylint
        path: ^pkg/
        text: require-error|float-compare|error-nil|error-is-as  # Manual judgment needed for assert vs require and epsilon values
      - linters:
          - staticcheck
        path: internal/adapters/
        text: deprecated
      - linters:
          - staticcheck
        path: _test\.go
        text: do not pass a nil Context
      - linters:
          - intrange
        path: ^internal/adapters/base/crud_manager\.go$
        # Loop condition calls v.Len() which should not be converted
      - linters:
          - intrange
        path: ^tests/integration/version_compatibility_test\.go$
        # Loop condition calls typeVal.NumField() which should not be converted
      - linters:
          - goheader
        path: (\.pb\.go|\.gen\.go|/wrapper\.go$|/client\.go$|/managers\.go$)  # Generated files
      - linters:
          - goheader
        path: ^internal/common/types/  # Generated types from OpenAPI spec
      - linters:
          - revive
        path: ^internal/common/types/
        text: exported  # Generated enum constants don't need individual comments
      - linters:
          - goconst
        path: internal/factory/
        text: "v0\\.0\\.43"  # Version strings in factory switches should not be constants
      - linters:
          - goheader
        path: vendor/  # Third-party dependencies
      - linters:
          - goheader
        path: ^internal/adapters/.*goverter.*\.go$  # Goverter helper files
      # Goverter comments use "goverter:map Field Field" syntax which triggers dupword
      - linters:
          - dupword
        path: ^internal/adapters/.*goverter.*\.go$
      # Examples legitimately use context.Background() as entry points
      - linters:
          - contextcheck
        path: ^examples/
      # Examples don't always need Output comments
      - linters:
          - testableexamples
        path: ^examples/
      - linters:
          - testableexamples
        path: examples_test\.go$
      # Example tests use log.Fatal for demonstration which triggers exitAfterDefer
      - linters:
          - gocritic
        path: examples_test\.go$
        text: exitAfterDefer
      # Examples use string literals for clarity
      - linters:
          - goconst
        path: ^examples/
      # Example code style is intentionally simple for readability
      - linters:
          - gocritic
        path: ^examples/
        text: appendAssign|nestingReduce
      # Tool code style preferences
      - linters:
          - gocritic
        path: ^cmd/
        text: nestingReduce
      # Performance sprint suggestions often not applicable in tools/examples/adapters
      - linters:
          - perfsprint
        path: ^internal/adapters/
      - linters:
          - perfsprint
        path: ^examples/
      - linters:
          - perfsprint
        path: ^cmd/
      - linters:
          - perfsprint
        path: ^internal/factory/
      # Unconvert often flags valid type conversions in generated/adapter code
      - linters:
          - unconvert
        path: \.gen\.go$
      - linters:
          - unconvert
        path: ^internal/adapters/
      # Converter helper functions prepared for future use in adapters
      - linters:
          - unused
        path: ^internal/adapters/.*_converters.*\.go$
      - linters:
          - unused
        path: ^internal/adapters/.*/goverter_bridge\.go$
      # Example helper functions
      - linters:
          - unused
        path: ^examples/
    paths:
      - .*\.pb\.go$
      - .*\.gen\.go$
      - internal/api/.*/wrapper\.go$
      - internal/api/.*/client\.go$
      - internal/api/.*/managers\.go$
      - vendor
      - third_party
      - testdata
      - third_party$
      - builtin$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  # Formatters should only run with --fix, not during regular linting
  # enable:
  #   - gci
  #   - gofmt
  #   - gofumpt
  #   - goimports
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go$
      - .*\.gen\.go$
      - internal/api/.*/wrapper\.go$
      - internal/api/.*/client\.go$
      - internal/api/.*/managers\.go$
      - vendor
      - third_party
      - testdata
      - third_party$
      - builtin$
