// Code generated by generate_adapters.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0
package v0_0_42

import (
	"context"
	"testing"

	types "github.com/jontk/slurm-client/api"
	api "github.com/jontk/slurm-client/internal/openapi/v0_0_42"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestNewAccountAdapter(t *testing.T) {
	client := &api.ClientWithResponses{}
	adapter := NewAccountAdapter(client)
	require.NotNil(t, adapter)
}
func TestAccountAdapter_ValidateContext(t *testing.T) {
	adapter := NewAccountAdapter(&api.ClientWithResponses{})
	// Test nil context
	//lint:ignore SA1012 intentionally testing nil context validation
	err := adapter.ValidateContext(nil)
	assert.Error(t, err)
	// Test valid context
	err = adapter.ValidateContext(context.Background())
	assert.NoError(t, err)
}
func TestAccountAdapter_List_NilContext(t *testing.T) {
	adapter := NewAccountAdapter(&api.ClientWithResponses{})
	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.List(nil, nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}
func TestAccountAdapter_List_ClientNotInitialized(t *testing.T) {
	adapter := NewAccountAdapter(nil)
	result, err := adapter.List(context.Background(), nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}
func TestAccountAdapter_Get_NilContext(t *testing.T) {
	adapter := NewAccountAdapter(&api.ClientWithResponses{})
	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.Get(nil, "test-account")
	assert.Nil(t, result)
	assert.Error(t, err)
}
func TestAccountAdapter_Get_EmptyIdentifier(t *testing.T) {
	adapter := NewAccountAdapter(&api.ClientWithResponses{})
	result, err := adapter.Get(context.Background(), "")
	assert.Nil(t, result)
	assert.Error(t, err)
}
func TestAccountAdapter_Get_ClientNotInitialized(t *testing.T) {
	adapter := NewAccountAdapter(nil)
	result, err := adapter.Get(context.Background(), "test-account")
	assert.Nil(t, result)
	assert.Error(t, err)
}
func TestAccountAdapter_Create_NilContext(t *testing.T) {
	adapter := NewAccountAdapter(&api.ClientWithResponses{})
	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.Create(nil, &types.AccountCreate{})
	assert.Nil(t, result)
	assert.Error(t, err)
}
func TestAccountAdapter_Create_NilInput(t *testing.T) {
	adapter := NewAccountAdapter(&api.ClientWithResponses{})
	result, err := adapter.Create(context.Background(), nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}
func TestAccountAdapter_Create_ClientNotInitialized(t *testing.T) {
	adapter := NewAccountAdapter(nil)
	result, err := adapter.Create(context.Background(), &types.AccountCreate{})
	assert.Nil(t, result)
	assert.Error(t, err)
}
func TestAccountAdapter_Update_NilContext(t *testing.T) {
	adapter := NewAccountAdapter(&api.ClientWithResponses{})
	//lint:ignore SA1012 intentionally testing nil context
	err := adapter.Update(nil, "test-account", &types.AccountUpdate{})
	assert.Error(t, err)
}
func TestAccountAdapter_Update_NilInput(t *testing.T) {
	adapter := NewAccountAdapter(&api.ClientWithResponses{})
	err := adapter.Update(context.Background(), "test-account", nil)
	assert.Error(t, err)
}
func TestAccountAdapter_Update_ClientNotInitialized(t *testing.T) {
	adapter := NewAccountAdapter(nil)
	err := adapter.Update(context.Background(), "test-account", &types.AccountUpdate{})
	assert.Error(t, err)
}
func TestAccountAdapter_Delete_NilContext(t *testing.T) {
	adapter := NewAccountAdapter(&api.ClientWithResponses{})
	//lint:ignore SA1012 intentionally testing nil context
	err := adapter.Delete(nil, "test-account")
	assert.Error(t, err)
}
func TestAccountAdapter_Delete_EmptyIdentifier(t *testing.T) {
	adapter := NewAccountAdapter(&api.ClientWithResponses{})
	err := adapter.Delete(context.Background(), "")
	assert.Error(t, err)
}
func TestAccountAdapter_Delete_ClientNotInitialized(t *testing.T) {
	adapter := NewAccountAdapter(nil)
	err := adapter.Delete(context.Background(), "test-account")
	assert.Error(t, err)
}
func TestAccountAdapter_ReadConverter(t *testing.T) {
	adapter := NewAccountAdapter(&api.ClientWithResponses{})
	// Create test API object with known values
	testName := "test-account"
	testDesc := "test description"
	testOrg := "test-org"
	apiObj := api.V0042Account{
		Name:         testName,
		Description:  testDesc,
		Organization: testOrg,
	}
	// Convert API → Common
	commonObj := adapter.convertAPIAccountToCommon(apiObj)
	require.NotNil(t, commonObj)
	// Verify field values were correctly converted
	assert.Equal(t, testName, commonObj.Name)
	assert.Equal(t, testDesc, commonObj.Description)
	assert.Equal(t, testOrg, commonObj.Organization)
}
func TestAccountAdapter_CreateConverter(t *testing.T) {
	adapter := NewAccountAdapter(&api.ClientWithResponses{})
	// Create test input with known values
	testName := "test-account"
	input := &types.AccountCreate{
		Name: testName,
	}
	// Convert Common → API
	apiObj := adapter.convertCommonAccountCreateToAPI(input)
	require.NotNil(t, apiObj)
}
func TestAccountAdapter_UpdateConverter(t *testing.T) {
	adapter := NewAccountAdapter(&api.ClientWithResponses{})
	// Create test input with known values
	testDesc := "test description"
	input := &types.AccountUpdate{
		Description: &testDesc,
	}
	// Convert Common → API
	apiObj := adapter.convertCommonAccountUpdateToAPI(input)
	require.NotNil(t, apiObj)
}
func TestAccountAdapter_ValidateCreate(t *testing.T) {
	adapter := NewAccountAdapter(&api.ClientWithResponses{})
	t.Run("nil input returns error", func(t *testing.T) {
		err := adapter.ValidateAccountCreate(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "account creation data is required")
	})
	t.Run("missing Name returns error", func(t *testing.T) {
		input := &types.AccountCreate{}
		err := adapter.ValidateAccountCreate(input)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "account name is required")
	})
	t.Run("valid input passes", func(t *testing.T) {
		input := &types.AccountCreate{Name: "test"}
		err := adapter.ValidateAccountCreate(input)
		require.NoError(t, err)
	})
}
func TestAccountAdapter_ValidateUpdate(t *testing.T) {
	adapter := NewAccountAdapter(&api.ClientWithResponses{})
	t.Run("nil input returns error", func(t *testing.T) {
		err := adapter.validateAccountUpdate(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "account update data is required")
	})
	t.Run("valid input passes", func(t *testing.T) {
		input := &types.AccountUpdate{}
		err := adapter.validateAccountUpdate(input)
		require.NoError(t, err)
	})
}
