// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v0_0_42

import (
	api "github.com/jontk/slurm-client/api"
	v0042 "github.com/jontk/slurm-client/internal/openapi/v0_0_42"
)

type AccountConverterGoverterImpl struct{}

func (c *AccountConverterGoverterImpl) ConvertAPIAccountToCommon(source v0042.V0042Account) *api.Account {
	var apiAccount api.Account
	apiAccount.Associations = ConvertAssocShortSlice(source.Associations)
	apiAccount.Coordinators = ConvertCoordSlice(source.Coordinators)
	apiAccount.Description = source.Description
	apiAccount.Flags = ConvertAccountFlags(source.Flags)
	apiAccount.Name = source.Name
	apiAccount.Organization = source.Organization
	return &apiAccount
}
func (c *AccountConverterGoverterImpl) ConvertCommonAccountCreateToAPI(source *api.AccountCreate) *v0042.V0042Account {
	var pV0_0_42V0042Account *v0042.V0042Account
	if source != nil {
		var v0_0_42V0042Account v0042.V0042Account
		v0_0_42V0042Account.Coordinators = ConvertCoordNamesToSlice((*source).Coordinators)
		v0_0_42V0042Account.Description = (*source).Description
		v0_0_42V0042Account.Name = (*source).Name
		v0_0_42V0042Account.Organization = (*source).Organization
		pV0_0_42V0042Account = &v0_0_42V0042Account
	}
	return pV0_0_42V0042Account
}
