// Code generated by generate_adapters.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0

package v0_0_42

import (
	types "github.com/jontk/slurm-client/api"
	"github.com/jontk/slurm-client/pkg/errors"
)

// validateAssociationUpdate validates association update data
func (a *AssociationAdapter) validateAssociationUpdate(update *types.AssociationUpdate) error {
	if update == nil {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "association update data is required", "update", nil, nil)
	}
	if update.DefaultQoS == nil && len(update.QoSList) == 0 && update.MaxJobs == nil && update.MaxSubmitJobs == nil && update.MaxWallTime == nil {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "at least one field must be provided for update", "update", nil, nil)
	}
	return nil
}

// ValidateAssociationCreate validates association create data
func (a *AssociationAdapter) ValidateAssociationCreate(create *types.AssociationCreate) error {
	if create == nil {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "association creation data is required", "create", nil, nil)
	}
	if create.Account == "" {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "account is required", "account", nil, nil)
	}
	if create.User == "" {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "user is required", "user", nil, nil)
	}
	return nil
}
