// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v0_0_42

import (
	api "github.com/jontk/slurm-client/api"
	v0042 "github.com/jontk/slurm-client/internal/openapi/v0_0_42"
)

type AssociationConverterGoverterImpl struct{}

func (c *AssociationConverterGoverterImpl) ConvertAPIAssociationToCommon(source v0042.V0042Assoc) *api.Association {
	var apiAssociation api.Association
	if source.Account != nil {
		xstring := *source.Account
		apiAssociation.Account = &xstring
	}
	apiAssociation.Accounting = ConvertAccounting(source.Accounting)
	if source.Cluster != nil {
		xstring2 := *source.Cluster
		apiAssociation.Cluster = &xstring2
	}
	if source.Comment != nil {
		xstring3 := *source.Comment
		apiAssociation.Comment = &xstring3
	}
	apiAssociation.Default = ConvertAssociationDefault(source.Default)
	apiAssociation.Flags = ConvertAssocFlags(source.Flags)
	if source.Id != nil {
		xint32 := *source.Id
		apiAssociation.ID = &xint32
	}
	if source.IsDefault != nil {
		xbool := *source.IsDefault
		apiAssociation.IsDefault = &xbool
	}
	if source.Lineage != nil {
		xstring4 := *source.Lineage
		apiAssociation.Lineage = &xstring4
	}
	apiAssociation.Max = ConvertAssociationMax(source.Max)
	apiAssociation.Min = ConvertAssociationMin(source.Min)
	if source.ParentAccount != nil {
		xstring5 := *source.ParentAccount
		apiAssociation.ParentAccount = &xstring5
	}
	if source.Partition != nil {
		xstring6 := *source.Partition
		apiAssociation.Partition = &xstring6
	}
	apiAssociation.Priority = ConvertUint32NoVal(source.Priority)
	apiAssociation.QoS = ConvertQosStringIdList(source.Qos)
	if source.SharesRaw != nil {
		xint322 := *source.SharesRaw
		apiAssociation.SharesRaw = &xint322
	}
	apiAssociation.User = source.User
	return &apiAssociation
}
