// Code generated by generate_converters_v2.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0
package v0_0_42

import (
	types "github.com/jontk/slurm-client/api"
	api "github.com/jontk/slurm-client/internal/openapi/v0_0_42"
)

// Helper functions for custom conversions
// These are version-specific and handle complex conversion logic
// convertResumeAfter converts resume after time
func convertResumeAfter(apiResume *api.V0042Uint64NoValStruct) *uint64 {
	if apiResume != nil && apiResume.Number != nil && *apiResume.Number > 0 {
		val := uint64(*apiResume.Number)
		return &val
	}
	return nil
}

// convertNodeEnergy converts API node energy to common type
func convertNodeEnergy(apiEnergy *api.V0042AcctGatherEnergy) *types.NodeEnergy {
	if apiEnergy == nil {
		return nil
	}
	energy := &types.NodeEnergy{}
	if apiEnergy.AverageWatts != nil {
		avgWatts := int32(*apiEnergy.AverageWatts)
		energy.AverageWatts = &avgWatts
	}
	if apiEnergy.BaseConsumedEnergy != nil {
		baseEnergy := *apiEnergy.BaseConsumedEnergy
		energy.BaseConsumedEnergy = &baseEnergy
	}
	if apiEnergy.ConsumedEnergy != nil {
		consumed := *apiEnergy.ConsumedEnergy
		energy.ConsumedEnergy = &consumed
	}
	if apiEnergy.CurrentWatts != nil && apiEnergy.CurrentWatts.Number != nil {
		currentWatts := uint32(*apiEnergy.CurrentWatts.Number)
		energy.CurrentWatts = &currentWatts
	}
	if apiEnergy.LastCollected != nil {
		lastCollected := *apiEnergy.LastCollected
		energy.LastCollected = &lastCollected
	}
	return energy
}

// convertAssocShortSlice converts API AssocShort slice to common type
func convertAssocShortSlice(apiAssocs *api.V0042AssocShortList) []types.AssocShort {
	if apiAssocs == nil {
		return nil
	}
	result := make([]types.AssocShort, len(*apiAssocs))
	for i, assoc := range *apiAssocs {
		result[i] = types.AssocShort{
			Account:   assoc.Account,
			Cluster:   assoc.Cluster,
			ID:        assoc.Id, // Note: Id in API, ID in common
			Partition: assoc.Partition,
			User:      assoc.User,
		}
	}
	return result
}
