// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v0_0_42

import (
	api "github.com/jontk/slurm-client/api"
	v0042 "github.com/jontk/slurm-client/internal/openapi/v0_0_42"
)

type JobConverterGoverterImpl struct{}

func (c *JobConverterGoverterImpl) ConvertAPIJobToCommon(source v0042.V0042JobInfo) *api.Job {
	var apiJob api.Job
	if source.Account != nil {
		xstring := *source.Account
		apiJob.Account = &xstring
	}
	apiJob.AccrueTime = ConvertTimeNoVal(source.AccrueTime)
	if source.AdminComment != nil {
		xstring2 := *source.AdminComment
		apiJob.AdminComment = &xstring2
	}
	if source.AllocatingNode != nil {
		xstring3 := *source.AllocatingNode
		apiJob.AllocatingNode = &xstring3
	}
	apiJob.ArrayJobID = ConvertUint32NoVal(source.ArrayJobId)
	apiJob.ArrayMaxTasks = ConvertUint32NoVal(source.ArrayMaxTasks)
	apiJob.ArrayTaskID = ConvertUint32NoVal(source.ArrayTaskId)
	if source.ArrayTaskString != nil {
		xstring4 := *source.ArrayTaskString
		apiJob.ArrayTaskString = &xstring4
	}
	if source.AssociationId != nil {
		xint32 := *source.AssociationId
		apiJob.AssociationID = &xint32
	}
	if source.BatchFeatures != nil {
		xstring5 := *source.BatchFeatures
		apiJob.BatchFeatures = &xstring5
	}
	if source.BatchFlag != nil {
		xbool := *source.BatchFlag
		apiJob.BatchFlag = &xbool
	}
	if source.BatchHost != nil {
		xstring6 := *source.BatchHost
		apiJob.BatchHost = &xstring6
	}
	apiJob.BillableTRES = ConvertFloat64NoVal(source.BillableTres)
	if source.BurstBuffer != nil {
		xstring7 := *source.BurstBuffer
		apiJob.BurstBuffer = &xstring7
	}
	if source.BurstBufferState != nil {
		xstring8 := *source.BurstBufferState
		apiJob.BurstBufferState = &xstring8
	}
	if source.Cluster != nil {
		xstring9 := *source.Cluster
		apiJob.Cluster = &xstring9
	}
	if source.ClusterFeatures != nil {
		xstring10 := *source.ClusterFeatures
		apiJob.ClusterFeatures = &xstring10
	}
	if source.Command != nil {
		xstring11 := *source.Command
		apiJob.Command = &xstring11
	}
	if source.Comment != nil {
		xstring12 := *source.Comment
		apiJob.Comment = &xstring12
	}
	if source.Container != nil {
		xstring13 := *source.Container
		apiJob.Container = &xstring13
	}
	if source.ContainerId != nil {
		xstring14 := *source.ContainerId
		apiJob.ContainerID = &xstring14
	}
	if source.Contiguous != nil {
		xbool2 := *source.Contiguous
		apiJob.Contiguous = &xbool2
	}
	if source.CoreSpec != nil {
		xint322 := *source.CoreSpec
		apiJob.CoreSpec = &xint322
	}
	apiJob.CoresPerSocket = ConvertUint16NoVal(source.CoresPerSocket)
	apiJob.CPUFrequencyGovernor = ConvertUint32NoVal(source.CpuFrequencyGovernor)
	apiJob.CPUFrequencyMaximum = ConvertUint32NoVal(source.CpuFrequencyMaximum)
	apiJob.CPUFrequencyMinimum = ConvertUint32NoVal(source.CpuFrequencyMinimum)
	apiJob.CPUs = ConvertUint32NoVal(source.Cpus)
	apiJob.CPUsPerTask = ConvertUint16NoVal(source.CpusPerTask)
	if source.CpusPerTres != nil {
		xstring15 := *source.CpusPerTres
		apiJob.CPUsPerTRES = &xstring15
	}
	if source.Cron != nil {
		xstring16 := *source.Cron
		apiJob.Cron = &xstring16
	}
	if source.CurrentWorkingDirectory != nil {
		xstring17 := *source.CurrentWorkingDirectory
		apiJob.CurrentWorkingDirectory = &xstring17
	}
	apiJob.Deadline = ConvertTimeNoVal(source.Deadline)
	apiJob.DelayBoot = ConvertUint32NoVal(source.DelayBoot)
	if source.Dependency != nil {
		xstring18 := *source.Dependency
		apiJob.Dependency = &xstring18
	}
	apiJob.DerivedExitCode = ConvertExitCode(source.DerivedExitCode)
	apiJob.EligibleTime = ConvertTimeNoVal(source.EligibleTime)
	apiJob.EndTime = ConvertTimeNoVal(source.EndTime)
	if source.ExcludedNodes != nil {
		xstring19 := *source.ExcludedNodes
		apiJob.ExcludedNodes = &xstring19
	}
	apiJob.ExitCode = ConvertExitCode(source.ExitCode)
	if source.Extra != nil {
		xstring20 := *source.Extra
		apiJob.Extra = &xstring20
	}
	if source.FailedNode != nil {
		xstring21 := *source.FailedNode
		apiJob.FailedNode = &xstring21
	}
	if source.Features != nil {
		xstring22 := *source.Features
		apiJob.Features = &xstring22
	}
	if source.FederationOrigin != nil {
		xstring23 := *source.FederationOrigin
		apiJob.FederationOrigin = &xstring23
	}
	if source.FederationSiblingsActive != nil {
		xstring24 := *source.FederationSiblingsActive
		apiJob.FederationSiblingsActive = &xstring24
	}
	if source.FederationSiblingsViable != nil {
		xstring25 := *source.FederationSiblingsViable
		apiJob.FederationSiblingsViable = &xstring25
	}
	apiJob.Flags = ConvertJobFlags(source.Flags)
	apiJob.GRESDetail = ConvertJobGRESDetail(source.GresDetail)
	if source.GroupId != nil {
		xint323 := *source.GroupId
		apiJob.GroupID = &xint323
	}
	if source.GroupName != nil {
		xstring26 := *source.GroupName
		apiJob.GroupName = &xstring26
	}
	apiJob.HetJobID = ConvertUint32NoVal(source.HetJobId)
	if source.HetJobIdSet != nil {
		xstring27 := *source.HetJobIdSet
		apiJob.HetJobIDSet = &xstring27
	}
	apiJob.HetJobOffset = ConvertUint32NoVal(source.HetJobOffset)
	if source.Hold != nil {
		xbool3 := *source.Hold
		apiJob.Hold = &xbool3
	}
	if source.JobId != nil {
		xint324 := *source.JobId
		apiJob.JobID = &xint324
	}
	apiJob.JobResources = ConvertJobResources(source.JobResources)
	apiJob.JobSizeStr = ConvertCSVStringToSlice(source.JobSizeStr)
	apiJob.JobState = ConvertJobStateSlice(source.JobState)
	apiJob.LastSchedEvaluation = ConvertTimeNoVal(source.LastSchedEvaluation)
	if source.Licenses != nil {
		xstring28 := *source.Licenses
		apiJob.Licenses = &xstring28
	}
	apiJob.MailType = ConvertJobMailType(source.MailType)
	if source.MailUser != nil {
		xstring29 := *source.MailUser
		apiJob.MailUser = &xstring29
	}
	apiJob.MaxCPUs = ConvertUint32NoVal(source.MaxCpus)
	apiJob.MaxNodes = ConvertUint32NoVal(source.MaxNodes)
	if source.MaximumSwitchWaitTime != nil {
		xint325 := *source.MaximumSwitchWaitTime
		apiJob.MaximumSwitchWaitTime = &xint325
	}
	if source.McsLabel != nil {
		xstring30 := *source.McsLabel
		apiJob.MCSLabel = &xstring30
	}
	apiJob.MemoryPerCPU = ConvertUint64NoVal(source.MemoryPerCpu)
	apiJob.MemoryPerNode = ConvertUint64NoVal(source.MemoryPerNode)
	if source.MemoryPerTres != nil {
		xstring31 := *source.MemoryPerTres
		apiJob.MemoryPerTRES = &xstring31
	}
	apiJob.MinimumCPUsPerNode = ConvertUint16NoVal(source.MinimumCpusPerNode)
	apiJob.MinimumTmpDiskPerNode = ConvertUint32NoVal(source.MinimumTmpDiskPerNode)
	if source.Name != nil {
		xstring32 := *source.Name
		apiJob.Name = &xstring32
	}
	if source.Network != nil {
		xstring33 := *source.Network
		apiJob.Network = &xstring33
	}
	if source.Nice != nil {
		xint326 := *source.Nice
		apiJob.Nice = &xint326
	}
	apiJob.NodeCount = ConvertUint32NoVal(source.NodeCount)
	if source.Nodes != nil {
		xstring34 := *source.Nodes
		apiJob.Nodes = &xstring34
	}
	if source.Partition != nil {
		xstring35 := *source.Partition
		apiJob.Partition = &xstring35
	}
	apiJob.Power = ConvertJobPower(source.Power)
	apiJob.PreSusTime = ConvertUint64NoVal(source.PreSusTime)
	apiJob.PreemptTime = ConvertTimeNoVal(source.PreemptTime)
	apiJob.PreemptableTime = ConvertTimeNoVal(source.PreemptableTime)
	if source.Prefer != nil {
		xstring36 := *source.Prefer
		apiJob.Prefer = &xstring36
	}
	apiJob.Priority = ConvertUint32NoVal(source.Priority)
	apiJob.PriorityByPartition = ConvertJobPriorityByPartition(source.PriorityByPartition)
	apiJob.Profile = ConvertJobProfile(source.Profile)
	if source.Qos != nil {
		xstring37 := *source.Qos
		apiJob.QoS = &xstring37
	}
	if source.Reboot != nil {
		xbool4 := *source.Reboot
		apiJob.Reboot = &xbool4
	}
	if source.Requeue != nil {
		xbool5 := *source.Requeue
		apiJob.Requeue = &xbool5
	}
	if source.RequiredNodes != nil {
		xstring38 := *source.RequiredNodes
		apiJob.RequiredNodes = &xstring38
	}
	if source.RequiredSwitches != nil {
		xint327 := *source.RequiredSwitches
		apiJob.RequiredSwitches = &xint327
	}
	apiJob.ResizeTime = ConvertTimeNoVal(source.ResizeTime)
	if source.RestartCnt != nil {
		xint328 := *source.RestartCnt
		apiJob.RestartCnt = &xint328
	}
	if source.ResvName != nil {
		xstring39 := *source.ResvName
		apiJob.ResvName = &xstring39
	}
	if source.ScheduledNodes != nil {
		xstring40 := *source.ScheduledNodes
		apiJob.ScheduledNodes = &xstring40
	}
	if source.SelinuxContext != nil {
		xstring41 := *source.SelinuxContext
		apiJob.SelinuxContext = &xstring41
	}
	apiJob.Shared = ConvertJobShared(source.Shared)
	if source.SocketsPerBoard != nil {
		xint329 := *source.SocketsPerBoard
		apiJob.SocketsPerBoard = &xint329
	}
	apiJob.SocketsPerNode = ConvertUint16NoVal(source.SocketsPerNode)
	if source.StandardError != nil {
		xstring42 := *source.StandardError
		apiJob.StandardError = &xstring42
	}
	if source.StandardInput != nil {
		xstring43 := *source.StandardInput
		apiJob.StandardInput = &xstring43
	}
	if source.StandardOutput != nil {
		xstring44 := *source.StandardOutput
		apiJob.StandardOutput = &xstring44
	}
	apiJob.StartTime = ConvertTimeNoVal(source.StartTime)
	if source.StateDescription != nil {
		xstring45 := *source.StateDescription
		apiJob.StateDescription = &xstring45
	}
	if source.StateReason != nil {
		xstring46 := *source.StateReason
		apiJob.StateReason = &xstring46
	}
	apiJob.SubmitTime = ConvertTimeNoVal(source.SubmitTime)
	apiJob.SuspendTime = ConvertTimeNoVal(source.SuspendTime)
	if source.SystemComment != nil {
		xstring47 := *source.SystemComment
		apiJob.SystemComment = &xstring47
	}
	apiJob.Tasks = ConvertUint32NoVal(source.Tasks)
	apiJob.TasksPerBoard = ConvertUint16NoVal(source.TasksPerBoard)
	apiJob.TasksPerCore = ConvertUint16NoVal(source.TasksPerCore)
	apiJob.TasksPerNode = ConvertUint16NoVal(source.TasksPerNode)
	apiJob.TasksPerSocket = ConvertUint16NoVal(source.TasksPerSocket)
	apiJob.TasksPerTRES = ConvertUint16NoVal(source.TasksPerTres)
	if source.ThreadSpec != nil {
		xint3210 := *source.ThreadSpec
		apiJob.ThreadSpec = &xint3210
	}
	apiJob.ThreadsPerCore = ConvertUint16NoVal(source.ThreadsPerCore)
	apiJob.TimeLimit = ConvertUint32NoVal(source.TimeLimit)
	apiJob.TimeMinimum = ConvertUint32NoVal(source.TimeMinimum)
	if source.TresAllocStr != nil {
		xstring48 := *source.TresAllocStr
		apiJob.TRESAllocStr = &xstring48
	}
	if source.TresBind != nil {
		xstring49 := *source.TresBind
		apiJob.TRESBind = &xstring49
	}
	if source.TresFreq != nil {
		xstring50 := *source.TresFreq
		apiJob.TRESFreq = &xstring50
	}
	if source.TresPerJob != nil {
		xstring51 := *source.TresPerJob
		apiJob.TRESPerJob = &xstring51
	}
	if source.TresPerNode != nil {
		xstring52 := *source.TresPerNode
		apiJob.TRESPerNode = &xstring52
	}
	if source.TresPerSocket != nil {
		xstring53 := *source.TresPerSocket
		apiJob.TRESPerSocket = &xstring53
	}
	if source.TresPerTask != nil {
		xstring54 := *source.TresPerTask
		apiJob.TRESPerTask = &xstring54
	}
	if source.TresReqStr != nil {
		xstring55 := *source.TresReqStr
		apiJob.TRESReqStr = &xstring55
	}
	if source.UserId != nil {
		xint3211 := *source.UserId
		apiJob.UserID = &xint3211
	}
	if source.UserName != nil {
		xstring56 := *source.UserName
		apiJob.UserName = &xstring56
	}
	if source.Wckey != nil {
		xstring57 := *source.Wckey
		apiJob.Wckey = &xstring57
	}
	return &apiJob
}
