// Code generated by generate_adapters.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0

package v0_0_42

import (
	"context"
	"fmt"
	"strconv"

	types "github.com/jontk/slurm-client/api"
	adapterbase "github.com/jontk/slurm-client/internal/adapters/base"
	"github.com/jontk/slurm-client/internal/common"
	api "github.com/jontk/slurm-client/internal/openapi/v0_0_42"
	"github.com/jontk/slurm-client/pkg/errors"
)

// JobAdapter implements the Job adapter interface for v0_0_42
type JobAdapter struct {
	*adapterbase.BaseManager
	client *api.ClientWithResponses
}

// NewJobAdapter creates a new Job adapter
func NewJobAdapter(client *api.ClientWithResponses) *JobAdapter {
	return &JobAdapter{
		BaseManager: adapterbase.NewBaseManager("v0.0.42", "Job"),
		client:      client,
	}
}

// List retrieves a list of jobs with optional filtering
func (a *JobAdapter) List(ctx context.Context, opts *types.JobListOptions) (*types.JobList, error) {
	// Validate context
	if err := a.ValidateContext(ctx); err != nil {
		return nil, err
	}

	// Check client initialization
	if err := a.CheckClientInitialized(a.client); err != nil {
		return nil, err
	}

	// Prepare parameters
	params := &api.SlurmV0042GetJobsParams{}

	// Call the API
	resp, err := a.client.SlurmV0042GetJobsWithResponse(ctx, params)
	if err != nil {
		return nil, a.HandleAPIError(err)
	}

	// Handle response errors
	var apiErrors *api.V0042OpenapiErrors
	if resp.JSON200 != nil {
		apiErrors = resp.JSON200.Errors
	} else if resp.JSONDefault != nil {
		apiErrors = resp.JSONDefault.Errors
	}
	responseAdapter := api.NewResponseAdapter(resp.StatusCode(), apiErrors)
	if err := common.HandleAPIResponse(responseAdapter, "v0.0.42"); err != nil {
		return nil, err
	}

	// Check for nil response
	if err := a.CheckNilResponse(resp.JSON200, "List Jobs"); err != nil {
		return nil, err
	}

	// Convert response to common types
	items := make([]types.Job, 0, len(resp.JSON200.Jobs))
	for _, apiItem := range resp.JSON200.Jobs {
		item := a.convertAPIJobToCommon(apiItem)
		items = append(items, *item)
	}

	// Apply filtering before pagination
	jobBaseManager := adapterbase.NewJobBaseManager("v0.0.42")
	items = jobBaseManager.FilterJobList(items, opts)

	// Apply pagination
	listOpts := adapterbase.ListOptions{}
	if opts != nil {
		listOpts.Limit = opts.Limit
		listOpts.Offset = opts.Offset
	}

	start := listOpts.Offset
	if start < 0 {
		start = 0
	}
	if start >= len(items) {
		return &types.JobList{
			Jobs:  []types.Job{},
			Total: len(items),
		}, nil
	}

	end := len(items)
	if listOpts.Limit > 0 {
		end = start + listOpts.Limit
		if end > len(items) {
			end = len(items)
		}
	}

	return &types.JobList{
		Jobs:  items[start:end],
		Total: len(items),
	}, nil
}

// Get retrieves a specific job by jobID
func (a *JobAdapter) Get(ctx context.Context, jobID int32) (*types.Job, error) {
	// Validate context
	if err := a.ValidateContext(ctx); err != nil {
		return nil, err
	}
	if err := a.ValidateResourceID(jobID, "jobID"); err != nil {
		return nil, err
	}
	if err := a.CheckClientInitialized(a.client); err != nil {
		return nil, err
	}

	// Prepare parameters
	params := &api.SlurmV0042GetJobParams{}

	// Call the API
	resp, err := a.client.SlurmV0042GetJobWithResponse(ctx, strconv.Itoa(int(jobID)), params)
	if err != nil {
		return nil, a.HandleAPIError(err)
	}

	// Handle response errors
	var apiErrors *api.V0042OpenapiErrors
	if resp.JSON200 != nil {
		apiErrors = resp.JSON200.Errors
	} else if resp.JSONDefault != nil {
		apiErrors = resp.JSONDefault.Errors
	}
	responseAdapter := api.NewResponseAdapter(resp.StatusCode(), apiErrors)
	if err := common.HandleAPIResponse(responseAdapter, "v0.0.42"); err != nil {
		return nil, err
	}

	// Check for nil response
	if err := a.CheckNilResponse(resp.JSON200, "Get Job"); err != nil {
		return nil, err
	}

	// Check if entity exists
	if len(resp.JSON200.Jobs) == 0 {
		return nil, errors.NewSlurmError(errors.ErrorCodeResourceNotFound,
			fmt.Sprintf("Job %d not found", jobID))
	}

	// Convert and return
	return a.convertAPIJobToCommon(resp.JSON200.Jobs[0]), nil
}

// Submit submits a new job
func (a *JobAdapter) Submit(ctx context.Context, job *types.JobCreate) (*types.JobSubmitResponse, error) {
	// Validate context
	if err := a.ValidateContext(ctx); err != nil {
		return nil, err
	}
	if job == nil {
		return nil, errors.NewValidationError(errors.ErrorCodeValidationFailed, "job is required", "job", nil, nil)
	}
	if err := a.CheckClientInitialized(a.client); err != nil {
		return nil, err
	}

	// Convert to API type
	apiJob := a.convertCommonJobCreateToAPI(job)

	// Call the API
	resp, err := a.client.SlurmV0042PostJobSubmitWithResponse(ctx, apiJob)
	if err != nil {
		return nil, a.HandleAPIError(err)
	}

	// Handle response errors — check JSONDefault on non-200 responses so that
	// the actual SLURM rejection reason is surfaced instead of a generic HTTP error.
	var apiErrors *api.V0042OpenapiErrors
	if resp.JSON200 != nil {
		apiErrors = resp.JSON200.Errors
	} else if resp.JSONDefault != nil {
		apiErrors = resp.JSONDefault.Errors
	}
	responseAdapter := api.NewResponseAdapter(resp.StatusCode(), apiErrors)
	if err := common.HandleAPIResponse(responseAdapter, "v0.0.42"); err != nil {
		return nil, err
	}

	// Extract job ID from response
	return a.convertAPIJobSubmitResponseToCommon(resp.JSON200), nil
}

// Update updates an existing job
func (a *JobAdapter) Update(ctx context.Context, jobID int32, update *types.JobUpdate) error {
	// Validate context
	if err := a.ValidateContext(ctx); err != nil {
		return err
	}
	if err := a.ValidateResourceID(jobID, "jobID"); err != nil {
		return err
	}
	if update == nil {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "update is required", "update", nil, nil)
	}
	if err := a.CheckClientInitialized(a.client); err != nil {
		return err
	}

	// Convert to API type
	reqBody := a.convertCommonJobUpdateToAPIRequestBody(update)

	// Call the API with job ID in path
	resp, err := a.client.SlurmV0042PostJobWithResponse(ctx, strconv.Itoa(int(jobID)), reqBody)
	if err != nil {
		return a.HandleAPIError(err)
	}

	// Handle response errors
	var apiErrors *api.V0042OpenapiErrors
	if resp.JSON200 != nil {
		apiErrors = resp.JSON200.Errors
	} else if resp.JSONDefault != nil {
		apiErrors = resp.JSONDefault.Errors
	}
	responseAdapter := api.NewResponseAdapter(resp.StatusCode(), apiErrors)
	return common.HandleAPIResponse(responseAdapter, "v0.0.42")
}

// Cancel cancels a job
func (a *JobAdapter) Cancel(ctx context.Context, jobID int32, opts *types.JobCancelRequest) error {
	// Validate context
	if err := a.ValidateContext(ctx); err != nil {
		return err
	}
	if err := a.ValidateResourceID(jobID, "jobID"); err != nil {
		return err
	}
	if err := a.CheckClientInitialized(a.client); err != nil {
		return err
	}

	// Call the delete/cancel API
	resp, err := a.client.SlurmV0042DeleteJobWithResponse(ctx, strconv.Itoa(int(jobID)), nil)
	if err != nil {
		return a.HandleAPIError(err)
	}

	// Handle response
	if resp.StatusCode() == 204 || resp.StatusCode() == 200 {
		return nil
	}

	var apiErrors *api.V0042OpenapiErrors
	if resp.JSON200 != nil {
		apiErrors = resp.JSON200.Errors
	} else if resp.JSONDefault != nil {
		apiErrors = resp.JSONDefault.Errors
	}
	responseAdapter := api.NewResponseAdapter(resp.StatusCode(), apiErrors)
	return common.HandleAPIResponse(responseAdapter, "v0.0.42")
}

// Hold places a job on hold
func (a *JobAdapter) Hold(ctx context.Context, req *types.JobHoldRequest) error {
	return a.holdJobImpl(ctx, req)
}

// Release is handled via Hold method with release flag

// Signal sends a signal to a job
func (a *JobAdapter) Signal(ctx context.Context, req *types.JobSignalRequest) error {
	return a.signalJobImpl(ctx, req)
}

// Notify sends a notification to a job
func (a *JobAdapter) Notify(ctx context.Context, req *types.JobNotifyRequest) error {
	return a.notifyJobImpl(ctx, req)
}

// Requeue requeues a job
func (a *JobAdapter) Requeue(ctx context.Context, jobID int32) error {
	return a.requeueJobImpl(ctx, jobID)
}

// Watch watches for job events
func (a *JobAdapter) Watch(ctx context.Context, opts *types.JobWatchOptions) (<-chan types.JobWatchEvent, error) {
	return a.watchJobsImpl(ctx, opts)
}

// Allocate allocates resources for a job
func (a *JobAdapter) Allocate(ctx context.Context, req *types.JobAllocateRequest) (*types.JobAllocateResponse, error) {
	return a.allocateJobImpl(ctx, req)
}
