// Code generated by generate_adapters.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0

package v0_0_42

import (
	types "github.com/jontk/slurm-client/api"
	"github.com/jontk/slurm-client/pkg/errors"
)

// ValidateJobCreate validates job create data
func (a *JobAdapter) ValidateJobCreate(create *types.JobCreate) error {
	if create == nil {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "job creation data is required", "create", nil, nil)
	}
	if create.Script == nil || *create.Script == "" {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "job script is required", "script", nil, nil)
	}
	return nil
}

// validateJobUpdate validates job update data
func (a *JobAdapter) validateJobUpdate(update *types.JobUpdate) error {
	if update == nil {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "job update data is required", "update", nil, nil)
	}
	return nil
}
