// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v0_0_42

import (
	api "github.com/jontk/slurm-client/api"
	v0042 "github.com/jontk/slurm-client/internal/openapi/v0_0_42"
)

type NodeConverterGoverterImpl struct{}

func (c *NodeConverterGoverterImpl) ConvertAPINodeToCommon(source v0042.V0042Node) *api.Node {
	var apiNode api.Node
	apiNode.ActiveFeatures = ConvertCSVStringToSlice(source.ActiveFeatures)
	if source.Address != nil {
		xstring := *source.Address
		apiNode.Address = &xstring
	}
	if source.AllocCpus != nil {
		xint32 := *source.AllocCpus
		apiNode.AllocCPUs = &xint32
	}
	if source.AllocIdleCpus != nil {
		xint322 := *source.AllocIdleCpus
		apiNode.AllocIdleCPUs = &xint322
	}
	if source.AllocMemory != nil {
		xint64 := *source.AllocMemory
		apiNode.AllocMemory = &xint64
	}
	if source.Architecture != nil {
		xstring2 := *source.Architecture
		apiNode.Architecture = &xstring2
	}
	if source.Boards != nil {
		xint323 := *source.Boards
		apiNode.Boards = &xint323
	}
	apiNode.BootTime = ConvertTimeNoVal(source.BootTime)
	if source.BurstbufferNetworkAddress != nil {
		xstring3 := *source.BurstbufferNetworkAddress
		apiNode.BurstbufferNetworkAddress = &xstring3
	}
	if source.ClusterName != nil {
		xstring4 := *source.ClusterName
		apiNode.ClusterName = &xstring4
	}
	if source.Comment != nil {
		xstring5 := *source.Comment
		apiNode.Comment = &xstring5
	}
	if source.Cores != nil {
		xint324 := *source.Cores
		apiNode.Cores = &xint324
	}
	if source.CpuBinding != nil {
		xint325 := *source.CpuBinding
		apiNode.CPUBinding = &xint325
	}
	if source.CpuLoad != nil {
		xint326 := *source.CpuLoad
		apiNode.CPULoad = &xint326
	}
	if source.Cpus != nil {
		xint327 := *source.Cpus
		apiNode.CPUs = &xint327
	}
	if source.EffectiveCpus != nil {
		xint328 := *source.EffectiveCpus
		apiNode.EffectiveCPUs = &xint328
	}
	apiNode.Energy = ConvertNodeEnergyGoverter(source.Energy)
	apiNode.ExternalSensors = ConvertExternalSensors(source.ExternalSensors)
	if source.Extra != nil {
		xstring6 := *source.Extra
		apiNode.Extra = &xstring6
	}
	apiNode.Features = ConvertCSVStringToSlice(source.Features)
	apiNode.FreeMem = ConvertUint64NoVal(source.FreeMem)
	if source.GpuSpec != nil {
		xstring7 := *source.GpuSpec
		apiNode.GPUSpec = &xstring7
	}
	if source.Gres != nil {
		xstring8 := *source.Gres
		apiNode.GRES = &xstring8
	}
	if source.GresDrained != nil {
		xstring9 := *source.GresDrained
		apiNode.GRESDrained = &xstring9
	}
	if source.GresUsed != nil {
		xstring10 := *source.GresUsed
		apiNode.GRESUsed = &xstring10
	}
	if source.Hostname != nil {
		xstring11 := *source.Hostname
		apiNode.Hostname = &xstring11
	}
	if source.InstanceId != nil {
		xstring12 := *source.InstanceId
		apiNode.InstanceID = &xstring12
	}
	if source.InstanceType != nil {
		xstring13 := *source.InstanceType
		apiNode.InstanceType = &xstring13
	}
	apiNode.LastBusy = ConvertTimeNoVal(source.LastBusy)
	if source.McsLabel != nil {
		xstring14 := *source.McsLabel
		apiNode.MCSLabel = &xstring14
	}
	if source.Name != nil {
		xstring15 := *source.Name
		apiNode.Name = &xstring15
	}
	apiNode.NextStateAfterReboot = ConvertNextStateAfterReboot(source.NextStateAfterReboot)
	if source.OperatingSystem != nil {
		xstring16 := *source.OperatingSystem
		apiNode.OperatingSystem = &xstring16
	}
	if source.Owner != nil {
		xstring17 := *source.Owner
		apiNode.Owner = &xstring17
	}
	apiNode.Partitions = ConvertCSVStringToSlice(source.Partitions)
	if source.Port != nil {
		xint329 := *source.Port
		apiNode.Port = &xint329
	}
	apiNode.Power = ConvertPower(source.Power)
	if source.RealMemory != nil {
		xint642 := *source.RealMemory
		apiNode.RealMemory = &xint642
	}
	if source.Reason != nil {
		xstring18 := *source.Reason
		apiNode.Reason = &xstring18
	}
	apiNode.ReasonChangedAt = ConvertTimeNoVal(source.ReasonChangedAt)
	if source.ReasonSetByUser != nil {
		xstring19 := *source.ReasonSetByUser
		apiNode.ReasonSetByUser = &xstring19
	}
	if source.ResCoresPerGpu != nil {
		xint3210 := *source.ResCoresPerGpu
		apiNode.ResCoresPerGPU = &xint3210
	}
	if source.Reservation != nil {
		xstring20 := *source.Reservation
		apiNode.Reservation = &xstring20
	}
	apiNode.ResumeAfter = ConvertResumeAfterGoverter(source.ResumeAfter)
	apiNode.SlurmdStartTime = ConvertTimeNoVal(source.SlurmdStartTime)
	if source.Sockets != nil {
		xint3211 := *source.Sockets
		apiNode.Sockets = &xint3211
	}
	if source.SpecializedCores != nil {
		xint3212 := *source.SpecializedCores
		apiNode.SpecializedCores = &xint3212
	}
	if source.SpecializedCpus != nil {
		xstring21 := *source.SpecializedCpus
		apiNode.SpecializedCPUs = &xstring21
	}
	if source.SpecializedMemory != nil {
		xint643 := *source.SpecializedMemory
		apiNode.SpecializedMemory = &xint643
	}
	apiNode.State = ConvertNodeStateSlice(source.State)
	if source.TemporaryDisk != nil {
		xint3213 := *source.TemporaryDisk
		apiNode.TemporaryDisk = &xint3213
	}
	if source.Threads != nil {
		xint3214 := *source.Threads
		apiNode.Threads = &xint3214
	}
	if source.Tres != nil {
		xstring22 := *source.Tres
		apiNode.TRES = &xstring22
	}
	if source.TresUsed != nil {
		xstring23 := *source.TresUsed
		apiNode.TRESUsed = &xstring23
	}
	if source.TresWeighted != nil {
		xfloat64 := *source.TresWeighted
		apiNode.TRESWeighted = &xfloat64
	}
	if source.Version != nil {
		xstring24 := *source.Version
		apiNode.Version = &xstring24
	}
	if source.Weight != nil {
		xint3215 := *source.Weight
		apiNode.Weight = &xint3215
	}
	return &apiNode
}
