// Code generated by generate_adapters.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0
package v0_0_42

import (
	"context"

	types "github.com/jontk/slurm-client/api"
	"github.com/jontk/slurm-client/internal/common"
	api "github.com/jontk/slurm-client/internal/openapi/v0_0_42"
)

// drainNodeImpl implements the Drain method
func (a *NodeAdapter) drainNodeImpl(ctx context.Context, nodeName string, reason string) error {
	// Validate context
	if err := a.ValidateContext(ctx); err != nil {
		return err
	}
	// Validate node name
	if err := a.ValidateResourceName(nodeName, "nodeName"); err != nil {
		return err
	}
	// Check client initialization
	if err := a.CheckClientInitialized(a.client); err != nil {
		return err
	}
	// Build node update request with DRAIN state
	updateReq := api.V0042UpdateNodeMsg{
		State: &[]string{"DRAIN"},
	}
	if reason != "" {
		updateReq.Reason = &reason
	}
	// Call the API to update the node
	resp, err := a.client.SlurmV0042PostNodeWithResponse(ctx, nodeName, updateReq)
	if err != nil {
		return a.HandleAPIError(err)
	}
	// Handle response errors
	var apiErrors *api.V0042OpenapiErrors
	if resp.JSON200 != nil {
		apiErrors = resp.JSON200.Errors
	}
	responseAdapter := api.NewResponseAdapter(resp.StatusCode(), apiErrors)
	if err := common.HandleAPIResponse(responseAdapter, "v0.0.42"); err != nil {
		return err
	}
	return nil
}

// resumeNodeImpl implements the Resume method
func (a *NodeAdapter) resumeNodeImpl(ctx context.Context, nodeName string) error {
	// Validate context
	if err := a.ValidateContext(ctx); err != nil {
		return err
	}
	// Validate node name
	if err := a.ValidateResourceName(nodeName, "nodeName"); err != nil {
		return err
	}
	// Check client initialization
	if err := a.CheckClientInitialized(a.client); err != nil {
		return err
	}
	// Build node update request with RESUME state
	updateReq := api.V0042UpdateNodeMsg{
		State: &[]string{"RESUME"},
	}
	// Call the API to update the node
	resp, err := a.client.SlurmV0042PostNodeWithResponse(ctx, nodeName, updateReq)
	if err != nil {
		return a.HandleAPIError(err)
	}
	// Handle response errors
	var apiErrors *api.V0042OpenapiErrors
	if resp.JSON200 != nil {
		apiErrors = resp.JSON200.Errors
	}
	responseAdapter := api.NewResponseAdapter(resp.StatusCode(), apiErrors)
	if err := common.HandleAPIResponse(responseAdapter, "v0.0.42"); err != nil {
		return err
	}
	return nil
}

// NOTE: watchNodesImpl is intentionally NOT generated here.
// The real implementation is in node_watch_extra.go which uses polling.
// convertCommonNodeUpdateToAPIRequestBody converts NodeUpdate to the API request body type
func (a *NodeAdapter) convertCommonNodeUpdateToAPIRequestBody(update *types.NodeUpdate) api.SlurmV0042PostNodeJSONRequestBody {
	if update == nil {
		return api.SlurmV0042PostNodeJSONRequestBody{}
	}
	// Delegate to the goverter-generated ConvertCommonNodeUpdateToAPI
	result := nodeWriteConverter.ConvertCommonNodeUpdateToAPI(update)
	if result == nil {
		return api.SlurmV0042PostNodeJSONRequestBody{}
	}
	return *result
}
