// Code generated by generate_adapters.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0

package v0_0_42

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	types "github.com/jontk/slurm-client/api"
	api "github.com/jontk/slurm-client/internal/openapi/v0_0_42"
)

func TestNewPartitionAdapter(t *testing.T) {
	client := &api.ClientWithResponses{}
	adapter := NewPartitionAdapter(client)
	require.NotNil(t, adapter)
}

func TestPartitionAdapter_ValidateContext(t *testing.T) {
	adapter := NewPartitionAdapter(&api.ClientWithResponses{})

	// Test nil context
	//lint:ignore SA1012 intentionally testing nil context validation
	err := adapter.ValidateContext(nil)
	assert.Error(t, err)

	// Test valid context
	err = adapter.ValidateContext(context.Background())
	assert.NoError(t, err)
}

func TestPartitionAdapter_List_NilContext(t *testing.T) {
	adapter := NewPartitionAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.List(nil, nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestPartitionAdapter_List_ClientNotInitialized(t *testing.T) {
	adapter := NewPartitionAdapter(nil)

	result, err := adapter.List(context.Background(), nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestPartitionAdapter_Get_NilContext(t *testing.T) {
	adapter := NewPartitionAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.Get(nil, "test-partition")
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestPartitionAdapter_Get_EmptyIdentifier(t *testing.T) {
	adapter := NewPartitionAdapter(&api.ClientWithResponses{})

	result, err := adapter.Get(context.Background(), "")
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestPartitionAdapter_Get_ClientNotInitialized(t *testing.T) {
	adapter := NewPartitionAdapter(nil)

	result, err := adapter.Get(context.Background(), "test-partition")
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestPartitionAdapter_Create_NilContext(t *testing.T) {
	adapter := NewPartitionAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.Create(nil, &types.PartitionCreate{})
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestPartitionAdapter_Create_NilInput(t *testing.T) {
	adapter := NewPartitionAdapter(&api.ClientWithResponses{})

	result, err := adapter.Create(context.Background(), nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestPartitionAdapter_Create_ClientNotInitialized(t *testing.T) {
	adapter := NewPartitionAdapter(nil)

	result, err := adapter.Create(context.Background(), &types.PartitionCreate{})
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestPartitionAdapter_Update_NilContext(t *testing.T) {
	adapter := NewPartitionAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	err := adapter.Update(nil, "test-partition", &types.PartitionUpdate{})
	assert.Error(t, err)
}

func TestPartitionAdapter_Update_NilInput(t *testing.T) {
	adapter := NewPartitionAdapter(&api.ClientWithResponses{})

	err := adapter.Update(context.Background(), "test-partition", nil)
	assert.Error(t, err)
}

func TestPartitionAdapter_Update_ClientNotInitialized(t *testing.T) {
	adapter := NewPartitionAdapter(nil)

	err := adapter.Update(context.Background(), "test-partition", &types.PartitionUpdate{})
	assert.Error(t, err)
}

func TestPartitionAdapter_Delete_NilContext(t *testing.T) {
	adapter := NewPartitionAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	err := adapter.Delete(nil, "test-partition")
	assert.Error(t, err)
}

func TestPartitionAdapter_Delete_EmptyIdentifier(t *testing.T) {
	adapter := NewPartitionAdapter(&api.ClientWithResponses{})

	err := adapter.Delete(context.Background(), "")
	assert.Error(t, err)
}

func TestPartitionAdapter_Delete_ClientNotInitialized(t *testing.T) {
	adapter := NewPartitionAdapter(nil)

	err := adapter.Delete(context.Background(), "test-partition")
	assert.Error(t, err)
}

func TestPartitionAdapter_ReadConverter(t *testing.T) {
	adapter := NewPartitionAdapter(&api.ClientWithResponses{})

	// Create test API object with known values
	testName := "test-partition"
	testCluster := "test-cluster"
	apiObj := api.V0042PartitionInfo{
		Name:    &testName,
		Cluster: &testCluster,
	}

	// Convert API → Common
	commonObj := adapter.convertAPIPartitionToCommon(apiObj)
	require.NotNil(t, commonObj)

	// Verify field values were correctly converted
	if commonObj.Name != nil {
		assert.Equal(t, testName, *commonObj.Name)
	}
	if commonObj.Cluster != nil {
		assert.Equal(t, testCluster, *commonObj.Cluster)
	}
}
