// Code generated by generate_adapters.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0

package v0_0_42

import (
	"context"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	types "github.com/jontk/slurm-client/api"
	api "github.com/jontk/slurm-client/internal/openapi/v0_0_42"
)

func TestNewReservationAdapter(t *testing.T) {
	client := &api.ClientWithResponses{}
	adapter := NewReservationAdapter(client)
	require.NotNil(t, adapter)
}

func TestReservationAdapter_ValidateContext(t *testing.T) {
	adapter := NewReservationAdapter(&api.ClientWithResponses{})

	// Test nil context
	//lint:ignore SA1012 intentionally testing nil context validation
	err := adapter.ValidateContext(nil)
	assert.Error(t, err)

	// Test valid context
	err = adapter.ValidateContext(context.Background())
	assert.NoError(t, err)
}

func TestReservationAdapter_List_NilContext(t *testing.T) {
	adapter := NewReservationAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.List(nil, nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestReservationAdapter_List_ClientNotInitialized(t *testing.T) {
	adapter := NewReservationAdapter(nil)

	result, err := adapter.List(context.Background(), nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestReservationAdapter_Get_NilContext(t *testing.T) {
	adapter := NewReservationAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.Get(nil, "test-reservation")
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestReservationAdapter_Get_EmptyIdentifier(t *testing.T) {
	adapter := NewReservationAdapter(&api.ClientWithResponses{})

	result, err := adapter.Get(context.Background(), "")
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestReservationAdapter_Get_ClientNotInitialized(t *testing.T) {
	adapter := NewReservationAdapter(nil)

	result, err := adapter.Get(context.Background(), "test-reservation")
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestReservationAdapter_Create_NilContext(t *testing.T) {
	adapter := NewReservationAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.Create(nil, &types.ReservationCreate{})
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestReservationAdapter_Create_NilInput(t *testing.T) {
	adapter := NewReservationAdapter(&api.ClientWithResponses{})

	result, err := adapter.Create(context.Background(), nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestReservationAdapter_Create_ClientNotInitialized(t *testing.T) {
	adapter := NewReservationAdapter(nil)

	result, err := adapter.Create(context.Background(), &types.ReservationCreate{})
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestReservationAdapter_Update_NilContext(t *testing.T) {
	adapter := NewReservationAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	err := adapter.Update(nil, "test-reservation", &types.ReservationUpdate{})
	assert.Error(t, err)
}

func TestReservationAdapter_Update_NilInput(t *testing.T) {
	adapter := NewReservationAdapter(&api.ClientWithResponses{})

	err := adapter.Update(context.Background(), "test-reservation", nil)
	assert.Error(t, err)
}

func TestReservationAdapter_Update_ClientNotInitialized(t *testing.T) {
	adapter := NewReservationAdapter(nil)

	err := adapter.Update(context.Background(), "test-reservation", &types.ReservationUpdate{})
	assert.Error(t, err)
}

func TestReservationAdapter_Delete_NilContext(t *testing.T) {
	adapter := NewReservationAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	err := adapter.Delete(nil, "test-reservation")
	assert.Error(t, err)
}

func TestReservationAdapter_Delete_EmptyIdentifier(t *testing.T) {
	adapter := NewReservationAdapter(&api.ClientWithResponses{})

	err := adapter.Delete(context.Background(), "")
	assert.Error(t, err)
}

func TestReservationAdapter_Delete_ClientNotInitialized(t *testing.T) {
	adapter := NewReservationAdapter(nil)

	err := adapter.Delete(context.Background(), "test-reservation")
	assert.Error(t, err)
}

func TestReservationAdapter_ReadConverter(t *testing.T) {
	adapter := NewReservationAdapter(&api.ClientWithResponses{})

	// Create test API object with known values
	testName := "test-reservation"
	apiObj := api.V0042ReservationInfo{
		Name: &testName,
	}

	// Convert API → Common
	commonObj := adapter.convertAPIReservationToCommon(apiObj)
	require.NotNil(t, commonObj)

	// Verify field values were correctly converted
	if commonObj.Name != nil {
		assert.Equal(t, testName, *commonObj.Name)
	}
}

func TestReservationAdapter_ValidateCreate(t *testing.T) {
	adapter := NewReservationAdapter(&api.ClientWithResponses{})

	t.Run("nil input returns error", func(t *testing.T) {
		err := adapter.ValidateReservationCreate(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "reservation creation data is required")
	})

	t.Run("missing Name returns error", func(t *testing.T) {
		input := &types.ReservationCreate{StartTime: time.Now()}
		err := adapter.ValidateReservationCreate(input)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "reservation name is required")
	})

	t.Run("missing StartTime returns error", func(t *testing.T) {
		input := &types.ReservationCreate{Name: ptrString("test")}
		err := adapter.ValidateReservationCreate(input)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "start time is required")
	})

	t.Run("valid input passes", func(t *testing.T) {
		input := &types.ReservationCreate{Name: ptrString("test"), StartTime: time.Now()}
		err := adapter.ValidateReservationCreate(input)
		require.NoError(t, err)
	})
}

func TestReservationAdapter_ValidateUpdate(t *testing.T) {
	adapter := NewReservationAdapter(&api.ClientWithResponses{})

	t.Run("nil input returns error", func(t *testing.T) {
		err := adapter.validateReservationUpdate(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "reservation update data is required")
	})

	t.Run("empty fields returns error", func(t *testing.T) {
		input := &types.ReservationUpdate{}
		err := adapter.validateReservationUpdate(input)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "at least one field must be provided for update")
	})

	t.Run("valid input passes", func(t *testing.T) {
		input := &types.ReservationUpdate{Comment: ptrString("test")}
		err := adapter.validateReservationUpdate(input)
		require.NoError(t, err)
	})
}
