// Code generated by generate_adapters.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0

package v0_0_42

import (
	"context"
	"fmt"

	types "github.com/jontk/slurm-client/api"
	adapterbase "github.com/jontk/slurm-client/internal/adapters/base"
	"github.com/jontk/slurm-client/internal/common"
	api "github.com/jontk/slurm-client/internal/openapi/v0_0_42"
	"github.com/jontk/slurm-client/pkg/errors"
)

// ReservationAdapter implements the Reservation adapter interface for v0_0_42
type ReservationAdapter struct {
	*adapterbase.BaseManager
	client *api.ClientWithResponses
}

// NewReservationAdapter creates a new Reservation adapter
func NewReservationAdapter(client *api.ClientWithResponses) *ReservationAdapter {
	return &ReservationAdapter{
		BaseManager: adapterbase.NewBaseManager("v0.0.42", "Reservation"),
		client:      client,
	}
}

// List retrieves a list of reservations with optional filtering
func (a *ReservationAdapter) List(ctx context.Context, opts *types.ReservationListOptions) (*types.ReservationList, error) {
	// Validate context
	if err := a.ValidateContext(ctx); err != nil {
		return nil, err
	}

	// Check client initialization
	if err := a.CheckClientInitialized(a.client); err != nil {
		return nil, err
	}

	// Prepare parameters
	params := &api.SlurmV0042GetReservationsParams{}

	// Call the API
	resp, err := a.client.SlurmV0042GetReservationsWithResponse(ctx, params)
	if err != nil {
		return nil, a.HandleAPIError(err)
	}

	// Handle response errors
	var apiErrors *api.V0042OpenapiErrors
	if resp.JSON200 != nil {
		apiErrors = resp.JSON200.Errors
	}
	responseAdapter := api.NewResponseAdapter(resp.StatusCode(), apiErrors)
	if err := common.HandleAPIResponse(responseAdapter, "v0.0.42"); err != nil {
		return nil, err
	}

	// Check for nil response
	if err := a.CheckNilResponse(resp.JSON200, "List Reservations"); err != nil {
		return nil, err
	}

	// Convert response to common types
	items := make([]types.Reservation, 0, len(resp.JSON200.Reservations))
	for _, apiItem := range resp.JSON200.Reservations {
		item := a.convertAPIReservationToCommon(apiItem)
		items = append(items, *item)
	}

	// Apply pagination
	listOpts := adapterbase.ListOptions{}
	if opts != nil {
		listOpts.Limit = opts.Limit
		listOpts.Offset = opts.Offset
	}

	start := listOpts.Offset
	if start < 0 {
		start = 0
	}
	if start >= len(items) {
		return &types.ReservationList{
			Reservations: []types.Reservation{},
			Total:        len(items),
		}, nil
	}

	end := len(items)
	if listOpts.Limit > 0 {
		end = start + listOpts.Limit
		if end > len(items) {
			end = len(items)
		}
	}

	return &types.ReservationList{
		Reservations: items[start:end],
		Total:        len(items),
	}, nil
}

// Get retrieves a specific reservation by reservationName
func (a *ReservationAdapter) Get(ctx context.Context, reservationName string) (*types.Reservation, error) {
	// Validate context
	if err := a.ValidateContext(ctx); err != nil {
		return nil, err
	}
	if err := a.ValidateResourceName(reservationName, "reservationName"); err != nil {
		return nil, err
	}
	if err := a.CheckClientInitialized(a.client); err != nil {
		return nil, err
	}

	// Prepare parameters
	params := &api.SlurmV0042GetReservationParams{}

	// Call the API
	resp, err := a.client.SlurmV0042GetReservationWithResponse(ctx, reservationName, params)
	if err != nil {
		return nil, a.HandleAPIError(err)
	}

	// Handle response errors
	var apiErrors *api.V0042OpenapiErrors
	if resp.JSON200 != nil {
		apiErrors = resp.JSON200.Errors
	}
	responseAdapter := api.NewResponseAdapter(resp.StatusCode(), apiErrors)
	if err := common.HandleAPIResponse(responseAdapter, "v0.0.42"); err != nil {
		return nil, err
	}

	// Check for nil response
	if err := a.CheckNilResponse(resp.JSON200, "Get Reservation"); err != nil {
		return nil, err
	}

	// Check if entity exists
	if len(resp.JSON200.Reservations) == 0 {
		return nil, errors.NewSlurmError(errors.ErrorCodeResourceNotFound,
			fmt.Sprintf("Reservation %s not found", reservationName))
	}

	// Convert and return
	return a.convertAPIReservationToCommon(resp.JSON200.Reservations[0]), nil
}

// Create creates a new reservation
func (a *ReservationAdapter) Create(ctx context.Context, input *types.ReservationCreate) (*types.ReservationCreateResponse, error) {
	return nil, errors.NewClientError(errors.ErrorCodeUnsupportedOperation, "Create is not supported for Reservation in v0.0.42", "operation not supported")
}

// Update updates an existing reservation
func (a *ReservationAdapter) Update(ctx context.Context, reservationName string, update *types.ReservationUpdate) error {
	return errors.NewClientError(errors.ErrorCodeUnsupportedOperation, "Update is not supported for Reservation in v0.0.42", "operation not supported")
}

// Delete removes a reservation by reservationName
func (a *ReservationAdapter) Delete(ctx context.Context, reservationName string) error {
	// Validate context
	if err := a.ValidateContext(ctx); err != nil {
		return err
	}
	if err := a.ValidateResourceName(reservationName, "reservationName"); err != nil {
		return err
	}
	if err := a.CheckClientInitialized(a.client); err != nil {
		return err
	}

	// Call the API
	resp, err := a.client.SlurmV0042DeleteReservationWithResponse(ctx, reservationName)
	if err != nil {
		return a.HandleAPIError(err)
	}

	// Handle response errors
	var apiErrors *api.V0042OpenapiErrors
	if resp.JSON200 != nil {
		apiErrors = resp.JSON200.Errors
	}
	responseAdapter := api.NewResponseAdapter(resp.StatusCode(), apiErrors)

	// For DELETE operations, 204 is also a success
	if resp.StatusCode() == 204 {
		return nil
	}

	return common.HandleAPIResponse(responseAdapter, "v0.0.42")
}
