// Code generated by generate_adapters.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0
package v0_0_42

import (
	types "github.com/jontk/slurm-client/api"
	"github.com/jontk/slurm-client/pkg/errors"
)

// ValidateWCKeyCreate validates wckey create data
func (a *WCKeyAdapter) ValidateWCKeyCreate(create *types.WCKeyCreate) error {
	if create == nil {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "wckey creation data is required", "create", nil, nil)
	}
	if create.Name == "" {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "wckey name is required", "name", nil, nil)
	}
	if create.User == "" {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "wckey user is required", "user", nil, nil)
	}
	return nil
}
