// Code generated by generate_adapters.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0

package v0_0_42

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	types "github.com/jontk/slurm-client/api"
	api "github.com/jontk/slurm-client/internal/openapi/v0_0_42"
)

func TestNewWCKeyAdapter(t *testing.T) {
	client := &api.ClientWithResponses{}
	adapter := NewWCKeyAdapter(client)
	require.NotNil(t, adapter)
}

func TestWCKeyAdapter_ValidateContext(t *testing.T) {
	adapter := NewWCKeyAdapter(&api.ClientWithResponses{})

	// Test nil context
	//lint:ignore SA1012 intentionally testing nil context validation
	err := adapter.ValidateContext(nil)
	assert.Error(t, err)

	// Test valid context
	err = adapter.ValidateContext(context.Background())
	assert.NoError(t, err)
}

func TestWCKeyAdapter_List_NilContext(t *testing.T) {
	adapter := NewWCKeyAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.List(nil, nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestWCKeyAdapter_List_ClientNotInitialized(t *testing.T) {
	adapter := NewWCKeyAdapter(nil)

	result, err := adapter.List(context.Background(), nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestWCKeyAdapter_Get_NilContext(t *testing.T) {
	adapter := NewWCKeyAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.Get(nil, "test-wckey")
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestWCKeyAdapter_Get_EmptyIdentifier(t *testing.T) {
	adapter := NewWCKeyAdapter(&api.ClientWithResponses{})

	result, err := adapter.Get(context.Background(), "")
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestWCKeyAdapter_Get_ClientNotInitialized(t *testing.T) {
	adapter := NewWCKeyAdapter(nil)

	result, err := adapter.Get(context.Background(), "test-wckey")
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestWCKeyAdapter_Create_NilContext(t *testing.T) {
	adapter := NewWCKeyAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.Create(nil, &types.WCKeyCreate{})
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestWCKeyAdapter_Create_NilInput(t *testing.T) {
	adapter := NewWCKeyAdapter(&api.ClientWithResponses{})

	result, err := adapter.Create(context.Background(), nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestWCKeyAdapter_Create_ClientNotInitialized(t *testing.T) {
	adapter := NewWCKeyAdapter(nil)

	result, err := adapter.Create(context.Background(), &types.WCKeyCreate{})
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestWCKeyAdapter_Delete_NilContext(t *testing.T) {
	adapter := NewWCKeyAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	err := adapter.Delete(nil, "test-wckey")
	assert.Error(t, err)
}

func TestWCKeyAdapter_Delete_EmptyIdentifier(t *testing.T) {
	adapter := NewWCKeyAdapter(&api.ClientWithResponses{})

	err := adapter.Delete(context.Background(), "")
	assert.Error(t, err)
}

func TestWCKeyAdapter_Delete_ClientNotInitialized(t *testing.T) {
	adapter := NewWCKeyAdapter(nil)

	err := adapter.Delete(context.Background(), "test-wckey")
	assert.Error(t, err)
}

func TestWCKeyAdapter_ReadConverter(t *testing.T) {
	adapter := NewWCKeyAdapter(&api.ClientWithResponses{})

	// Create test API object
	apiObj := api.V0042Wckey{}

	// Convert API → Common
	commonObj := adapter.convertAPIWCKeyToCommon(apiObj)
	require.NotNil(t, commonObj)

	// Verify field values were correctly converted
}

func TestWCKeyAdapter_CreateConverter(t *testing.T) {
	adapter := NewWCKeyAdapter(&api.ClientWithResponses{})

	// Create test input with known values
	input := &types.WCKeyCreate{}

	// Convert Common → API
	apiObj := adapter.convertCommonWCKeyCreateToAPI(input)
	require.NotNil(t, apiObj)
}

func TestWCKeyAdapter_ValidateCreate(t *testing.T) {
	adapter := NewWCKeyAdapter(&api.ClientWithResponses{})

	t.Run("nil input returns error", func(t *testing.T) {
		err := adapter.ValidateWCKeyCreate(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "wckey creation data is required")
	})

	t.Run("missing Name returns error", func(t *testing.T) {
		input := &types.WCKeyCreate{User: "test"}
		err := adapter.ValidateWCKeyCreate(input)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "wckey name is required")
	})

	t.Run("missing User returns error", func(t *testing.T) {
		input := &types.WCKeyCreate{Name: "test"}
		err := adapter.ValidateWCKeyCreate(input)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "wckey user is required")
	})

	t.Run("valid input passes", func(t *testing.T) {
		input := &types.WCKeyCreate{Name: "test", User: "test"}
		err := adapter.ValidateWCKeyCreate(input)
		require.NoError(t, err)
	})
}
