// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v0_0_42

import (
	api "github.com/jontk/slurm-client/api"
	v0042 "github.com/jontk/slurm-client/internal/openapi/v0_0_42"
)

type AccountWriteConverterGoverterImpl struct{}

func (c *AccountWriteConverterGoverterImpl) ConvertCommonAccountCreateToAPI(source *api.AccountCreate) *v0042.V0042Account {
	var pV0_0_42V0042Account *v0042.V0042Account
	if source != nil {
		var v0_0_42V0042Account v0042.V0042Account
		v0_0_42V0042Account.Coordinators = ConvertCoordNamesToSlice((*source).Coordinators)
		v0_0_42V0042Account.Description = (*source).Description
		v0_0_42V0042Account.Name = (*source).Name
		v0_0_42V0042Account.Organization = (*source).Organization
		pV0_0_42V0042Account = &v0_0_42V0042Account
	}
	return pV0_0_42V0042Account
}
func (c *AccountWriteConverterGoverterImpl) ConvertCommonAccountUpdateToAPI(source *api.AccountUpdate) *v0042.V0042Account {
	var pV0_0_42V0042Account *v0042.V0042Account
	if source != nil {
		var v0_0_42V0042Account v0042.V0042Account
		v0_0_42V0042Account.Coordinators = ConvertCoordNamesToSlice((*source).Coordinators)
		v0_0_42V0042Account.Description = ConvertStringPtrToString((*source).Description)
		v0_0_42V0042Account.Organization = ConvertStringPtrToString((*source).Organization)
		pV0_0_42V0042Account = &v0_0_42V0042Account
	}
	return pV0_0_42V0042Account
}

type AssociationWriteConverterGoverterImpl struct{}

func (c *AssociationWriteConverterGoverterImpl) ConvertCommonAssociationCreateToAPI(source *api.AssociationCreate) *v0042.V0042Assoc {
	var pV0_0_42V0042Assoc *v0042.V0042Assoc
	if source != nil {
		var v0_0_42V0042Assoc v0042.V0042Assoc
		pString := (*source).Account
		v0_0_42V0042Assoc.Account = &pString
		pString2 := (*source).Cluster
		v0_0_42V0042Assoc.Cluster = &pString2
		pString3 := (*source).Comment
		v0_0_42V0042Assoc.Comment = &pString3
		pBool := (*source).IsDefault
		v0_0_42V0042Assoc.IsDefault = &pBool
		pString4 := (*source).ParentAccount
		v0_0_42V0042Assoc.ParentAccount = &pString4
		pString5 := (*source).Partition
		v0_0_42V0042Assoc.Partition = &pString5
		v0_0_42V0042Assoc.Priority = ConvertInt32ToUint32NoValStruct((*source).Priority)
		pInt32 := (*source).SharesRaw
		v0_0_42V0042Assoc.SharesRaw = &pInt32
		v0_0_42V0042Assoc.User = (*source).User
		pV0_0_42V0042Assoc = &v0_0_42V0042Assoc
	}
	return pV0_0_42V0042Assoc
}
func (c *AssociationWriteConverterGoverterImpl) ConvertCommonAssociationUpdateToAPI(source *api.AssociationUpdate) *v0042.V0042Assoc {
	var pV0_0_42V0042Assoc *v0042.V0042Assoc
	if source != nil {
		var v0_0_42V0042Assoc v0042.V0042Assoc
		if (*source).Comment != nil {
			xstring := *(*source).Comment
			v0_0_42V0042Assoc.Comment = &xstring
		}
		if (*source).IsDefault != nil {
			xbool := *(*source).IsDefault
			v0_0_42V0042Assoc.IsDefault = &xbool
		}
		v0_0_42V0042Assoc.Priority = ConvertInt32PtrToUint32NoValStruct((*source).Priority)
		if (*source).SharesRaw != nil {
			xint32 := *(*source).SharesRaw
			v0_0_42V0042Assoc.SharesRaw = &xint32
		}
		pV0_0_42V0042Assoc = &v0_0_42V0042Assoc
	}
	return pV0_0_42V0042Assoc
}

type ClusterWriteConverterGoverterImpl struct{}

func (c *ClusterWriteConverterGoverterImpl) ConvertCommonClusterCreateToAPI(source *api.ClusterCreate) *v0042.V0042ClusterRec {
	var pV0_0_42V0042ClusterRec *v0042.V0042ClusterRec
	if source != nil {
		var v0_0_42V0042ClusterRec v0042.V0042ClusterRec
		v0_0_42V0042ClusterRec.Flags = ConvertStringSliceToClusterRecFlags((*source).Flags)
		pString := (*source).Name
		v0_0_42V0042ClusterRec.Name = &pString
		pString2 := (*source).Nodes
		v0_0_42V0042ClusterRec.Nodes = &pString2
		pInt32 := (*source).RpcVersion
		v0_0_42V0042ClusterRec.RpcVersion = &pInt32
		pString3 := (*source).SelectPlugin
		v0_0_42V0042ClusterRec.SelectPlugin = &pString3
		pV0_0_42V0042ClusterRec = &v0_0_42V0042ClusterRec
	}
	return pV0_0_42V0042ClusterRec
}
func (c *ClusterWriteConverterGoverterImpl) ConvertCommonClusterUpdateToAPI(source *api.ClusterUpdate) *v0042.V0042ClusterRec {
	var pV0_0_42V0042ClusterRec *v0042.V0042ClusterRec
	if source != nil {
		var v0_0_42V0042ClusterRec v0042.V0042ClusterRec
		if (*source).RPCVersion != nil {
			xint32 := *(*source).RPCVersion
			v0_0_42V0042ClusterRec.RpcVersion = &xint32
		}
		pV0_0_42V0042ClusterRec = &v0_0_42V0042ClusterRec
	}
	return pV0_0_42V0042ClusterRec
}

type JobWriteConverterGoverterImpl struct{}

func (c *JobWriteConverterGoverterImpl) ConvertCommonJobCreateToAPI(source *api.JobCreate) *v0042.V0042JobDescMsg {
	var pV0_0_42V0042JobDescMsg *v0042.V0042JobDescMsg
	if source != nil {
		var v0_0_42V0042JobDescMsg v0042.V0042JobDescMsg
		if (*source).Account != nil {
			xstring := *(*source).Account
			v0_0_42V0042JobDescMsg.Account = &xstring
		}
		if (*source).AccountGatherFrequency != nil {
			xstring2 := *(*source).AccountGatherFrequency
			v0_0_42V0042JobDescMsg.AccountGatherFrequency = &xstring2
		}
		if (*source).AdminComment != nil {
			xstring3 := *(*source).AdminComment
			v0_0_42V0042JobDescMsg.AdminComment = &xstring3
		}
		if (*source).AllocationNodeList != nil {
			xstring4 := *(*source).AllocationNodeList
			v0_0_42V0042JobDescMsg.AllocationNodeList = &xstring4
		}
		if (*source).AllocationNodePort != nil {
			xint32 := *(*source).AllocationNodePort
			v0_0_42V0042JobDescMsg.AllocationNodePort = &xint32
		}
		v0_0_42V0042JobDescMsg.Argv = ConvertStringSliceToStringArray((*source).Argv)
		if (*source).Array != nil {
			xstring5 := *(*source).Array
			v0_0_42V0042JobDescMsg.Array = &xstring5
		}
		if (*source).BatchFeatures != nil {
			xstring6 := *(*source).BatchFeatures
			v0_0_42V0042JobDescMsg.BatchFeatures = &xstring6
		}
		v0_0_42V0042JobDescMsg.BeginTime = ConvertUint64PtrToNoValStruct((*source).BeginTime)
		if (*source).BurstBuffer != nil {
			xstring7 := *(*source).BurstBuffer
			v0_0_42V0042JobDescMsg.BurstBuffer = &xstring7
		}
		if (*source).ClusterConstraint != nil {
			xstring8 := *(*source).ClusterConstraint
			v0_0_42V0042JobDescMsg.ClusterConstraint = &xstring8
		}
		if (*source).Clusters != nil {
			xstring9 := *(*source).Clusters
			v0_0_42V0042JobDescMsg.Clusters = &xstring9
		}
		if (*source).Comment != nil {
			xstring10 := *(*source).Comment
			v0_0_42V0042JobDescMsg.Comment = &xstring10
		}
		if (*source).Constraints != nil {
			xstring11 := *(*source).Constraints
			v0_0_42V0042JobDescMsg.Constraints = &xstring11
		}
		if (*source).Container != nil {
			xstring12 := *(*source).Container
			v0_0_42V0042JobDescMsg.Container = &xstring12
		}
		if (*source).ContainerID != nil {
			xstring13 := *(*source).ContainerID
			v0_0_42V0042JobDescMsg.ContainerId = &xstring13
		}
		if (*source).Contiguous != nil {
			xbool := *(*source).Contiguous
			v0_0_42V0042JobDescMsg.Contiguous = &xbool
		}
		if (*source).CoreSpecification != nil {
			xint322 := *(*source).CoreSpecification
			v0_0_42V0042JobDescMsg.CoreSpecification = &xint322
		}
		if (*source).CPUBinding != nil {
			xstring14 := *(*source).CPUBinding
			v0_0_42V0042JobDescMsg.CpuBinding = &xstring14
		}
		v0_0_42V0042JobDescMsg.CpuBindingFlags = ConvertCPUBindingFlagsSliceToAPIV42((*source).CPUBindingFlags)
		if (*source).CPUFrequency != nil {
			xstring15 := *(*source).CPUFrequency
			v0_0_42V0042JobDescMsg.CpuFrequency = &xstring15
		}
		if (*source).CPUsPerTask != nil {
			xint323 := *(*source).CPUsPerTask
			v0_0_42V0042JobDescMsg.CpusPerTask = &xint323
		}
		if (*source).CPUsPerTRES != nil {
			xstring16 := *(*source).CPUsPerTRES
			v0_0_42V0042JobDescMsg.CpusPerTres = &xstring16
		}
		v0_0_42V0042JobDescMsg.Crontab = ConvertCronEntryToAPIV42((*source).Crontab)
		if (*source).CurrentWorkingDirectory != nil {
			xstring17 := *(*source).CurrentWorkingDirectory
			v0_0_42V0042JobDescMsg.CurrentWorkingDirectory = &xstring17
		}
		if (*source).Deadline != nil {
			xint64 := *(*source).Deadline
			v0_0_42V0042JobDescMsg.Deadline = &xint64
		}
		if (*source).DelayBoot != nil {
			xint324 := *(*source).DelayBoot
			v0_0_42V0042JobDescMsg.DelayBoot = &xint324
		}
		if (*source).Dependency != nil {
			xstring18 := *(*source).Dependency
			v0_0_42V0042JobDescMsg.Dependency = &xstring18
		}
		if (*source).Distribution != nil {
			xstring19 := *(*source).Distribution
			v0_0_42V0042JobDescMsg.Distribution = &xstring19
		}
		v0_0_42V0042JobDescMsg.DistributionPlaneSize = ConvertUint16PtrToNoValStruct((*source).DistributionPlaneSize)
		if (*source).EndTime != nil {
			xint642 := *(*source).EndTime
			v0_0_42V0042JobDescMsg.EndTime = &xint642
		}
		v0_0_42V0042JobDescMsg.Environment = ConvertStringSliceToStringArray((*source).Environment)
		v0_0_42V0042JobDescMsg.ExcludedNodes = ConvertStringSliceToCsvString((*source).ExcludedNodes)
		if (*source).Extra != nil {
			xstring20 := *(*source).Extra
			v0_0_42V0042JobDescMsg.Extra = &xstring20
		}
		v0_0_42V0042JobDescMsg.Flags = ConvertFlagsSliceToAPIV42((*source).Flags)
		if (*source).GroupID != nil {
			xstring21 := *(*source).GroupID
			v0_0_42V0042JobDescMsg.GroupId = &xstring21
		}
		if (*source).HetjobGroup != nil {
			xint325 := *(*source).HetjobGroup
			v0_0_42V0042JobDescMsg.HetjobGroup = &xint325
		}
		if (*source).Hold != nil {
			xbool2 := *(*source).Hold
			v0_0_42V0042JobDescMsg.Hold = &xbool2
		}
		if (*source).Immediate != nil {
			xbool3 := *(*source).Immediate
			v0_0_42V0042JobDescMsg.Immediate = &xbool3
		}
		if (*source).JobID != nil {
			xint326 := *(*source).JobID
			v0_0_42V0042JobDescMsg.JobId = &xint326
		}
		if (*source).KillOnNodeFail != nil {
			xbool4 := *(*source).KillOnNodeFail
			v0_0_42V0042JobDescMsg.KillOnNodeFail = &xbool4
		}
		v0_0_42V0042JobDescMsg.KillWarningDelay = ConvertUint16PtrToNoValStruct((*source).KillWarningDelay)
		v0_0_42V0042JobDescMsg.KillWarningFlags = ConvertKillWarningFlagsSliceToAPIV42((*source).KillWarningFlags)
		if (*source).KillWarningSignal != nil {
			xstring22 := *(*source).KillWarningSignal
			v0_0_42V0042JobDescMsg.KillWarningSignal = &xstring22
		}
		if (*source).Licenses != nil {
			xstring23 := *(*source).Licenses
			v0_0_42V0042JobDescMsg.Licenses = &xstring23
		}
		v0_0_42V0042JobDescMsg.MailType = ConvertMailTypeSliceToAPIV42((*source).MailType)
		if (*source).MailUser != nil {
			xstring24 := *(*source).MailUser
			v0_0_42V0042JobDescMsg.MailUser = &xstring24
		}
		if (*source).MaximumCPUs != nil {
			xint327 := *(*source).MaximumCPUs
			v0_0_42V0042JobDescMsg.MaximumCpus = &xint327
		}
		if (*source).MaximumNodes != nil {
			xint328 := *(*source).MaximumNodes
			v0_0_42V0042JobDescMsg.MaximumNodes = &xint328
		}
		if (*source).MCSLabel != nil {
			xstring25 := *(*source).MCSLabel
			v0_0_42V0042JobDescMsg.McsLabel = &xstring25
		}
		if (*source).MemoryBinding != nil {
			xstring26 := *(*source).MemoryBinding
			v0_0_42V0042JobDescMsg.MemoryBinding = &xstring26
		}
		v0_0_42V0042JobDescMsg.MemoryBindingType = ConvertMemoryBindingTypeSliceToAPIV42((*source).MemoryBindingType)
		v0_0_42V0042JobDescMsg.MemoryPerCpu = ConvertUint64PtrToNoValStruct((*source).MemoryPerCPU)
		v0_0_42V0042JobDescMsg.MemoryPerNode = ConvertUint64PtrToNoValStruct((*source).MemoryPerNode)
		if (*source).MemoryPerTRES != nil {
			xstring27 := *(*source).MemoryPerTRES
			v0_0_42V0042JobDescMsg.MemoryPerTres = &xstring27
		}
		if (*source).MinimumBoardsPerNode != nil {
			xint329 := *(*source).MinimumBoardsPerNode
			v0_0_42V0042JobDescMsg.MinimumBoardsPerNode = &xint329
		}
		if (*source).MinimumCPUs != nil {
			xint3210 := *(*source).MinimumCPUs
			v0_0_42V0042JobDescMsg.MinimumCpus = &xint3210
		}
		if (*source).MinimumCPUsPerNode != nil {
			xint3211 := *(*source).MinimumCPUsPerNode
			v0_0_42V0042JobDescMsg.MinimumCpusPerNode = &xint3211
		}
		if (*source).MinimumNodes != nil {
			xint3212 := *(*source).MinimumNodes
			v0_0_42V0042JobDescMsg.MinimumNodes = &xint3212
		}
		if (*source).MinimumSocketsPerBoard != nil {
			xint3213 := *(*source).MinimumSocketsPerBoard
			v0_0_42V0042JobDescMsg.MinimumSocketsPerBoard = &xint3213
		}
		if (*source).Name != nil {
			xstring28 := *(*source).Name
			v0_0_42V0042JobDescMsg.Name = &xstring28
		}
		if (*source).Network != nil {
			xstring29 := *(*source).Network
			v0_0_42V0042JobDescMsg.Network = &xstring29
		}
		if (*source).Nice != nil {
			xint3214 := *(*source).Nice
			v0_0_42V0042JobDescMsg.Nice = &xint3214
		}
		if (*source).Nodes != nil {
			xstring30 := *(*source).Nodes
			v0_0_42V0042JobDescMsg.Nodes = &xstring30
		}
		if (*source).NtasksPerTRES != nil {
			xint3215 := *(*source).NtasksPerTRES
			v0_0_42V0042JobDescMsg.NtasksPerTres = &xint3215
		}
		if (*source).OomKillStep != nil {
			xint3216 := *(*source).OomKillStep
			v0_0_42V0042JobDescMsg.OomKillStep = &xint3216
		}
		v0_0_42V0042JobDescMsg.OpenMode = ConvertOpenModeSliceToAPIV42((*source).OpenMode)
		if (*source).Overcommit != nil {
			xbool5 := *(*source).Overcommit
			v0_0_42V0042JobDescMsg.Overcommit = &xbool5
		}
		if (*source).Partition != nil {
			xstring31 := *(*source).Partition
			v0_0_42V0042JobDescMsg.Partition = &xstring31
		}
		if (*source).Prefer != nil {
			xstring32 := *(*source).Prefer
			v0_0_42V0042JobDescMsg.Prefer = &xstring32
		}
		v0_0_42V0042JobDescMsg.Priority = ConvertUint32PtrToNoValStruct((*source).Priority)
		v0_0_42V0042JobDescMsg.Profile = ConvertProfileSliceToAPIV42((*source).Profile)
		if (*source).QoS != nil {
			xstring33 := *(*source).QoS
			v0_0_42V0042JobDescMsg.Qos = &xstring33
		}
		if (*source).Reboot != nil {
			xbool6 := *(*source).Reboot
			v0_0_42V0042JobDescMsg.Reboot = &xbool6
		}
		if (*source).Requeue != nil {
			xbool7 := *(*source).Requeue
			v0_0_42V0042JobDescMsg.Requeue = &xbool7
		}
		v0_0_42V0042JobDescMsg.RequiredNodes = ConvertStringSliceToCsvString((*source).RequiredNodes)
		v0_0_42V0042JobDescMsg.RequiredSwitches = ConvertUint32PtrToNoValStruct((*source).RequiredSwitches)
		if (*source).Reservation != nil {
			xstring34 := *(*source).Reservation
			v0_0_42V0042JobDescMsg.Reservation = &xstring34
		}
		if (*source).ReservePorts != nil {
			xint3217 := *(*source).ReservePorts
			v0_0_42V0042JobDescMsg.ReservePorts = &xint3217
		}
		if (*source).Script != nil {
			xstring35 := *(*source).Script
			v0_0_42V0042JobDescMsg.Script = &xstring35
		}
		v0_0_42V0042JobDescMsg.SegmentSize = ConvertUint16PtrToNoValStruct((*source).SegmentSize)
		if (*source).SelinuxContext != nil {
			xstring36 := *(*source).SelinuxContext
			v0_0_42V0042JobDescMsg.SelinuxContext = &xstring36
		}
		v0_0_42V0042JobDescMsg.Shared = ConvertSharedSliceToAPIV42((*source).Shared)
		if (*source).SiteFactor != nil {
			xint3218 := *(*source).SiteFactor
			v0_0_42V0042JobDescMsg.SiteFactor = &xint3218
		}
		if (*source).SocketsPerNode != nil {
			xint3219 := *(*source).SocketsPerNode
			v0_0_42V0042JobDescMsg.SocketsPerNode = &xint3219
		}
		v0_0_42V0042JobDescMsg.SpankEnvironment = ConvertStringSliceToStringArray((*source).SpankEnvironment)
		if (*source).StandardError != nil {
			xstring37 := *(*source).StandardError
			v0_0_42V0042JobDescMsg.StandardError = &xstring37
		}
		if (*source).StandardInput != nil {
			xstring38 := *(*source).StandardInput
			v0_0_42V0042JobDescMsg.StandardInput = &xstring38
		}
		if (*source).StandardOutput != nil {
			xstring39 := *(*source).StandardOutput
			v0_0_42V0042JobDescMsg.StandardOutput = &xstring39
		}
		if (*source).Tasks != nil {
			xint3220 := *(*source).Tasks
			v0_0_42V0042JobDescMsg.Tasks = &xint3220
		}
		if (*source).TasksPerBoard != nil {
			xint3221 := *(*source).TasksPerBoard
			v0_0_42V0042JobDescMsg.TasksPerBoard = &xint3221
		}
		if (*source).TasksPerCore != nil {
			xint3222 := *(*source).TasksPerCore
			v0_0_42V0042JobDescMsg.TasksPerCore = &xint3222
		}
		if (*source).TasksPerNode != nil {
			xint3223 := *(*source).TasksPerNode
			v0_0_42V0042JobDescMsg.TasksPerNode = &xint3223
		}
		if (*source).TasksPerSocket != nil {
			xint3224 := *(*source).TasksPerSocket
			v0_0_42V0042JobDescMsg.TasksPerSocket = &xint3224
		}
		if (*source).TemporaryDiskPerNode != nil {
			xint3225 := *(*source).TemporaryDiskPerNode
			v0_0_42V0042JobDescMsg.TemporaryDiskPerNode = &xint3225
		}
		if (*source).ThreadSpecification != nil {
			xint3226 := *(*source).ThreadSpecification
			v0_0_42V0042JobDescMsg.ThreadSpecification = &xint3226
		}
		if (*source).ThreadsPerCore != nil {
			xint3227 := *(*source).ThreadsPerCore
			v0_0_42V0042JobDescMsg.ThreadsPerCore = &xint3227
		}
		v0_0_42V0042JobDescMsg.TimeLimit = ConvertUint32PtrToNoValStruct((*source).TimeLimit)
		v0_0_42V0042JobDescMsg.TimeMinimum = ConvertUint32PtrToNoValStruct((*source).TimeMinimum)
		if (*source).TRESBind != nil {
			xstring40 := *(*source).TRESBind
			v0_0_42V0042JobDescMsg.TresBind = &xstring40
		}
		if (*source).TRESFreq != nil {
			xstring41 := *(*source).TRESFreq
			v0_0_42V0042JobDescMsg.TresFreq = &xstring41
		}
		if (*source).TRESPerJob != nil {
			xstring42 := *(*source).TRESPerJob
			v0_0_42V0042JobDescMsg.TresPerJob = &xstring42
		}
		if (*source).TRESPerNode != nil {
			xstring43 := *(*source).TRESPerNode
			v0_0_42V0042JobDescMsg.TresPerNode = &xstring43
		}
		if (*source).TRESPerSocket != nil {
			xstring44 := *(*source).TRESPerSocket
			v0_0_42V0042JobDescMsg.TresPerSocket = &xstring44
		}
		if (*source).TRESPerTask != nil {
			xstring45 := *(*source).TRESPerTask
			v0_0_42V0042JobDescMsg.TresPerTask = &xstring45
		}
		if (*source).UserID != nil {
			xstring46 := *(*source).UserID
			v0_0_42V0042JobDescMsg.UserId = &xstring46
		}
		if (*source).WaitAllNodes != nil {
			xbool8 := *(*source).WaitAllNodes
			v0_0_42V0042JobDescMsg.WaitAllNodes = &xbool8
		}
		if (*source).WaitForSwitch != nil {
			xint3228 := *(*source).WaitForSwitch
			v0_0_42V0042JobDescMsg.WaitForSwitch = &xint3228
		}
		if (*source).Wckey != nil {
			xstring47 := *(*source).Wckey
			v0_0_42V0042JobDescMsg.Wckey = &xstring47
		}
		v0_0_42V0042JobDescMsg.X11 = ConvertX11SliceToAPIV42((*source).X11)
		if (*source).X11MagicCookie != nil {
			xstring48 := *(*source).X11MagicCookie
			v0_0_42V0042JobDescMsg.X11MagicCookie = &xstring48
		}
		if (*source).X11TargetHost != nil {
			xstring49 := *(*source).X11TargetHost
			v0_0_42V0042JobDescMsg.X11TargetHost = &xstring49
		}
		if (*source).X11TargetPort != nil {
			xint3229 := *(*source).X11TargetPort
			v0_0_42V0042JobDescMsg.X11TargetPort = &xint3229
		}
		pV0_0_42V0042JobDescMsg = &v0_0_42V0042JobDescMsg
	}
	return pV0_0_42V0042JobDescMsg
}

type NodeWriteConverterGoverterImpl struct{}

func (c *NodeWriteConverterGoverterImpl) ConvertCommonNodeUpdateToAPI(source *api.NodeUpdate) *v0042.V0042UpdateNodeMsg {
	var pV0_0_42V0042UpdateNodeMsg *v0042.V0042UpdateNodeMsg
	if source != nil {
		var v0_0_42V0042UpdateNodeMsg v0042.V0042UpdateNodeMsg
		v0_0_42V0042UpdateNodeMsg.Address = ConvertStringSliceToHostlistString((*source).Address)
		if (*source).Comment != nil {
			xstring := *(*source).Comment
			v0_0_42V0042UpdateNodeMsg.Comment = &xstring
		}
		if (*source).CPUBind != nil {
			xint32 := *(*source).CPUBind
			v0_0_42V0042UpdateNodeMsg.CpuBind = &xint32
		}
		if (*source).Extra != nil {
			xstring2 := *(*source).Extra
			v0_0_42V0042UpdateNodeMsg.Extra = &xstring2
		}
		v0_0_42V0042UpdateNodeMsg.Features = ConvertStringSliceToCsvString((*source).Features)
		v0_0_42V0042UpdateNodeMsg.FeaturesAct = ConvertStringSliceToCsvString((*source).FeaturesAct)
		if (*source).GRES != nil {
			xstring3 := *(*source).GRES
			v0_0_42V0042UpdateNodeMsg.Gres = &xstring3
		}
		v0_0_42V0042UpdateNodeMsg.Hostname = ConvertStringSliceToHostlistString((*source).Hostname)
		v0_0_42V0042UpdateNodeMsg.Name = ConvertStringSliceToHostlistString((*source).Name)
		if (*source).Reason != nil {
			xstring4 := *(*source).Reason
			v0_0_42V0042UpdateNodeMsg.Reason = &xstring4
		}
		if (*source).ReasonUID != nil {
			xstring5 := *(*source).ReasonUID
			v0_0_42V0042UpdateNodeMsg.ReasonUid = &xstring5
		}
		v0_0_42V0042UpdateNodeMsg.ResumeAfter = ConvertUint32PtrToNoValStruct((*source).ResumeAfter)
		v0_0_42V0042UpdateNodeMsg.State = ConvertNodeStatesToAPIV42((*source).State)
		v0_0_42V0042UpdateNodeMsg.Weight = ConvertUint32PtrToNoValStruct((*source).Weight)
		pV0_0_42V0042UpdateNodeMsg = &v0_0_42V0042UpdateNodeMsg
	}
	return pV0_0_42V0042UpdateNodeMsg
}

type QoSWriteConverterGoverterImpl struct{}

func (c *QoSWriteConverterGoverterImpl) ConvertCommonQoSCreateToAPI(source *api.QoSCreate) *v0042.V0042Qos {
	var pV0_0_42V0042Qos *v0042.V0042Qos
	if source != nil {
		var v0_0_42V0042Qos v0042.V0042Qos
		pString := (*source).Description
		v0_0_42V0042Qos.Description = &pString
		v0_0_42V0042Qos.Flags = ConvertStringSliceToQosFlags((*source).Flags)
		pString2 := (*source).Name
		v0_0_42V0042Qos.Name = &pString2
		v0_0_42V0042Qos.Priority = ConvertIntToUint32NoValStruct((*source).Priority)
		v0_0_42V0042Qos.UsageFactor = ConvertFloat64ToFloat64NoValStruct((*source).UsageFactor)
		v0_0_42V0042Qos.UsageThreshold = ConvertFloat64ToFloat64NoValStruct((*source).UsageThreshold)
		pV0_0_42V0042Qos = &v0_0_42V0042Qos
	}
	return pV0_0_42V0042Qos
}
func (c *QoSWriteConverterGoverterImpl) ConvertCommonQoSUpdateToAPI(source *api.QoSUpdate) *v0042.V0042Qos {
	var pV0_0_42V0042Qos *v0042.V0042Qos
	if source != nil {
		var v0_0_42V0042Qos v0042.V0042Qos
		if (*source).Description != nil {
			xstring := *(*source).Description
			v0_0_42V0042Qos.Description = &xstring
		}
		v0_0_42V0042Qos.Flags = ConvertStringSlicePtrToQosFlags((*source).Flags)
		v0_0_42V0042Qos.Priority = ConvertIntPtrToUint32NoValStruct((*source).Priority)
		v0_0_42V0042Qos.UsageFactor = ConvertFloat64PtrToFloat64NoValStruct((*source).UsageFactor)
		v0_0_42V0042Qos.UsageThreshold = ConvertFloat64PtrToFloat64NoValStruct((*source).UsageThreshold)
		pV0_0_42V0042Qos = &v0_0_42V0042Qos
	}
	return pV0_0_42V0042Qos
}

type UserWriteConverterGoverterImpl struct{}

func (c *UserWriteConverterGoverterImpl) ConvertCommonUserCreateToAPI(source *api.UserCreate) *v0042.V0042User {
	var pV0_0_42V0042User *v0042.V0042User
	if source != nil {
		var v0_0_42V0042User v0042.V0042User
		v0_0_42V0042User.Default = ConvertUserCreateDefaultToAPI(source)
		v0_0_42V0042User.Name = (*source).Name
		pV0_0_42V0042User = &v0_0_42V0042User
	}
	return pV0_0_42V0042User
}
func (c *UserWriteConverterGoverterImpl) ConvertCommonUserUpdateToAPI(source *api.UserUpdate) *v0042.V0042User {
	var pV0_0_42V0042User *v0042.V0042User
	if source != nil {
		var v0_0_42V0042User v0042.V0042User
		v0_0_42V0042User.Default = ConvertUserUpdateDefaultToAPI(source)
		pV0_0_42V0042User = &v0_0_42V0042User
	}
	return pV0_0_42V0042User
}

type WCKeyWriteConverterGoverterImpl struct{}

func (c *WCKeyWriteConverterGoverterImpl) ConvertCommonWCKeyCreateToAPI(source *api.WCKeyCreate) *v0042.V0042Wckey {
	var pV0_0_42V0042Wckey *v0042.V0042Wckey
	if source != nil {
		var v0_0_42V0042Wckey v0042.V0042Wckey
		v0_0_42V0042Wckey.Cluster = (*source).Cluster
		v0_0_42V0042Wckey.Name = (*source).Name
		v0_0_42V0042Wckey.User = (*source).User
		pV0_0_42V0042Wckey = &v0_0_42V0042Wckey
	}
	return pV0_0_42V0042Wckey
}
