// Code generated by tools/codegen/generate.go; DO NOT EDIT.

package v0_0_40

import (
	"net/http"
	
	"github.com/jontk/slurm-client/internal/interfaces"
)

// WrapperClient implements the SlurmClient interface for API version v0.0.40
type WrapperClient struct {
	apiClient *ClientWithResponses
	config    *interfaces.ClientConfig
}

// NewWrapperClient creates a new v0.0.40 client
func NewWrapperClient(config *interfaces.ClientConfig) (*WrapperClient, error) {
	// Create HTTP client with authentication
	httpClient := config.HTTPClient
	if httpClient == nil {
		httpClient = &http.Client{}
	}
	
	// Create oapi-codegen client
	apiClient, err := NewClientWithResponses(config.BaseURL, WithHTTPClient(httpClient))
	if err != nil {
		return nil, err
	}
	
	return &WrapperClient{
		apiClient: apiClient,
		config:    config,
	}, nil
}

// Version returns the API version
func (c *WrapperClient) Version() string {
	return "v0.0.40"
}

// Jobs returns the JobManager
func (c *WrapperClient) Jobs() interfaces.JobManager {
	return &JobManager{client: c}
}

// Nodes returns the NodeManager  
func (c *WrapperClient) Nodes() interfaces.NodeManager {
	return &NodeManager{client: c}
}

// Partitions returns the PartitionManager
func (c *WrapperClient) Partitions() interfaces.PartitionManager {
	return &PartitionManager{client: c}
}

// Info returns the InfoManager
func (c *WrapperClient) Info() interfaces.InfoManager {
	return &InfoManager{client: c}
}

// Reservations returns the ReservationManager
func (c *WrapperClient) Reservations() interfaces.ReservationManager {
	return nil
}

// QoS returns the QoSManager
func (c *WrapperClient) QoS() interfaces.QoSManager {
	return nil
}

// Accounts returns the AccountManager
func (c *WrapperClient) Accounts() interfaces.AccountManager {
	return nil
}

// Close closes the client
func (c *WrapperClient) Close() error {
	// No resources to close for HTTP client
	return nil
}
