// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v0_0_44

import (
	api "github.com/jontk/slurm-client/api"
	v0044 "github.com/jontk/slurm-client/internal/openapi/v0_0_44"
)

type AccountConverterGoverterImpl struct{}

func (c *AccountConverterGoverterImpl) ConvertAPIAccountToCommon(source v0044.V0044Account) *api.Account {
	var apiAccount api.Account
	apiAccount.Associations = ConvertAssocShortSlice(source.Associations)
	apiAccount.Coordinators = ConvertCoordSlice(source.Coordinators)
	apiAccount.Description = source.Description
	apiAccount.Flags = ConvertAccountFlags(source.Flags)
	apiAccount.Name = source.Name
	apiAccount.Organization = source.Organization
	return &apiAccount
}
func (c *AccountConverterGoverterImpl) ConvertCommonAccountCreateToAPI(source *api.AccountCreate) *v0044.V0044Account {
	var pV0_0_44V0044Account *v0044.V0044Account
	if source != nil {
		var v0_0_44V0044Account v0044.V0044Account
		v0_0_44V0044Account.Coordinators = ConvertCoordNamesToSlice((*source).Coordinators)
		v0_0_44V0044Account.Description = (*source).Description
		v0_0_44V0044Account.Name = (*source).Name
		v0_0_44V0044Account.Organization = (*source).Organization
		pV0_0_44V0044Account = &v0_0_44V0044Account
	}
	return pV0_0_44V0044Account
}
