// Code generated by generate_adapters.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0

package v0_0_44

import (
	types "github.com/jontk/slurm-client/api"
	"github.com/jontk/slurm-client/pkg/errors"
)

// ValidateAccountCreate validates account create data
func (a *AccountAdapter) ValidateAccountCreate(create *types.AccountCreate) error {
	if create == nil {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "account creation data is required", "create", nil, nil)
	}
	if create.Name == "" {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "account name is required", "name", nil, nil)
	}
	return nil
}

// validateAccountUpdate validates account update data
func (a *AccountAdapter) validateAccountUpdate(update *types.AccountUpdate) error {
	if update == nil {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "account update data is required", "update", nil, nil)
	}
	return nil
}
