// Code generated by generate_adapters.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0
package v0_0_44

import (
	"context"
	"fmt"

	types "github.com/jontk/slurm-client/api"
	adapterbase "github.com/jontk/slurm-client/internal/adapters/base"
	"github.com/jontk/slurm-client/internal/common"
	api "github.com/jontk/slurm-client/internal/openapi/v0_0_44"
	"github.com/jontk/slurm-client/pkg/errors"
)

// ClusterAdapter implements the Cluster adapter interface for v0_0_44
type ClusterAdapter struct {
	*adapterbase.BaseManager
	client *api.ClientWithResponses
}

// NewClusterAdapter creates a new Cluster adapter
func NewClusterAdapter(client *api.ClientWithResponses) *ClusterAdapter {
	return &ClusterAdapter{
		BaseManager: adapterbase.NewBaseManager("v0.0.44", "Cluster"),
		client:      client,
	}
}

// List retrieves a list of clusters with optional filtering
func (a *ClusterAdapter) List(ctx context.Context, opts *types.ClusterListOptions) (*types.ClusterList, error) {
	// Validate context
	if err := a.ValidateContext(ctx); err != nil {
		return nil, err
	}
	// Check client initialization
	if err := a.CheckClientInitialized(a.client); err != nil {
		return nil, err
	}
	// Prepare parameters
	params := &api.SlurmdbV0044GetClustersParams{}
	// Call the API
	resp, err := a.client.SlurmdbV0044GetClustersWithResponse(ctx, params)
	if err != nil {
		return nil, a.HandleAPIError(err)
	}
	// Handle response errors
	var apiErrors *api.V0044OpenapiErrors
	if resp.JSON200 != nil {
		apiErrors = resp.JSON200.Errors
	}
	responseAdapter := api.NewResponseAdapter(resp.StatusCode(), apiErrors)
	if err := common.HandleAPIResponse(responseAdapter, "v0.0.44"); err != nil {
		return nil, err
	}
	// Check for nil response
	if err := a.CheckNilResponse(resp.JSON200, "List Clusters"); err != nil {
		return nil, err
	}
	// Convert response to common types
	items := make([]types.Cluster, 0, len(resp.JSON200.Clusters))
	for _, apiItem := range resp.JSON200.Clusters {
		item := a.convertAPIClusterToCommon(apiItem)
		items = append(items, *item)
	}
	// Apply pagination
	listOpts := adapterbase.ListOptions{}
	if opts != nil {
		listOpts.Limit = opts.Limit
		listOpts.Offset = opts.Offset
	}
	start := listOpts.Offset
	if start < 0 {
		start = 0
	}
	if start >= len(items) {
		return &types.ClusterList{
			Clusters: []types.Cluster{},
			Total:    len(items),
		}, nil
	}
	end := len(items)
	if listOpts.Limit > 0 {
		end = start + listOpts.Limit
		if end > len(items) {
			end = len(items)
		}
	}
	return &types.ClusterList{
		Clusters: items[start:end],
		Total:    len(items),
	}, nil
}

// Get retrieves a specific cluster by clusterName
func (a *ClusterAdapter) Get(ctx context.Context, clusterName string) (*types.Cluster, error) {
	// Validate context
	if err := a.ValidateContext(ctx); err != nil {
		return nil, err
	}
	if err := a.ValidateResourceName(clusterName, "clusterName"); err != nil {
		return nil, err
	}
	if err := a.CheckClientInitialized(a.client); err != nil {
		return nil, err
	}
	// Prepare parameters
	params := &api.SlurmdbV0044GetClusterParams{}
	// Call the API
	resp, err := a.client.SlurmdbV0044GetClusterWithResponse(ctx, clusterName, params)
	if err != nil {
		return nil, a.HandleAPIError(err)
	}
	// Handle response errors
	var apiErrors *api.V0044OpenapiErrors
	if resp.JSON200 != nil {
		apiErrors = resp.JSON200.Errors
	}
	responseAdapter := api.NewResponseAdapter(resp.StatusCode(), apiErrors)
	if err := common.HandleAPIResponse(responseAdapter, "v0.0.44"); err != nil {
		return nil, err
	}
	// Check for nil response
	if err := a.CheckNilResponse(resp.JSON200, "Get Cluster"); err != nil {
		return nil, err
	}
	// Check if entity exists
	if len(resp.JSON200.Clusters) == 0 {
		return nil, errors.NewSlurmError(errors.ErrorCodeResourceNotFound,
			fmt.Sprintf("Cluster %s not found", clusterName))
	}
	// Convert and return
	return a.convertAPIClusterToCommon(resp.JSON200.Clusters[0]), nil
}

// Create creates a new cluster
func (a *ClusterAdapter) Create(ctx context.Context, input *types.ClusterCreate) (*types.ClusterCreateResponse, error) {
	// Validate context
	if err := a.ValidateContext(ctx); err != nil {
		return nil, err
	}
	if input == nil {
		return nil, errors.NewValidationError(errors.ErrorCodeValidationFailed, "input is required", "input", nil, nil)
	}
	if err := a.CheckClientInitialized(a.client); err != nil {
		return nil, err
	}
	// Convert to API type
	apiInput := a.convertCommonClusterCreateToAPI(input)
	// Create request body with the entity wrapped in a slice
	reqBody := api.SlurmdbV0044PostClustersJSONRequestBody{
		Clusters: []api.V0044ClusterRec{*apiInput},
	}
	// Call the API (params is nil for default behavior)
	resp, err := a.client.SlurmdbV0044PostClustersWithResponse(ctx, nil, reqBody)
	if err != nil {
		return nil, a.HandleAPIError(err)
	}
	// Handle response errors
	var apiErrors *api.V0044OpenapiErrors
	if resp.JSON200 != nil {
		apiErrors = resp.JSON200.Errors
	}
	responseAdapter := api.NewResponseAdapter(resp.StatusCode(), apiErrors)
	if err := common.HandleAPIResponse(responseAdapter, "v0.0.44"); err != nil {
		return nil, err
	}
	return &types.ClusterCreateResponse{}, nil
}

// Delete removes a cluster by clusterName
func (a *ClusterAdapter) Delete(ctx context.Context, clusterName string) error {
	// Validate context
	if err := a.ValidateContext(ctx); err != nil {
		return err
	}
	if err := a.ValidateResourceName(clusterName, "clusterName"); err != nil {
		return err
	}
	if err := a.CheckClientInitialized(a.client); err != nil {
		return err
	}
	// Call the API (params is nil for default behavior)
	resp, err := a.client.SlurmdbV0044DeleteClusterWithResponse(ctx, clusterName, nil)
	if err != nil {
		return a.HandleAPIError(err)
	}
	// Handle response errors
	var apiErrors *api.V0044OpenapiErrors
	if resp.JSON200 != nil {
		apiErrors = resp.JSON200.Errors
	}
	responseAdapter := api.NewResponseAdapter(resp.StatusCode(), apiErrors)
	// For DELETE operations, 204 is also a success
	if resp.StatusCode() == 204 {
		return nil
	}
	return common.HandleAPIResponse(responseAdapter, "v0.0.44")
}
