// Code generated by generate_adapters.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0
package v0_0_44

import (
	types "github.com/jontk/slurm-client/api"
	"github.com/jontk/slurm-client/pkg/errors"
)

// ValidateClusterCreate validates cluster create data
func (a *ClusterAdapter) ValidateClusterCreate(create *types.ClusterCreate) error {
	if create == nil {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "cluster creation data is required", "create", nil, nil)
	}
	if create.Name == "" {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "cluster name is required", "name", nil, nil)
	}
	return nil
}
