// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v0_0_44

import (
	api "github.com/jontk/slurm-client/api"
	v0044 "github.com/jontk/slurm-client/internal/openapi/v0_0_44"
)

type ClusterConverterGoverterImpl struct{}

func (c *ClusterConverterGoverterImpl) ConvertAPIClusterToCommon(source v0044.V0044ClusterRec) *api.Cluster {
	var apiCluster api.Cluster
	apiCluster.Associations = ConvertClusterAssociations(source.Associations)
	apiCluster.Controller = ConvertClusterController(source.Controller)
	apiCluster.Flags = ConvertClusterFlags(source.Flags)
	if source.Name != nil {
		xstring := *source.Name
		apiCluster.Name = &xstring
	}
	if source.Nodes != nil {
		xstring2 := *source.Nodes
		apiCluster.Nodes = &xstring2
	}
	if source.RpcVersion != nil {
		xint32 := *source.RpcVersion
		apiCluster.RpcVersion = &xint32
	}
	if source.SelectPlugin != nil {
		xstring3 := *source.SelectPlugin
		apiCluster.SelectPlugin = &xstring3
	}
	apiCluster.TRES = ConvertClusterTRES(source.Tres)
	return &apiCluster
}
