// Code generated by generate_adapters.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0
package v0_0_44

import (
	"context"
	"testing"

	types "github.com/jontk/slurm-client/api"
	api "github.com/jontk/slurm-client/internal/openapi/v0_0_44"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestNewJobAdapter(t *testing.T) {
	client := &api.ClientWithResponses{}
	adapter := NewJobAdapter(client)
	require.NotNil(t, adapter)
}
func TestJobAdapter_ValidateContext(t *testing.T) {
	adapter := NewJobAdapter(&api.ClientWithResponses{})
	// Test nil context
	//lint:ignore SA1012 intentionally testing nil context validation
	err := adapter.ValidateContext(nil)
	assert.Error(t, err)
	// Test valid context
	err = adapter.ValidateContext(context.Background())
	assert.NoError(t, err)
}
func TestJobAdapter_List_NilContext(t *testing.T) {
	adapter := NewJobAdapter(&api.ClientWithResponses{})
	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.List(nil, nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}
func TestJobAdapter_List_ClientNotInitialized(t *testing.T) {
	adapter := NewJobAdapter(nil)
	result, err := adapter.List(context.Background(), nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}
func TestJobAdapter_Get_NilContext(t *testing.T) {
	adapter := NewJobAdapter(&api.ClientWithResponses{})
	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.Get(nil, 123)
	assert.Nil(t, result)
	assert.Error(t, err)
}
func TestJobAdapter_Get_EmptyIdentifier(t *testing.T) {
	adapter := NewJobAdapter(&api.ClientWithResponses{})
	result, err := adapter.Get(context.Background(), 0)
	assert.Nil(t, result)
	assert.Error(t, err)
}
func TestJobAdapter_Get_ClientNotInitialized(t *testing.T) {
	adapter := NewJobAdapter(nil)
	result, err := adapter.Get(context.Background(), 123)
	assert.Nil(t, result)
	assert.Error(t, err)
}
func TestJobAdapter_Submit_NilContext(t *testing.T) {
	adapter := NewJobAdapter(&api.ClientWithResponses{})
	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.Submit(nil, &types.JobCreate{})
	assert.Nil(t, result)
	assert.Error(t, err)
}
func TestJobAdapter_Submit_NilInput(t *testing.T) {
	adapter := NewJobAdapter(&api.ClientWithResponses{})
	result, err := adapter.Submit(context.Background(), nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}
func TestJobAdapter_Submit_ClientNotInitialized(t *testing.T) {
	adapter := NewJobAdapter(nil)
	result, err := adapter.Submit(context.Background(), &types.JobCreate{})
	assert.Nil(t, result)
	assert.Error(t, err)
}
func TestJobAdapter_Update_NilContext(t *testing.T) {
	adapter := NewJobAdapter(&api.ClientWithResponses{})
	//lint:ignore SA1012 intentionally testing nil context
	err := adapter.Update(nil, 123, &types.JobUpdate{})
	assert.Error(t, err)
}
func TestJobAdapter_Update_NilInput(t *testing.T) {
	adapter := NewJobAdapter(&api.ClientWithResponses{})
	err := adapter.Update(context.Background(), 123, nil)
	assert.Error(t, err)
}
func TestJobAdapter_Update_ClientNotInitialized(t *testing.T) {
	adapter := NewJobAdapter(nil)
	err := adapter.Update(context.Background(), 123, &types.JobUpdate{})
	assert.Error(t, err)
}
func TestJobAdapter_Cancel_NilContext(t *testing.T) {
	adapter := NewJobAdapter(&api.ClientWithResponses{})
	//lint:ignore SA1012 intentionally testing nil context
	err := adapter.Cancel(nil, 123, nil)
	assert.Error(t, err)
}
func TestJobAdapter_Cancel_InvalidJobID(t *testing.T) {
	adapter := NewJobAdapter(&api.ClientWithResponses{})
	err := adapter.Cancel(context.Background(), 0, nil)
	assert.Error(t, err)
}
func TestJobAdapter_Cancel_ClientNotInitialized(t *testing.T) {
	adapter := NewJobAdapter(nil)
	err := adapter.Cancel(context.Background(), 123, nil)
	assert.Error(t, err)
}
func TestJobAdapter_ReadConverter(t *testing.T) {
	adapter := NewJobAdapter(&api.ClientWithResponses{})
	// Create test API object with known values
	testID := int32(12345)
	testName := "test-job"
	testUserName := "testuser"
	apiObj := api.V0044JobInfo{
		JobId:    &testID,
		Name:     &testName,
		UserName: &testUserName,
	}
	// Convert API → Common
	commonObj := adapter.convertAPIJobToCommon(apiObj)
	require.NotNil(t, commonObj)
	// Verify field values were correctly converted
	if commonObj.JobID != nil {
		assert.Equal(t, testID, *commonObj.JobID)
	}
	if commonObj.Name != nil {
		assert.Equal(t, testName, *commonObj.Name)
	}
	if commonObj.UserName != nil {
		assert.Equal(t, testUserName, *commonObj.UserName)
	}
}
func TestJobAdapter_ValidateCreate(t *testing.T) {
	adapter := NewJobAdapter(&api.ClientWithResponses{})
	t.Run("nil input returns error", func(t *testing.T) {
		err := adapter.ValidateJobCreate(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "job creation data is required")
	})
	t.Run("missing Script returns error", func(t *testing.T) {
		input := &types.JobCreate{}
		err := adapter.ValidateJobCreate(input)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "job script is required")
	})
	t.Run("valid input passes", func(t *testing.T) {
		input := &types.JobCreate{Script: ptrString("test")}
		err := adapter.ValidateJobCreate(input)
		require.NoError(t, err)
	})
}
func TestJobAdapter_ValidateUpdate(t *testing.T) {
	adapter := NewJobAdapter(&api.ClientWithResponses{})
	t.Run("nil input returns error", func(t *testing.T) {
		err := adapter.validateJobUpdate(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "job update data is required")
	})
	t.Run("valid input passes", func(t *testing.T) {
		input := &types.JobUpdate{}
		err := adapter.validateJobUpdate(input)
		require.NoError(t, err)
	})
}
