// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v0_0_44

import (
	api "github.com/jontk/slurm-client/api"
	v0044 "github.com/jontk/slurm-client/internal/openapi/v0_0_44"
)

type PartitionConverterGoverterImpl struct{}

func (c *PartitionConverterGoverterImpl) ConvertAPIPartitionToCommon(source v0044.V0044PartitionInfo) *api.Partition {
	var apiPartition api.Partition
	apiPartition.Accounts = ConvertPartitionAccounts(source.Accounts)
	if source.Alternate != nil {
		xstring := *source.Alternate
		apiPartition.Alternate = &xstring
	}
	if source.Cluster != nil {
		xstring2 := *source.Cluster
		apiPartition.Cluster = &xstring2
	}
	apiPartition.CPUs = ConvertPartitionCPUs(source.Cpus)
	apiPartition.Defaults = ConvertPartitionDefaults(source.Defaults)
	if source.GraceTime != nil {
		xint32 := *source.GraceTime
		apiPartition.GraceTime = &xint32
	}
	apiPartition.Groups = ConvertPartitionGroups(source.Groups)
	apiPartition.Maximums = ConvertPartitionMaximums(source.Maximums)
	apiPartition.Minimums = ConvertPartitionMinimums(source.Minimums)
	if source.Name != nil {
		xstring3 := *source.Name
		apiPartition.Name = &xstring3
	}
	if source.NodeSets != nil {
		xstring4 := *source.NodeSets
		apiPartition.NodeSets = &xstring4
	}
	apiPartition.Nodes = ConvertPartitionNodes(source.Nodes)
	apiPartition.Partition = ConvertPartitionPartition(source.Partition)
	apiPartition.Priority = ConvertPartitionPriority(source.Priority)
	apiPartition.QoS = ConvertPartitionQoS(source.Qos)
	apiPartition.SelectType = ConvertPartitionSelectType(source.SelectType)
	apiPartition.SuspendTime = ConvertPartitionSuspendTime(source.SuspendTime)
	apiPartition.Timeouts = ConvertPartitionTimeouts(source.Timeouts)
	if source.Topology != nil {
		xstring5 := *source.Topology
		apiPartition.Topology = &xstring5
	}
	apiPartition.TRES = ConvertPartitionTRES(source.Tres)
	return &apiPartition
}
