// Code generated by generate_adapters.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0

package v0_0_44

import (
	"context"
	"fmt"

	types "github.com/jontk/slurm-client/api"
	adapterbase "github.com/jontk/slurm-client/internal/adapters/base"
	"github.com/jontk/slurm-client/internal/common"
	api "github.com/jontk/slurm-client/internal/openapi/v0_0_44"
	"github.com/jontk/slurm-client/pkg/errors"
)

// PartitionAdapter implements the Partition adapter interface for v0_0_44
type PartitionAdapter struct {
	*adapterbase.BaseManager
	client *api.ClientWithResponses
}

// NewPartitionAdapter creates a new Partition adapter
func NewPartitionAdapter(client *api.ClientWithResponses) *PartitionAdapter {
	return &PartitionAdapter{
		BaseManager: adapterbase.NewBaseManager("v0.0.44", "Partition"),
		client:      client,
	}
}

// List retrieves a list of partitions with optional filtering
func (a *PartitionAdapter) List(ctx context.Context, opts *types.PartitionListOptions) (*types.PartitionList, error) {
	// Validate context
	if err := a.ValidateContext(ctx); err != nil {
		return nil, err
	}

	// Check client initialization
	if err := a.CheckClientInitialized(a.client); err != nil {
		return nil, err
	}

	// Prepare parameters
	params := &api.SlurmV0044GetPartitionsParams{}

	// Call the API
	resp, err := a.client.SlurmV0044GetPartitionsWithResponse(ctx, params)
	if err != nil {
		return nil, a.HandleAPIError(err)
	}

	// Handle response errors
	var apiErrors *api.V0044OpenapiErrors
	if resp.JSON200 != nil {
		apiErrors = resp.JSON200.Errors
	}
	responseAdapter := api.NewResponseAdapter(resp.StatusCode(), apiErrors)
	if err := common.HandleAPIResponse(responseAdapter, "v0.0.44"); err != nil {
		return nil, err
	}

	// Check for nil response
	if err := a.CheckNilResponse(resp.JSON200, "List Partitions"); err != nil {
		return nil, err
	}

	// Convert response to common types
	items := make([]types.Partition, 0, len(resp.JSON200.Partitions))
	for _, apiItem := range resp.JSON200.Partitions {
		item := a.convertAPIPartitionToCommon(apiItem)
		items = append(items, *item)
	}

	// Apply pagination
	listOpts := adapterbase.ListOptions{}
	if opts != nil {
		listOpts.Limit = opts.Limit
		listOpts.Offset = opts.Offset
	}

	start := listOpts.Offset
	if start < 0 {
		start = 0
	}
	if start >= len(items) {
		return &types.PartitionList{
			Partitions: []types.Partition{},
			Total:      len(items),
		}, nil
	}

	end := len(items)
	if listOpts.Limit > 0 {
		end = start + listOpts.Limit
		if end > len(items) {
			end = len(items)
		}
	}

	return &types.PartitionList{
		Partitions: items[start:end],
		Total:      len(items),
	}, nil
}

// Get retrieves a specific partition by partitionName
func (a *PartitionAdapter) Get(ctx context.Context, partitionName string) (*types.Partition, error) {
	// Validate context
	if err := a.ValidateContext(ctx); err != nil {
		return nil, err
	}
	if err := a.ValidateResourceName(partitionName, "partitionName"); err != nil {
		return nil, err
	}
	if err := a.CheckClientInitialized(a.client); err != nil {
		return nil, err
	}

	// Prepare parameters
	params := &api.SlurmV0044GetPartitionParams{}

	// Call the API
	resp, err := a.client.SlurmV0044GetPartitionWithResponse(ctx, partitionName, params)
	if err != nil {
		return nil, a.HandleAPIError(err)
	}

	// Handle response errors
	var apiErrors *api.V0044OpenapiErrors
	if resp.JSON200 != nil {
		apiErrors = resp.JSON200.Errors
	}
	responseAdapter := api.NewResponseAdapter(resp.StatusCode(), apiErrors)
	if err := common.HandleAPIResponse(responseAdapter, "v0.0.44"); err != nil {
		return nil, err
	}

	// Check for nil response
	if err := a.CheckNilResponse(resp.JSON200, "Get Partition"); err != nil {
		return nil, err
	}

	// Check if entity exists
	if len(resp.JSON200.Partitions) == 0 {
		return nil, errors.NewSlurmError(errors.ErrorCodeResourceNotFound,
			fmt.Sprintf("Partition %s not found", partitionName))
	}

	// Convert and return
	return a.convertAPIPartitionToCommon(resp.JSON200.Partitions[0]), nil
}

// Create is not supported in this API version
func (a *PartitionAdapter) Create(ctx context.Context, partition *types.PartitionCreate) (*types.PartitionCreateResponse, error) {
	return nil, errors.NewClientError(
		errors.ErrorCodeUnsupportedOperation,
		"partition create not supported in this version",
		"Method not allowed (405)")
}

// Update is not supported in this API version
func (a *PartitionAdapter) Update(ctx context.Context, partitionName string, update *types.PartitionUpdate) error {
	return errors.NewClientError(
		errors.ErrorCodeUnsupportedOperation,
		"partition update not supported in this version",
		"Method not allowed (405)")
}

// Delete is not supported in this API version
func (a *PartitionAdapter) Delete(ctx context.Context, partitionName string) error {
	return errors.NewClientError(
		errors.ErrorCodeUnsupportedOperation,
		"partition delete not supported in this version",
		"Method not allowed (405)")
}
