// Code generated by generate_adapters.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0

package v0_0_44

import (
	types "github.com/jontk/slurm-client/api"
	"github.com/jontk/slurm-client/pkg/errors"
)

// ValidateQoSCreate validates qos create data
func (a *QoSAdapter) ValidateQoSCreate(create *types.QoSCreate) error {
	if create == nil {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "QoS creation data is required", "create", nil, nil)
	}
	if create.Name == "" {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "QoS name is required", "name", nil, nil)
	}
	return nil
}

// validateQoSUpdate validates qos update data
func (a *QoSAdapter) validateQoSUpdate(update *types.QoSUpdate) error {
	if update == nil {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "QoS update data is required", "update", nil, nil)
	}
	return nil
}
