// Code generated by generate_adapters.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0

package v0_0_44

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	types "github.com/jontk/slurm-client/api"
	api "github.com/jontk/slurm-client/internal/openapi/v0_0_44"
)

func TestNewQoSAdapter(t *testing.T) {
	client := &api.ClientWithResponses{}
	adapter := NewQoSAdapter(client)
	require.NotNil(t, adapter)
}

func TestQoSAdapter_ValidateContext(t *testing.T) {
	adapter := NewQoSAdapter(&api.ClientWithResponses{})

	// Test nil context
	//lint:ignore SA1012 intentionally testing nil context validation
	err := adapter.ValidateContext(nil)
	assert.Error(t, err)

	// Test valid context
	err = adapter.ValidateContext(context.Background())
	assert.NoError(t, err)
}

func TestQoSAdapter_List_NilContext(t *testing.T) {
	adapter := NewQoSAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.List(nil, nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestQoSAdapter_List_ClientNotInitialized(t *testing.T) {
	adapter := NewQoSAdapter(nil)

	result, err := adapter.List(context.Background(), nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestQoSAdapter_Get_NilContext(t *testing.T) {
	adapter := NewQoSAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.Get(nil, "test-qos")
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestQoSAdapter_Get_EmptyIdentifier(t *testing.T) {
	adapter := NewQoSAdapter(&api.ClientWithResponses{})

	result, err := adapter.Get(context.Background(), "")
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestQoSAdapter_Get_ClientNotInitialized(t *testing.T) {
	adapter := NewQoSAdapter(nil)

	result, err := adapter.Get(context.Background(), "test-qos")
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestQoSAdapter_Create_NilContext(t *testing.T) {
	adapter := NewQoSAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.Create(nil, &types.QoSCreate{})
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestQoSAdapter_Create_NilInput(t *testing.T) {
	adapter := NewQoSAdapter(&api.ClientWithResponses{})

	result, err := adapter.Create(context.Background(), nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestQoSAdapter_Create_ClientNotInitialized(t *testing.T) {
	adapter := NewQoSAdapter(nil)

	result, err := adapter.Create(context.Background(), &types.QoSCreate{})
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestQoSAdapter_Update_NilContext(t *testing.T) {
	adapter := NewQoSAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	err := adapter.Update(nil, "test-qos", &types.QoSUpdate{})
	assert.Error(t, err)
}

func TestQoSAdapter_Update_NilInput(t *testing.T) {
	adapter := NewQoSAdapter(&api.ClientWithResponses{})

	err := adapter.Update(context.Background(), "test-qos", nil)
	assert.Error(t, err)
}

func TestQoSAdapter_Update_ClientNotInitialized(t *testing.T) {
	adapter := NewQoSAdapter(nil)

	err := adapter.Update(context.Background(), "test-qos", &types.QoSUpdate{})
	assert.Error(t, err)
}

func TestQoSAdapter_Delete_NilContext(t *testing.T) {
	adapter := NewQoSAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	err := adapter.Delete(nil, "test-qos")
	assert.Error(t, err)
}

func TestQoSAdapter_Delete_EmptyIdentifier(t *testing.T) {
	adapter := NewQoSAdapter(&api.ClientWithResponses{})

	err := adapter.Delete(context.Background(), "")
	assert.Error(t, err)
}

func TestQoSAdapter_Delete_ClientNotInitialized(t *testing.T) {
	adapter := NewQoSAdapter(nil)

	err := adapter.Delete(context.Background(), "test-qos")
	assert.Error(t, err)
}

func TestQoSAdapter_ReadConverter(t *testing.T) {
	adapter := NewQoSAdapter(&api.ClientWithResponses{})

	// Create test API object with known values
	testName := "test-qos"
	testDesc := "test description"
	testID := int32(42)
	apiObj := api.V0044Qos{
		Name:        &testName,
		Description: &testDesc,
		Id:          &testID,
	}

	// Convert API → Common
	commonObj := adapter.convertAPIQoSToCommon(apiObj)
	require.NotNil(t, commonObj)

	// Verify field values were correctly converted
	if commonObj.Name != nil {
		assert.Equal(t, testName, *commonObj.Name)
	}
	if commonObj.Description != nil {
		assert.Equal(t, testDesc, *commonObj.Description)
	}
	if commonObj.ID != nil {
		assert.Equal(t, testID, *commonObj.ID)
	}
}

func TestQoSAdapter_CreateConverter(t *testing.T) {
	adapter := NewQoSAdapter(&api.ClientWithResponses{})

	// Create test input with known values
	testName := "test-qos"
	input := &types.QoSCreate{
		Name: testName,
	}

	// Convert Common → API
	apiObj := adapter.convertCommonQoSCreateToAPI(input)
	require.NotNil(t, apiObj)
}

func TestQoSAdapter_UpdateConverter(t *testing.T) {
	adapter := NewQoSAdapter(&api.ClientWithResponses{})

	// Create test input with known values
	testDesc := "test description"
	input := &types.QoSUpdate{
		Description: &testDesc,
	}

	// Convert Common → API
	apiObj := adapter.convertCommonQoSUpdateToAPI(input)
	require.NotNil(t, apiObj)
}

func TestQoSAdapter_ValidateCreate(t *testing.T) {
	adapter := NewQoSAdapter(&api.ClientWithResponses{})

	t.Run("nil input returns error", func(t *testing.T) {
		err := adapter.ValidateQoSCreate(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "QoS creation data is required")
	})

	t.Run("missing Name returns error", func(t *testing.T) {
		input := &types.QoSCreate{}
		err := adapter.ValidateQoSCreate(input)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "QoS name is required")
	})

	t.Run("valid input passes", func(t *testing.T) {
		input := &types.QoSCreate{Name: "test"}
		err := adapter.ValidateQoSCreate(input)
		require.NoError(t, err)
	})
}

func TestQoSAdapter_ValidateUpdate(t *testing.T) {
	adapter := NewQoSAdapter(&api.ClientWithResponses{})

	t.Run("nil input returns error", func(t *testing.T) {
		err := adapter.validateQoSUpdate(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "QoS update data is required")
	})

	t.Run("valid input passes", func(t *testing.T) {
		input := &types.QoSUpdate{}
		err := adapter.validateQoSUpdate(input)
		require.NoError(t, err)
	})
}
