// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v0_0_44

import (
	api "github.com/jontk/slurm-client/api"
	v0044 "github.com/jontk/slurm-client/internal/openapi/v0_0_44"
)

type UserConverterGoverterImpl struct{}

func (c *UserConverterGoverterImpl) ConvertAPIUserToCommon(source v0044.V0044User) *api.User {
	var apiUser api.User
	apiUser.AdministratorLevel = ConvertAdminLevelSlice(source.AdministratorLevel)
	apiUser.Associations = ConvertAssocShortSlice(source.Associations)
	apiUser.Coordinators = ConvertCoordSlice(source.Coordinators)
	apiUser.Default = ConvertUserDefault(source.Default)
	apiUser.Flags = ConvertUserFlags(source.Flags)
	apiUser.Name = source.Name
	if source.OldName != nil {
		xstring := *source.OldName
		apiUser.OldName = &xstring
	}
	apiUser.Wckeys = ConvertWckeySlice(source.Wckeys)
	return &apiUser
}
