// Code generated by generate_adapters.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0

package v0_0_44

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	types "github.com/jontk/slurm-client/api"
	api "github.com/jontk/slurm-client/internal/openapi/v0_0_44"
)

func TestNewUserAdapter(t *testing.T) {
	client := &api.ClientWithResponses{}
	adapter := NewUserAdapter(client)
	require.NotNil(t, adapter)
}

func TestUserAdapter_ValidateContext(t *testing.T) {
	adapter := NewUserAdapter(&api.ClientWithResponses{})

	// Test nil context
	//lint:ignore SA1012 intentionally testing nil context validation
	err := adapter.ValidateContext(nil)
	assert.Error(t, err)

	// Test valid context
	err = adapter.ValidateContext(context.Background())
	assert.NoError(t, err)
}

func TestUserAdapter_List_NilContext(t *testing.T) {
	adapter := NewUserAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.List(nil, nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestUserAdapter_List_ClientNotInitialized(t *testing.T) {
	adapter := NewUserAdapter(nil)

	result, err := adapter.List(context.Background(), nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestUserAdapter_Get_NilContext(t *testing.T) {
	adapter := NewUserAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.Get(nil, "test-user")
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestUserAdapter_Get_EmptyIdentifier(t *testing.T) {
	adapter := NewUserAdapter(&api.ClientWithResponses{})

	result, err := adapter.Get(context.Background(), "")
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestUserAdapter_Get_ClientNotInitialized(t *testing.T) {
	adapter := NewUserAdapter(nil)

	result, err := adapter.Get(context.Background(), "test-user")
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestUserAdapter_Create_NilContext(t *testing.T) {
	adapter := NewUserAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.Create(nil, &types.UserCreate{})
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestUserAdapter_Create_NilInput(t *testing.T) {
	adapter := NewUserAdapter(&api.ClientWithResponses{})

	result, err := adapter.Create(context.Background(), nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestUserAdapter_Create_ClientNotInitialized(t *testing.T) {
	adapter := NewUserAdapter(nil)

	result, err := adapter.Create(context.Background(), &types.UserCreate{})
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestUserAdapter_Update_NilContext(t *testing.T) {
	adapter := NewUserAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	err := adapter.Update(nil, "test-user", &types.UserUpdate{})
	assert.Error(t, err)
}

func TestUserAdapter_Update_NilInput(t *testing.T) {
	adapter := NewUserAdapter(&api.ClientWithResponses{})

	err := adapter.Update(context.Background(), "test-user", nil)
	assert.Error(t, err)
}

func TestUserAdapter_Update_ClientNotInitialized(t *testing.T) {
	adapter := NewUserAdapter(nil)

	err := adapter.Update(context.Background(), "test-user", &types.UserUpdate{})
	assert.Error(t, err)
}

func TestUserAdapter_Delete_NilContext(t *testing.T) {
	adapter := NewUserAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	err := adapter.Delete(nil, "test-user")
	assert.Error(t, err)
}

func TestUserAdapter_Delete_EmptyIdentifier(t *testing.T) {
	adapter := NewUserAdapter(&api.ClientWithResponses{})

	err := adapter.Delete(context.Background(), "")
	assert.Error(t, err)
}

func TestUserAdapter_Delete_ClientNotInitialized(t *testing.T) {
	adapter := NewUserAdapter(nil)

	err := adapter.Delete(context.Background(), "test-user")
	assert.Error(t, err)
}

func TestUserAdapter_ReadConverter(t *testing.T) {
	adapter := NewUserAdapter(&api.ClientWithResponses{})

	// Create test API object with known values
	testName := "test-user"
	testOldName := "old-user"
	apiObj := api.V0044User{
		Name:    testName,
		OldName: &testOldName,
	}

	// Convert API → Common
	commonObj := adapter.convertAPIUserToCommon(apiObj)
	require.NotNil(t, commonObj)

	// Verify field values were correctly converted
	assert.Equal(t, testName, commonObj.Name)
	if commonObj.OldName != nil {
		assert.Equal(t, testOldName, *commonObj.OldName)
	}
}

func TestUserAdapter_CreateConverter(t *testing.T) {
	adapter := NewUserAdapter(&api.ClientWithResponses{})

	// Create test input with known values
	testName := "test-user"
	input := &types.UserCreate{
		Name: testName,
	}

	// Convert Common → API
	apiObj := adapter.convertCommonUserCreateToAPI(input)
	require.NotNil(t, apiObj)
}

func TestUserAdapter_UpdateConverter(t *testing.T) {
	adapter := NewUserAdapter(&api.ClientWithResponses{})

	// Create test input with known values
	testAccount := "test-account"
	input := &types.UserUpdate{
		DefaultAccount: &testAccount,
	}

	// Convert Common → API
	apiObj := adapter.convertCommonUserUpdateToAPI(input)
	require.NotNil(t, apiObj)
}

func TestUserAdapter_ValidateCreate(t *testing.T) {
	adapter := NewUserAdapter(&api.ClientWithResponses{})

	t.Run("nil input returns error", func(t *testing.T) {
		err := adapter.ValidateUserCreate(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "user creation data is required")
	})

	t.Run("missing Name returns error", func(t *testing.T) {
		input := &types.UserCreate{}
		err := adapter.ValidateUserCreate(input)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "user name is required")
	})

	t.Run("valid input passes", func(t *testing.T) {
		input := &types.UserCreate{Name: "test"}
		err := adapter.ValidateUserCreate(input)
		require.NoError(t, err)
	})
}

func TestUserAdapter_ValidateUpdate(t *testing.T) {
	adapter := NewUserAdapter(&api.ClientWithResponses{})

	t.Run("nil input returns error", func(t *testing.T) {
		err := adapter.validateUserUpdate(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "user update data is required")
	})

	t.Run("valid input passes", func(t *testing.T) {
		input := &types.UserUpdate{}
		err := adapter.validateUserUpdate(input)
		require.NoError(t, err)
	})
}
