// Code generated by generate_adapters.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0
package v0_0_44

import (
	"context"
	"fmt"

	types "github.com/jontk/slurm-client/api"
	adapterbase "github.com/jontk/slurm-client/internal/adapters/base"
	"github.com/jontk/slurm-client/internal/common"
	api "github.com/jontk/slurm-client/internal/openapi/v0_0_44"
	"github.com/jontk/slurm-client/pkg/errors"
)

// WCKeyAdapter implements the WCKey adapter interface for v0_0_44
type WCKeyAdapter struct {
	*adapterbase.BaseManager
	client *api.ClientWithResponses
}

// NewWCKeyAdapter creates a new WCKey adapter
func NewWCKeyAdapter(client *api.ClientWithResponses) *WCKeyAdapter {
	return &WCKeyAdapter{
		BaseManager: adapterbase.NewBaseManager("v0.0.44", "WCKey"),
		client:      client,
	}
}

// List retrieves a list of wckeys with optional filtering
func (a *WCKeyAdapter) List(ctx context.Context, opts *types.WCKeyListOptions) (*types.WCKeyList, error) {
	// Validate context
	if err := a.ValidateContext(ctx); err != nil {
		return nil, err
	}
	// Check client initialization
	if err := a.CheckClientInitialized(a.client); err != nil {
		return nil, err
	}
	// Prepare parameters
	params := &api.SlurmdbV0044GetWckeysParams{}
	// Call the API
	resp, err := a.client.SlurmdbV0044GetWckeysWithResponse(ctx, params)
	if err != nil {
		return nil, a.HandleAPIError(err)
	}
	// Handle response errors
	var apiErrors *api.V0044OpenapiErrors
	if resp.JSON200 != nil {
		apiErrors = resp.JSON200.Errors
	}
	responseAdapter := api.NewResponseAdapter(resp.StatusCode(), apiErrors)
	if err := common.HandleAPIResponse(responseAdapter, "v0.0.44"); err != nil {
		return nil, err
	}
	// Check for nil response
	if err := a.CheckNilResponse(resp.JSON200, "List WCKeys"); err != nil {
		return nil, err
	}
	// Convert response to common types
	items := make([]types.WCKey, 0, len(resp.JSON200.Wckeys))
	for _, apiItem := range resp.JSON200.Wckeys {
		item := a.convertAPIWCKeyToCommon(apiItem)
		items = append(items, *item)
	}
	// Apply pagination
	listOpts := adapterbase.ListOptions{}
	if opts != nil {
		listOpts.Limit = opts.Limit
		listOpts.Offset = opts.Offset
	}
	start := listOpts.Offset
	if start < 0 {
		start = 0
	}
	if start >= len(items) {
		return &types.WCKeyList{
			WCKeys: []types.WCKey{},
			Total:  len(items),
		}, nil
	}
	end := len(items)
	if listOpts.Limit > 0 {
		end = start + listOpts.Limit
		if end > len(items) {
			end = len(items)
		}
	}
	return &types.WCKeyList{
		WCKeys: items[start:end],
		Total:  len(items),
	}, nil
}

// Get retrieves a specific wckey by wckeyName
func (a *WCKeyAdapter) Get(ctx context.Context, wckeyName string) (*types.WCKey, error) {
	// Validate context
	if err := a.ValidateContext(ctx); err != nil {
		return nil, err
	}
	if err := a.ValidateResourceName(wckeyName, "wckeyName"); err != nil {
		return nil, err
	}
	if err := a.CheckClientInitialized(a.client); err != nil {
		return nil, err
	}
	// Call the API (no params)
	resp, err := a.client.SlurmdbV0044GetWckeyWithResponse(ctx, wckeyName)
	if err != nil {
		return nil, a.HandleAPIError(err)
	}
	// Handle response errors
	var apiErrors *api.V0044OpenapiErrors
	if resp.JSON200 != nil {
		apiErrors = resp.JSON200.Errors
	}
	responseAdapter := api.NewResponseAdapter(resp.StatusCode(), apiErrors)
	if err := common.HandleAPIResponse(responseAdapter, "v0.0.44"); err != nil {
		return nil, err
	}
	// Check for nil response
	if err := a.CheckNilResponse(resp.JSON200, "Get WCKey"); err != nil {
		return nil, err
	}
	// Check if entity exists
	if len(resp.JSON200.Wckeys) == 0 {
		return nil, errors.NewSlurmError(errors.ErrorCodeResourceNotFound,
			fmt.Sprintf("WCKey %s not found", wckeyName))
	}
	// Convert and return
	return a.convertAPIWCKeyToCommon(resp.JSON200.Wckeys[0]), nil
}

// Create creates a new wckey
func (a *WCKeyAdapter) Create(ctx context.Context, input *types.WCKeyCreate) (*types.WCKeyCreateResponse, error) {
	// Validate context
	if err := a.ValidateContext(ctx); err != nil {
		return nil, err
	}
	if input == nil {
		return nil, errors.NewValidationError(errors.ErrorCodeValidationFailed, "input is required", "input", nil, nil)
	}
	if err := a.CheckClientInitialized(a.client); err != nil {
		return nil, err
	}
	// Convert to API type
	apiInput := a.convertCommonWCKeyCreateToAPI(input)
	// Create request body with the entity wrapped in a slice
	reqBody := api.SlurmdbV0044PostWckeysJSONRequestBody{
		Wckeys: []api.V0044Wckey{*apiInput},
	}
	// Call the API (params is nil for default behavior)
	resp, err := a.client.SlurmdbV0044PostWckeysWithResponse(ctx, nil, reqBody)
	if err != nil {
		return nil, a.HandleAPIError(err)
	}
	// Handle response errors
	var apiErrors *api.V0044OpenapiErrors
	if resp.JSON200 != nil {
		apiErrors = resp.JSON200.Errors
	}
	responseAdapter := api.NewResponseAdapter(resp.StatusCode(), apiErrors)
	if err := common.HandleAPIResponse(responseAdapter, "v0.0.44"); err != nil {
		return nil, err
	}
	return &types.WCKeyCreateResponse{}, nil
}

// Delete removes a wckey by wckeyName
func (a *WCKeyAdapter) Delete(ctx context.Context, wckeyName string) error {
	// Validate context
	if err := a.ValidateContext(ctx); err != nil {
		return err
	}
	if err := a.ValidateResourceName(wckeyName, "wckeyName"); err != nil {
		return err
	}
	if err := a.CheckClientInitialized(a.client); err != nil {
		return err
	}
	// Call the API
	resp, err := a.client.SlurmdbV0044DeleteWckeyWithResponse(ctx, wckeyName)
	if err != nil {
		return a.HandleAPIError(err)
	}
	// Handle response errors
	var apiErrors *api.V0044OpenapiErrors
	if resp.JSON200 != nil {
		apiErrors = resp.JSON200.Errors
	}
	responseAdapter := api.NewResponseAdapter(resp.StatusCode(), apiErrors)
	// For DELETE operations, 204 is also a success
	if resp.StatusCode() == 204 {
		return nil
	}
	return common.HandleAPIResponse(responseAdapter, "v0.0.44")
}
