// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v0_0_44

import (
	api "github.com/jontk/slurm-client/api"
	v0044 "github.com/jontk/slurm-client/internal/openapi/v0_0_44"
)

type WCKeyConverterGoverterImpl struct{}

func (c *WCKeyConverterGoverterImpl) ConvertAPIWCKeyToCommon(source v0044.V0044Wckey) *api.WCKey {
	var apiWCKey api.WCKey
	apiWCKey.Accounting = ConvertAccounting(source.Accounting)
	apiWCKey.Cluster = source.Cluster
	apiWCKey.Flags = ConvertWCKeyFlags(source.Flags)
	if source.Id != nil {
		xint32 := *source.Id
		apiWCKey.ID = &xint32
	}
	apiWCKey.Name = source.Name
	apiWCKey.User = source.User
	return &apiWCKey
}
