//go:build ignore

package main

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
)

// Code generation tool for Slurm REST API clients using oapi-codegen
func main() {
	if len(os.Args) < 2 {
		log.Fatal("Usage: go run generate.go <version> [spec-file]")
	}
	
	version := os.Args[1]
	var specFile string
	
	if len(os.Args) >= 3 {
		specFile = os.Args[2]
	} else {
		specFile = filepath.Join("openapi-specs", fmt.Sprintf("slurm-%s.yaml", version))
	}
	
	if err := generateClient(version, specFile); err != nil {
		log.Fatalf("Failed to generate client for %s: %v", version, err)
	}
	
	fmt.Printf("Successfully generated client for version %s\n", version)
}

func generateClient(version, specFile string) error {
	// Check if spec file exists
	if _, err := os.Stat(specFile); os.IsNotExist(err) {
		return fmt.Errorf("OpenAPI spec file not found: %s", specFile)
	}
	
	// Ensure output directory exists
	outputDir := filepath.Join("internal", "api", normalizeVersion(version))
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}
	
	outputFile := filepath.Join(outputDir, "client.go")
	
	// Generate client using oapi-codegen
	cmd := exec.Command("/Users/jontk/go/bin/oapi-codegen",
		"-package", normalizeVersion(version),
		"-generate", "client,models,spec",
		"-o", outputFile,
		specFile,
	)
	
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("oapi-codegen failed: %w", err)
	}
	
	// Generate wrapper client
	return generateWrapper(version, outputDir)
}

func generateWrapper(version, outputDir string) error {
	wrapperFile := filepath.Join(outputDir, "wrapper.go")
	
	content := fmt.Sprintf(`// Code generated by tools/codegen/generate.go; DO NOT EDIT.

package %s

import (
	"context"
	"net/http"
	
	"github.com/jontk/slurm-client"
	"github.com/jontk/slurm-client/internal/factory"
)

// Client implements the SlurmClient interface for API version %s
type Client struct {
	apiClient *ClientWithResponses
	config    *factory.ClientConfig
}

// NewClient creates a new %s client
func NewClient(config *factory.ClientConfig) (*Client, error) {
	// Create HTTP client with authentication
	httpClient := config.HTTPClient
	if httpClient == nil {
		httpClient = &http.Client{}
	}
	
	// Create oapi-codegen client
	apiClient, err := NewClientWithResponses(config.BaseURL, WithHTTPClient(httpClient))
	if err != nil {
		return nil, err
	}
	
	return &Client{
		apiClient: apiClient,
		config:    config,
	}, nil
}

// Version returns the API version
func (c *Client) Version() string {
	return "%s"
}

// Jobs returns the JobManager
func (c *Client) Jobs() slurm.JobManager {
	return &JobManager{client: c}
}

// Nodes returns the NodeManager  
func (c *Client) Nodes() slurm.NodeManager {
	return &NodeManager{client: c}
}

// Partitions returns the PartitionManager
func (c *Client) Partitions() slurm.PartitionManager {
	return &PartitionManager{client: c}
}

// Info returns the InfoManager
func (c *Client) Info() slurm.InfoManager {
	return &InfoManager{client: c}
}

// Close closes the client
func (c *Client) Close() error {
	// No resources to close for HTTP client
	return nil
}
`, normalizeVersion(version), version, version, version)
	
	return os.WriteFile(wrapperFile, []byte(content), 0644)
}

func normalizeVersion(version string) string {
	// Convert v0.0.42 to v0_0_42 for package names
	if len(version) > 0 && version[0] == 'v' {
		version = version[1:]
	}
	
	result := "v"
	for _, char := range version {
		if char == '.' {
			result += "_"
		} else {
			result += string(char)
		}
	}
	
	return result
}