// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v0_0_40

import (
	api "github.com/jontk/slurm-client/api"
	v0040 "github.com/jontk/slurm-client/internal/openapi/v0_0_40"
)

type AccountConverterGoverterImpl struct{}

func (c *AccountConverterGoverterImpl) ConvertAPIAccountToCommon(source v0040.V0040Account) *api.Account {
	var apiAccount api.Account
	apiAccount.Associations = ConvertAssocShortSlice(source.Associations)
	apiAccount.Coordinators = ConvertCoordSlice(source.Coordinators)
	apiAccount.Description = source.Description
	apiAccount.Flags = ConvertAccountFlags(source.Flags)
	apiAccount.Name = source.Name
	apiAccount.Organization = source.Organization
	return &apiAccount
}
func (c *AccountConverterGoverterImpl) ConvertCommonAccountCreateToAPI(source *api.AccountCreate) *v0040.V0040Account {
	var pV0_0_40V0040Account *v0040.V0040Account
	if source != nil {
		var v0_0_40V0040Account v0040.V0040Account
		v0_0_40V0040Account.Coordinators = ConvertCoordNamesToSlice((*source).Coordinators)
		v0_0_40V0040Account.Description = (*source).Description
		v0_0_40V0040Account.Name = (*source).Name
		v0_0_40V0040Account.Organization = (*source).Organization
		pV0_0_40V0040Account = &v0_0_40V0040Account
	}
	return pV0_0_40V0040Account
}
