// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v0_0_40

import (
	api "github.com/jontk/slurm-client/api"
	v0040 "github.com/jontk/slurm-client/internal/openapi/v0_0_40"
)

type QoSConverterGoverterImpl struct{}

func (c *QoSConverterGoverterImpl) ConvertAPIQoSToCommon(source v0040.V0040Qos) *api.QoS {
	var apiQoS api.QoS
	if source.Description != nil {
		xstring := *source.Description
		apiQoS.Description = &xstring
	}
	apiQoS.Flags = ConvertQoSFlags(source.Flags)
	if source.Id != nil {
		xint32 := *source.Id
		apiQoS.ID = &xint32
	}
	apiQoS.Limits = ConvertQoSLimits(source.Limits)
	if source.Name != nil {
		xstring2 := *source.Name
		apiQoS.Name = &xstring2
	}
	apiQoS.Preempt = ConvertQoSPreempt(source.Preempt)
	apiQoS.Priority = ConvertUint32NoVal(source.Priority)
	apiQoS.UsageFactor = ConvertFloat64NoVal(source.UsageFactor)
	apiQoS.UsageThreshold = ConvertFloat64NoVal(source.UsageThreshold)
	return &apiQoS
}
