// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v0_0_43

import (
	api "github.com/jontk/slurm-client/api"
	v0043 "github.com/jontk/slurm-client/internal/openapi/v0_0_43"
)

type AccountConverterGoverterImpl struct{}

func (c *AccountConverterGoverterImpl) ConvertAPIAccountToCommon(source v0043.V0043Account) *api.Account {
	var apiAccount api.Account
	apiAccount.Associations = ConvertAssocShortSlice(source.Associations)
	apiAccount.Coordinators = ConvertCoordSlice(source.Coordinators)
	apiAccount.Description = source.Description
	apiAccount.Flags = ConvertAccountFlags(source.Flags)
	apiAccount.Name = source.Name
	apiAccount.Organization = source.Organization
	return &apiAccount
}
func (c *AccountConverterGoverterImpl) ConvertCommonAccountCreateToAPI(source *api.AccountCreate) *v0043.V0043Account {
	var pV0_0_43V0043Account *v0043.V0043Account
	if source != nil {
		var v0_0_43V0043Account v0043.V0043Account
		v0_0_43V0043Account.Coordinators = ConvertCoordNamesToSlice((*source).Coordinators)
		v0_0_43V0043Account.Description = (*source).Description
		v0_0_43V0043Account.Name = (*source).Name
		v0_0_43V0043Account.Organization = (*source).Organization
		pV0_0_43V0043Account = &v0_0_43V0043Account
	}
	return pV0_0_43V0043Account
}
