// Code generated by generate_adapters.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0

package v0_0_43

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	types "github.com/jontk/slurm-client/api"
	api "github.com/jontk/slurm-client/internal/openapi/v0_0_43"
)

func TestNewAssociationAdapter(t *testing.T) {
	client := &api.ClientWithResponses{}
	adapter := NewAssociationAdapter(client)
	require.NotNil(t, adapter)
}

func TestAssociationAdapter_ValidateContext(t *testing.T) {
	adapter := NewAssociationAdapter(&api.ClientWithResponses{})

	// Test nil context
	//lint:ignore SA1012 intentionally testing nil context validation
	err := adapter.ValidateContext(nil)
	assert.Error(t, err)

	// Test valid context
	err = adapter.ValidateContext(context.Background())
	assert.NoError(t, err)
}

func TestAssociationAdapter_List_NilContext(t *testing.T) {
	adapter := NewAssociationAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.List(nil, nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestAssociationAdapter_List_ClientNotInitialized(t *testing.T) {
	adapter := NewAssociationAdapter(nil)

	result, err := adapter.List(context.Background(), nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestAssociationAdapter_Get_NilContext(t *testing.T) {
	adapter := NewAssociationAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.Get(nil, "test-association")
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestAssociationAdapter_Get_EmptyIdentifier(t *testing.T) {
	adapter := NewAssociationAdapter(&api.ClientWithResponses{})

	result, err := adapter.Get(context.Background(), "")
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestAssociationAdapter_Get_ClientNotInitialized(t *testing.T) {
	adapter := NewAssociationAdapter(nil)

	result, err := adapter.Get(context.Background(), "test-association")
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestAssociationAdapter_Create_NilContext(t *testing.T) {
	adapter := NewAssociationAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	result, err := adapter.Create(nil, &types.AssociationCreate{})
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestAssociationAdapter_Create_NilInput(t *testing.T) {
	adapter := NewAssociationAdapter(&api.ClientWithResponses{})

	result, err := adapter.Create(context.Background(), nil)
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestAssociationAdapter_Create_ClientNotInitialized(t *testing.T) {
	adapter := NewAssociationAdapter(nil)

	result, err := adapter.Create(context.Background(), &types.AssociationCreate{})
	assert.Nil(t, result)
	assert.Error(t, err)
}

func TestAssociationAdapter_Update_NilContext(t *testing.T) {
	adapter := NewAssociationAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	err := adapter.Update(nil, "test-association", &types.AssociationUpdate{})
	assert.Error(t, err)
}

func TestAssociationAdapter_Update_NilInput(t *testing.T) {
	adapter := NewAssociationAdapter(&api.ClientWithResponses{})

	err := adapter.Update(context.Background(), "test-association", nil)
	assert.Error(t, err)
}

func TestAssociationAdapter_Update_ClientNotInitialized(t *testing.T) {
	adapter := NewAssociationAdapter(nil)

	err := adapter.Update(context.Background(), "test-association", &types.AssociationUpdate{})
	assert.Error(t, err)
}

func TestAssociationAdapter_Delete_NilContext(t *testing.T) {
	adapter := NewAssociationAdapter(&api.ClientWithResponses{})

	//lint:ignore SA1012 intentionally testing nil context
	err := adapter.Delete(nil, "test-association")
	assert.Error(t, err)
}

func TestAssociationAdapter_Delete_EmptyIdentifier(t *testing.T) {
	adapter := NewAssociationAdapter(&api.ClientWithResponses{})

	err := adapter.Delete(context.Background(), "")
	assert.Error(t, err)
}

func TestAssociationAdapter_Delete_ClientNotInitialized(t *testing.T) {
	adapter := NewAssociationAdapter(nil)

	err := adapter.Delete(context.Background(), "test-association")
	assert.Error(t, err)
}

func TestAssociationAdapter_ReadConverter(t *testing.T) {
	adapter := NewAssociationAdapter(&api.ClientWithResponses{})

	// Create test API object with known values
	testID := int32(123)
	testAccount := "test-account"
	testCluster := "test-cluster"
	testUser := "test-user"
	apiObj := api.V0043Assoc{
		Id:      &testID,
		Account: &testAccount,
		Cluster: &testCluster,
		User:    testUser,
	}

	// Convert API → Common
	commonObj := adapter.convertAPIAssociationToCommon(apiObj)
	require.NotNil(t, commonObj)

	// Verify field values were correctly converted
	if commonObj.ID != nil {
		assert.Equal(t, testID, *commonObj.ID)
	}
	if commonObj.Account != nil {
		assert.Equal(t, testAccount, *commonObj.Account)
	}
	if commonObj.Cluster != nil {
		assert.Equal(t, testCluster, *commonObj.Cluster)
	}
	assert.Equal(t, testUser, commonObj.User)
}

func TestAssociationAdapter_CreateConverter(t *testing.T) {
	adapter := NewAssociationAdapter(&api.ClientWithResponses{})

	// Create test input with known values
	testAccount := "test-account"
	input := &types.AssociationCreate{
		Account: testAccount,
	}

	// Convert Common → API
	apiObj := adapter.convertCommonAssociationCreateToAPI(input)
	require.NotNil(t, apiObj)
}

func TestAssociationAdapter_UpdateConverter(t *testing.T) {
	adapter := NewAssociationAdapter(&api.ClientWithResponses{})

	// Create test input with known values
	testComment := "test comment"
	input := &types.AssociationUpdate{
		Comment: &testComment,
	}

	// Convert Common → API
	apiObj := adapter.convertCommonAssociationUpdateToAPI(input)
	require.NotNil(t, apiObj)
}

func TestAssociationAdapter_ValidateCreate(t *testing.T) {
	adapter := NewAssociationAdapter(&api.ClientWithResponses{})

	t.Run("nil input returns error", func(t *testing.T) {
		err := adapter.ValidateAssociationCreate(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "association creation data is required")
	})

	t.Run("missing Account returns error", func(t *testing.T) {
		input := &types.AssociationCreate{User: "test"}
		err := adapter.ValidateAssociationCreate(input)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "account is required")
	})

	t.Run("missing User returns error", func(t *testing.T) {
		input := &types.AssociationCreate{Account: "test"}
		err := adapter.ValidateAssociationCreate(input)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "user is required")
	})

	t.Run("valid input passes", func(t *testing.T) {
		input := &types.AssociationCreate{Account: "test", User: "test"}
		err := adapter.ValidateAssociationCreate(input)
		require.NoError(t, err)
	})
}

func TestAssociationAdapter_ValidateUpdate(t *testing.T) {
	adapter := NewAssociationAdapter(&api.ClientWithResponses{})

	t.Run("nil input returns error", func(t *testing.T) {
		err := adapter.validateAssociationUpdate(nil)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "association update data is required")
	})

	t.Run("empty fields returns error", func(t *testing.T) {
		input := &types.AssociationUpdate{}
		err := adapter.validateAssociationUpdate(input)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "at least one field must be provided for update")
	})

	t.Run("valid input passes", func(t *testing.T) {
		input := &types.AssociationUpdate{DefaultQoS: ptrString("test")}
		err := adapter.validateAssociationUpdate(input)
		require.NoError(t, err)
	})
}
