// Code generated by generate_adapters.go. DO NOT EDIT.
// SPDX-FileCopyrightText: 2025 Jon Thor Kristinsson
// SPDX-License-Identifier: Apache-2.0
package v0_0_43

import (
	types "github.com/jontk/slurm-client/api"
	"github.com/jontk/slurm-client/pkg/errors"
)

// ValidatePartitionCreate validates partition create data
func (a *PartitionAdapter) ValidatePartitionCreate(create *types.PartitionCreate) error {
	if create == nil {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "partition creation data is required", "create", nil, nil)
	}
	if create.Name == "" {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "partition name is required", "name", nil, nil)
	}
	return nil
}

// validatePartitionUpdate validates partition update data
func (a *PartitionAdapter) validatePartitionUpdate(update *types.PartitionUpdate) error {
	if update == nil {
		return errors.NewValidationError(errors.ErrorCodeValidationFailed, "partition update data is required", "update", nil, nil)
	}
	return nil
}
