// Code generated by tools/codegen/generate.go; DO NOT EDIT.

package v0_0_42

import (
	"context"
	
	"github.com/jontk/slurm-client/internal/interfaces"
)

// JobManager implements the JobManager interface for API version v0.0.42
type JobManager struct {
	client *WrapperClient
	impl   *JobManagerImpl
}

// List jobs with optional filtering
func (m *JobManager) List(ctx context.Context, opts *interfaces.ListJobsOptions) (*interfaces.JobList, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.List(ctx, opts)
}

// Get retrieves a specific job by ID
func (m *JobManager) Get(ctx context.Context, jobID string) (*interfaces.Job, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.Get(ctx, jobID)
}

// Submit submits a new job
func (m *JobManager) Submit(ctx context.Context, job *interfaces.JobSubmission) (*interfaces.JobSubmitResponse, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.Submit(ctx, job)
}

// Cancel cancels a job
func (m *JobManager) Cancel(ctx context.Context, jobID string) error {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.Cancel(ctx, jobID)
}

// Update updates job properties
func (m *JobManager) Update(ctx context.Context, jobID string, update *interfaces.JobUpdate) error {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.Update(ctx, jobID, update)
}

// Steps retrieves job steps for a job
func (m *JobManager) Steps(ctx context.Context, jobID string) (*interfaces.JobStepList, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.Steps(ctx, jobID)
}

// Watch provides real-time job updates
func (m *JobManager) Watch(ctx context.Context, opts *interfaces.WatchJobsOptions) (<-chan interfaces.JobEvent, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.Watch(ctx, opts)
}

// GetJobUtilization retrieves comprehensive resource utilization metrics for a job
func (m *JobManager) GetJobUtilization(ctx context.Context, jobID string) (*interfaces.JobUtilization, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetJobUtilization(ctx, jobID)
}

// GetJobEfficiency calculates efficiency metrics for a completed job
func (m *JobManager) GetJobEfficiency(ctx context.Context, jobID string) (*interfaces.ResourceUtilization, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetJobEfficiency(ctx, jobID)
}

// GetJobPerformance retrieves detailed performance metrics for a job
func (m *JobManager) GetJobPerformance(ctx context.Context, jobID string) (*interfaces.JobPerformance, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetJobPerformance(ctx, jobID)
}

// GetJobLiveMetrics retrieves real-time performance metrics for a running job
func (m *JobManager) GetJobLiveMetrics(ctx context.Context, jobID string) (*interfaces.JobLiveMetrics, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetJobLiveMetrics(ctx, jobID)
}

// WatchJobMetrics provides streaming performance updates for a running job
func (m *JobManager) WatchJobMetrics(ctx context.Context, jobID string, opts *interfaces.WatchMetricsOptions) (<-chan interfaces.JobMetricsEvent, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.WatchJobMetrics(ctx, jobID, opts)
}

// GetJobResourceTrends retrieves performance trends over specified time windows
func (m *JobManager) GetJobResourceTrends(ctx context.Context, jobID string, opts *interfaces.ResourceTrendsOptions) (*interfaces.JobResourceTrends, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetJobResourceTrends(ctx, jobID, opts)
}

// GetJobStepDetails retrieves detailed information about a specific job step
func (m *JobManager) GetJobStepDetails(ctx context.Context, jobID string, stepID string) (*interfaces.JobStepDetails, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetJobStepDetails(ctx, jobID, stepID)
}

// GetJobStepUtilization retrieves resource utilization metrics for a specific job step
func (m *JobManager) GetJobStepUtilization(ctx context.Context, jobID string, stepID string) (*interfaces.JobStepUtilization, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetJobStepUtilization(ctx, jobID, stepID)
}

// ListJobStepsWithMetrics retrieves all job steps with their performance metrics
func (m *JobManager) ListJobStepsWithMetrics(ctx context.Context, jobID string, opts *interfaces.ListJobStepsOptions) (*interfaces.JobStepMetricsList, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.ListJobStepsWithMetrics(ctx, jobID, opts)
}

// GetJobStepsFromAccounting retrieves job step data from SLURM's accounting database
func (m *JobManager) GetJobStepsFromAccounting(ctx context.Context, jobID string, opts *interfaces.AccountingQueryOptions) (*interfaces.AccountingJobSteps, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetJobStepsFromAccounting(ctx, jobID, opts)
}

// GetStepAccountingData retrieves detailed accounting information for a specific job step
func (m *JobManager) GetStepAccountingData(ctx context.Context, jobID string, stepID string) (*interfaces.StepAccountingRecord, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetStepAccountingData(ctx, jobID, stepID)
}

// GetJobStepAPIData integrates with SLURM's native job step APIs for real-time data
func (m *JobManager) GetJobStepAPIData(ctx context.Context, jobID string, stepID string) (*interfaces.JobStepAPIData, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetJobStepAPIData(ctx, jobID, stepID)
}

// ListJobStepsFromSacct queries job steps using SLURM's sacct command integration
func (m *JobManager) ListJobStepsFromSacct(ctx context.Context, jobID string, opts *interfaces.SacctQueryOptions) (*interfaces.SacctJobStepData, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.ListJobStepsFromSacct(ctx, jobID, opts)
}

// GetJobCPUAnalytics retrieves detailed CPU performance metrics for a job
func (m *JobManager) GetJobCPUAnalytics(ctx context.Context, jobID string) (*interfaces.CPUAnalytics, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetJobCPUAnalytics(ctx, jobID)
}

// GetJobMemoryAnalytics retrieves detailed memory performance metrics for a job
func (m *JobManager) GetJobMemoryAnalytics(ctx context.Context, jobID string) (*interfaces.MemoryAnalytics, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetJobMemoryAnalytics(ctx, jobID)
}

// GetJobIOAnalytics retrieves detailed I/O performance metrics for a job
func (m *JobManager) GetJobIOAnalytics(ctx context.Context, jobID string) (*interfaces.IOAnalytics, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetJobIOAnalytics(ctx, jobID)
}

// GetJobComprehensiveAnalytics retrieves all performance metrics for a job
func (m *JobManager) GetJobComprehensiveAnalytics(ctx context.Context, jobID string) (*interfaces.JobComprehensiveAnalytics, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetJobComprehensiveAnalytics(ctx, jobID)
}

// GetJobPerformanceHistory retrieves historical performance data for a job
func (m *JobManager) GetJobPerformanceHistory(ctx context.Context, jobID string, opts *interfaces.PerformanceHistoryOptions) (*interfaces.JobPerformanceHistory, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetJobPerformanceHistory(ctx, jobID, opts)
}

// GetPerformanceTrends analyzes cluster-wide performance trends
func (m *JobManager) GetPerformanceTrends(ctx context.Context, opts *interfaces.TrendAnalysisOptions) (*interfaces.PerformanceTrends, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetPerformanceTrends(ctx, opts)
}

// GetUserEfficiencyTrends tracks efficiency trends for a specific user
func (m *JobManager) GetUserEfficiencyTrends(ctx context.Context, userID string, opts *interfaces.EfficiencyTrendOptions) (*interfaces.UserEfficiencyTrends, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetUserEfficiencyTrends(ctx, userID, opts)
}

// AnalyzeBatchJobs performs bulk analysis on a collection of jobs
func (m *JobManager) AnalyzeBatchJobs(ctx context.Context, jobIDs []string, opts *interfaces.BatchAnalysisOptions) (*interfaces.BatchJobAnalysis, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.AnalyzeBatchJobs(ctx, jobIDs, opts)
}

// GetWorkflowPerformance analyzes performance of multi-job workflows
func (m *JobManager) GetWorkflowPerformance(ctx context.Context, workflowID string, opts *interfaces.WorkflowAnalysisOptions) (*interfaces.WorkflowPerformance, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetWorkflowPerformance(ctx, workflowID, opts)
}

// GenerateEfficiencyReport creates comprehensive efficiency reports
func (m *JobManager) GenerateEfficiencyReport(ctx context.Context, opts *interfaces.ReportOptions) (*interfaces.EfficiencyReport, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GenerateEfficiencyReport(ctx, opts)
}

// NodeManager implements the NodeManager interface for API version v0.0.42
type NodeManager struct {
	client *WrapperClient
	impl   *NodeManagerImpl
}

// List nodes with optional filtering
func (m *NodeManager) List(ctx context.Context, opts *interfaces.ListNodesOptions) (*interfaces.NodeList, error) {
	if m.impl == nil {
		m.impl = NewNodeManagerImpl(m.client)
	}
	return m.impl.List(ctx, opts)
}

// Get retrieves a specific node by name
func (m *NodeManager) Get(ctx context.Context, nodeName string) (*interfaces.Node, error) {
	if m.impl == nil {
		m.impl = NewNodeManagerImpl(m.client)
	}
	return m.impl.Get(ctx, nodeName)
}

// Update updates node properties
func (m *NodeManager) Update(ctx context.Context, nodeName string, update *interfaces.NodeUpdate) error {
	if m.impl == nil {
		m.impl = NewNodeManagerImpl(m.client)
	}
	return m.impl.Update(ctx, nodeName, update)
}

// Watch provides real-time node updates
func (m *NodeManager) Watch(ctx context.Context, opts *interfaces.WatchNodesOptions) (<-chan interfaces.NodeEvent, error) {
	if m.impl == nil {
		m.impl = NewNodeManagerImpl(m.client)
	}
	return m.impl.Watch(ctx, opts)
}

// PartitionManager implements the PartitionManager interface for API version v0.0.42
type PartitionManager struct {
	client *WrapperClient
	impl   *PartitionManagerImpl
}

// List partitions with optional filtering
func (m *PartitionManager) List(ctx context.Context, opts *interfaces.ListPartitionsOptions) (*interfaces.PartitionList, error) {
	if m.impl == nil {
		m.impl = NewPartitionManagerImpl(m.client)
	}
	return m.impl.List(ctx, opts)
}

// Get retrieves a specific partition by name
func (m *PartitionManager) Get(ctx context.Context, partitionName string) (*interfaces.Partition, error) {
	if m.impl == nil {
		m.impl = NewPartitionManagerImpl(m.client)
	}
	return m.impl.Get(ctx, partitionName)
}

// Update updates partition properties
func (m *PartitionManager) Update(ctx context.Context, partitionName string, update *interfaces.PartitionUpdate) error {
	if m.impl == nil {
		m.impl = NewPartitionManagerImpl(m.client)
	}
	return m.impl.Update(ctx, partitionName, update)
}

// Watch provides real-time partition updates
func (m *PartitionManager) Watch(ctx context.Context, opts *interfaces.WatchPartitionsOptions) (<-chan interfaces.PartitionEvent, error) {
	if m.impl == nil {
		m.impl = NewPartitionManagerImpl(m.client)
	}
	return m.impl.Watch(ctx, opts)
}

// InfoManager implements the InfoManager interface for API version v0.0.42
type InfoManager struct {
	client *WrapperClient
	impl   *InfoManagerImpl
}

// Get retrieves cluster information
func (m *InfoManager) Get(ctx context.Context) (*interfaces.ClusterInfo, error) {
	if m.impl == nil {
		m.impl = NewInfoManagerImpl(m.client)
	}
	return m.impl.Get(ctx)
}

// Ping tests connectivity to the cluster
func (m *InfoManager) Ping(ctx context.Context) error {
	if m.impl == nil {
		m.impl = NewInfoManagerImpl(m.client)
	}
	return m.impl.Ping(ctx)
}

// Stats retrieves cluster statistics
func (m *InfoManager) Stats(ctx context.Context) (*interfaces.ClusterStats, error) {
	if m.impl == nil {
		m.impl = NewInfoManagerImpl(m.client)
	}
	return m.impl.Stats(ctx)
}

// Version retrieves API version information
func (m *InfoManager) Version(ctx context.Context) (*interfaces.APIVersion, error) {
	if m.impl == nil {
		m.impl = NewInfoManagerImpl(m.client)
	}
	return m.impl.Version(ctx)
}








