// Code generated by tools/codegen/generate.go; DO NOT EDIT.

package v0_0_42

import (
	"context"
	"net/http"
	"time"
)

// ClientConfig holds configuration for the API client
type ClientConfig struct {
	BaseURL     string
	HTTPClient  *http.Client
	APIKey      string
	Debug       bool
}

// WrapperClient wraps the generated client for version v0.0.42
type WrapperClient struct {
	apiClient *ClientWithResponses
	config    *ClientConfig
}

// NewWrapperClient creates a new v0.0.42 wrapper client
func NewWrapperClient(config *ClientConfig) (*WrapperClient, error) {
	// Create HTTP client with authentication
	httpClient := config.HTTPClient
	if httpClient == nil {
		httpClient = &http.Client{}
	}
	
	// Create oapi-codegen client
	apiClient, err := NewClientWithResponses(config.BaseURL, WithHTTPClient(httpClient))
	if err != nil {
		return nil, err
	}
	
	return &WrapperClient{
		apiClient: apiClient,
		config:    config,
	}, nil
}

// Version returns the API version
func (c *WrapperClient) Version() string {
	return "v0.0.42"
}

// Jobs returns the JobManager
func (c *WrapperClient) Jobs() *JobManager {
	return &JobManager{client: c}
}

// Nodes returns the NodeManager  
func (c *WrapperClient) Nodes() *NodeManager {
	return &NodeManager{client: c}
}

// Partitions returns the PartitionManager
func (c *WrapperClient) Partitions() *PartitionManager {
	return &PartitionManager{client: c}
}

// Info returns the InfoManager
func (c *WrapperClient) Info() *InfoManager {
	return &InfoManager{client: c}
}

// Close closes the client
func (c *WrapperClient) Close() error {
	// No resources to close for HTTP client
	return nil
}
