// Code generated by tools/codegen/generate.go; DO NOT EDIT.

package v0_0_42

import (
	"net/http"
	
	"github.com/jontk/slurm-client"
	"github.com/jontk/slurm-client/pkg/auth"
	"github.com/jontk/slurm-client/pkg/config"
	"github.com/jontk/slurm-client/pkg/retry"
)

// ClientConfig represents configuration for the v0.0.42 client
type ClientConfig struct {
	BaseURL     string
	HTTPClient  *http.Client
	Auth        auth.Provider
	RetryPolicy retry.Policy
	Config      *config.Config
}

// Client implements the SlurmClient interface for API version v0.0.42
type Client struct {
	apiClient *ClientWithResponses
	config    *ClientConfig
}

// NewClient creates a new v0.0.42 client
func NewClient(config *ClientConfig) (*Client, error) {
	// Create HTTP client with authentication
	httpClient := config.HTTPClient
	if httpClient == nil {
		httpClient = &http.Client{}
	}
	
	// Create oapi-codegen client
	apiClient, err := NewClientWithResponses(config.BaseURL, WithHTTPClient(httpClient))
	if err != nil {
		return nil, err
	}
	
	return &Client{
		apiClient: apiClient,
		config:    config,
	}, nil
}

// Version returns the API version
func (c *Client) Version() string {
	return "v0.0.42"
}

// Jobs returns the JobManager
func (c *Client) Jobs() slurm.JobManager {
	return NewJobManager(c)
}

// Nodes returns the NodeManager  
func (c *Client) Nodes() slurm.NodeManager {
	return NewNodeManager(c)
}

// Partitions returns the PartitionManager
func (c *Client) Partitions() slurm.PartitionManager {
	return NewPartitionManager(c)
}

// Info returns the InfoManager
func (c *Client) Info() slurm.InfoManager {
	return NewInfoManager(c)
}

// Close closes the client
func (c *Client) Close() error {
	// No resources to close for HTTP client
	return nil
}
