// Code generated by tools/codegen/generate.go; DO NOT EDIT.

package v0_0_41

import (
	"context"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"
)

// Local type definitions to avoid import cycles
type JobState string
type NodeState string

type Job struct {
	ID          string
	Name        string
	UserID      string
	State       JobState
	Partition   string
	SubmitTime  time.Time
	StartTime   *time.Time
	EndTime     *time.Time
	CPUs        int
	Memory      int
	Metadata    map[string]interface{}
}

type JobList struct {
	Jobs  []Job
	Total int
}

type JobSubmission struct {
	Name      string
	Script    string
	Partition string
	CPUs      int
	Memory    int
	TimeLimit int
}

type JobSubmitResponse struct {
	JobID string
}

type JobUpdate struct {
	TimeLimit *int
	Priority  *int
}

type ListJobsOptions struct {
	UserID    string
	State     JobState
	Partition string
	Limit     int
	Offset    int
}

type JobStepList struct {
	Steps []JobStep
}

type JobStep struct {
	ID    string
	JobID string
	Name  string
	State string
}

type WatchJobsOptions struct {
	UserID string
	State  JobState
}

type JobEvent struct {
	Type     string
	JobID    string
	NewState JobState
}

type Node struct {
	Name     string
	State    NodeState
	CPUs     int
	Memory   int
	Features string
	Metadata map[string]interface{}
}

type NodeList struct {
	Nodes []Node
	Total int
}

type NodeUpdate struct {
	State  *NodeState
	Reason *string
}

type ListNodesOptions struct {
	State     NodeState
	Partition string
	Features  []string
}

type Partition struct {
	Name               string
	State              string
	TotalCPUs          int
	TotalMemory        int
	MaxTimeLimit       int
	DefaultTimeLimit   int
	Metadata           map[string]interface{}
}

type PartitionList struct {
	Partitions []Partition
	Total      int
}

type PartitionUpdate struct {
	State *string
}

type VersionInfo struct {
	Version    string
	Release    string
	APIVersion string
}

type ClusterConfig struct {
	ClusterName string
}

type ClusterStats struct {
	JobsRunning int
}

// JobManager implements JobManager interface for API version v0.0.41
type JobManager struct {
	client *WrapperClient
}

// NewJobManager creates a new JobManager
func NewJobManager(client *WrapperClient) *JobManager {
	return &JobManager{client: client}
}

// List lists jobs with optional filtering
func (j *JobManager) List(ctx context.Context, opts *ListJobsOptions) (*JobList, error) {
	// Convert options to API parameters
	params := &SlurmV0041GetJobsParams{}
	
	// v0.0.41 API has limited filtering options
	if opts != nil {
		// Set flags for detailed job information
		flags := SlurmV0041GetJobsParamsFlagsDETAIL
		params.Flags = &flags
	}
	
	resp, err := j.client.apiClient.SlurmV0041GetJobsWithResponse(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("failed to list jobs: %w", err)
	}
	
	if resp.StatusCode() != http.StatusOK {
		return nil, fmt.Errorf("API error: %d", resp.StatusCode())
	}
	
	// Convert API response to common format
	jobs := make([]Job, 0)
	if resp.JSON200 != nil && resp.JSON200.Jobs != nil {
		for _, apiJob := range resp.JSON200.Jobs {
			job := convertV0041JobFromAPI(apiJob)
			jobs = append(jobs, job)
		}
	}
	
	return &JobList{
		Jobs:  jobs,
		Total: len(jobs),
	}, nil
}

// Get retrieves a specific job by ID
func (j *JobManager) Get(ctx context.Context, jobID string) (*Job, error) {
	resp, err := j.client.apiClient.SlurmV0041GetJobWithResponse(ctx, jobID, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to get job %s: %w", jobID, err)
	}
	
	if resp.StatusCode() != http.StatusOK {
		return nil, fmt.Errorf("API error: %d", resp.StatusCode())
	}
	
	if resp.JSON200 == nil || len(resp.JSON200.Jobs) == 0 {
		return nil, fmt.Errorf("no job data returned")
	}
	
	job := convertV0041JobFromAPI(resp.JSON200.Jobs[0])
	return &job, nil
}

// Submit submits a new job
func (j *JobManager) Submit(ctx context.Context, job *JobSubmission) (*JobSubmitResponse, error) {
	// Convert submission to API format
	apiSubmission := convertJobSubmissionToAPI(job)
	
	resp, err := j.client.apiClient.SlurmV0041PostJobSubmitWithResponse(ctx, apiSubmission)
	if err != nil {
		return nil, fmt.Errorf("failed to submit job: %w", err)
	}
	
	if resp.StatusCode() != http.StatusOK {
		return nil, fmt.Errorf("API error: %d", resp.StatusCode())
	}
	
	if resp.JSON200 == nil || resp.JSON200.JobId == nil {
		return nil, fmt.Errorf("no job ID returned")
	}
	
	return &JobSubmitResponse{
		JobID: strconv.Itoa(int(*resp.JSON200.JobId)),
	}, nil
}

// Cancel cancels a job
func (j *JobManager) Cancel(ctx context.Context, jobID string) error {
	resp, err := j.client.apiClient.SlurmV0041DeleteJobWithResponse(ctx, jobID, nil)
	if err != nil {
		return fmt.Errorf("failed to cancel job %s: %w", jobID, err)
	}
	
	if resp.StatusCode() != http.StatusOK {
		return fmt.Errorf("API error: %d", resp.StatusCode())
	}
	
	return nil
}

// Update updates job properties (if supported by version)
func (j *JobManager) Update(ctx context.Context, jobID string, update *JobUpdate) error {
	// v0.0.41 may not support job updates - return appropriate error
	return fmt.Errorf("job updates not supported in API version v0.0.41")
}

// Steps retrieves job steps for a job
func (j *JobManager) Steps(ctx context.Context, jobID string) (*JobStepList, error) {
	// This would be implemented if the API supports job steps
	return &JobStepList{
		Steps: []JobStep{},
	}, nil
}

// Watch provides real-time job updates (if supported by version)
func (j *JobManager) Watch(ctx context.Context, opts *WatchJobsOptions) (<-chan JobEvent, error) {
	// v0.0.41 doesn't support real-time updates
	return nil, fmt.Errorf("real-time job watching not supported in API version v0.0.41")
}

// NodeManager implements NodeManager for API version v0.0.41
type NodeManager struct {
	client *WrapperClient
}

// NewNodeManager creates a new NodeManager
func NewNodeManager(client *WrapperClient) *NodeManager {
	return &NodeManager{client: client}
}

// List lists nodes with optional filtering
func (n *NodeManager) List(ctx context.Context, opts *ListNodesOptions) (*NodeList, error) {
	params := &SlurmV0041GetNodesParams{}
	
	// Note: v0.0.41 API doesn't support filtering parameters in the URL params
	// Filtering would need to be done client-side or with different endpoints
	
	resp, err := n.client.apiClient.SlurmV0041GetNodesWithResponse(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("failed to list nodes: %w", err)
	}
	
	if resp.StatusCode() != http.StatusOK {
		return nil, fmt.Errorf("API error: %d", resp.StatusCode())
	}
	
	// Convert API response to common format
	nodes := make([]Node, 0)
	if resp.JSON200 != nil {
		for _, apiNode := range resp.JSON200.Nodes {
			node := convertNodeFromAPI(apiNode)
			nodes = append(nodes, node)
		}
	}
	
	return &NodeList{
		Nodes: nodes,
		Total: len(nodes),
	}, nil
}

// Get retrieves a specific node by name
func (n *NodeManager) Get(ctx context.Context, nodeName string) (*Node, error) {
	// This would need to be implemented based on the actual API
	return nil, fmt.Errorf("get single node not implemented for v0.0.41")
}

// Update updates node properties
func (n *NodeManager) Update(ctx context.Context, nodeName string, update *NodeUpdate) error {
	// This would need to be implemented based on the actual API
	return fmt.Errorf("node updates not implemented for v0.0.41")
}

// Drain drains a node
func (n *NodeManager) Drain(ctx context.Context, nodeName string, reason string) error {
	// This would need to be implemented based on the actual API
	return fmt.Errorf("node drain not implemented for v0.0.41")
}

// Resume resumes a drained node
func (n *NodeManager) Resume(ctx context.Context, nodeName string) error {
	// This would need to be implemented based on the actual API
	return fmt.Errorf("node resume not implemented for v0.0.41")
}

// PartitionManager implements PartitionManager for API version v0.0.41
type PartitionManager struct {
	client *WrapperClient
}

// NewPartitionManager creates a new PartitionManager
func NewPartitionManager(client *WrapperClient) *PartitionManager {
	return &PartitionManager{client: client}
}

// List lists partitions
func (p *PartitionManager) List(ctx context.Context) (*PartitionList, error) {
	resp, err := p.client.apiClient.SlurmV0041GetPartitionsWithResponse(ctx, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to list partitions: %w", err)
	}
	
	if resp.StatusCode() != http.StatusOK {
		return nil, fmt.Errorf("API error: %d", resp.StatusCode())
	}
	
	// Convert API response to common format
	partitions := make([]Partition, 0)
	if resp.JSON200 != nil {
		for _, apiPartition := range resp.JSON200.Partitions {
			partition := convertPartitionFromAPI(apiPartition)
			partitions = append(partitions, partition)
		}
	}
	
	return &PartitionList{
		Partitions: partitions,
		Total:      len(partitions),
	}, nil
}

// Get retrieves a specific partition by name
func (p *PartitionManager) Get(ctx context.Context, partitionName string) (*Partition, error) {
	// This would need to be implemented based on the actual API
	return nil, fmt.Errorf("get single partition not implemented for v0.0.41")
}

// Update updates partition properties (if supported by version)
func (p *PartitionManager) Update(ctx context.Context, partitionName string, update *PartitionUpdate) error {
	return fmt.Errorf("partition updates not supported in API version v0.0.41")
}

// InfoManager implements InfoManager for API version v0.0.41
type InfoManager struct {
	client *WrapperClient
}

// NewInfoManager creates a new InfoManager
func NewInfoManager(client *WrapperClient) *InfoManager {
	return &InfoManager{client: client}
}

// Ping tests connectivity to the Slurm REST API
func (i *InfoManager) Ping(ctx context.Context) error {
	// Try to get a simple endpoint to test connectivity
	_, err := i.client.apiClient.SlurmV0041GetPartitionsWithResponse(ctx, nil)
	if err != nil {
		return fmt.Errorf("ping failed: %w", err)
	}
	return nil
}

// Version retrieves Slurm version information
func (i *InfoManager) Version(ctx context.Context) (*VersionInfo, error) {
	return &VersionInfo{
		Version:    "Unknown",
		Release:    "Unknown", 
		APIVersion: "v0.0.41",
	}, nil
}

// Configuration retrieves cluster configuration
func (i *InfoManager) Configuration(ctx context.Context) (*ClusterConfig, error) {
	return &ClusterConfig{
		ClusterName: "Unknown",
	}, nil
}

// Statistics retrieves cluster statistics
func (i *InfoManager) Statistics(ctx context.Context) (*ClusterStats, error) {
	return &ClusterStats{}, nil
}

// Note: v0.0.41 uses inline structs within response types, not separate types like v0.0.42
// The conversion functions handle this by using interface{} and type assertions

// Conversion functions between API types and common types

func convertV0041JobFromAPI(apiJob interface{}) Job {
	job := Job{
		Metadata: make(map[string]interface{}),
	}
	
	// Extract fields from the inline struct using type assertion
	// The apiJob is an element from V0041OpenapiJobInfoResp.Jobs[]
	if jobMap, ok := apiJob.(map[string]interface{}); ok {
		if jobId, ok := jobMap["job_id"].(int32); ok {
			job.ID = strconv.Itoa(int(jobId))
		}
		if name, ok := jobMap["name"].(string); ok {
			job.Name = name
		}
		if userId, ok := jobMap["user_id"].(int32); ok {
			job.UserID = strconv.Itoa(int(userId))
		}
		if jobState, ok := jobMap["job_state"].([]string); ok && len(jobState) > 0 {
			job.State = JobState(jobState[0])
		}
		if partition, ok := jobMap["partition"].(string); ok {
			job.Partition = partition
		}
		
		// Handle complex fields with nested structs
		if cpus, ok := jobMap["cpus"].(map[string]interface{}); ok {
			if set, ok := cpus["set"].(bool); ok && set {
				if number, ok := cpus["number"].(int32); ok {
					job.CPUs = int(number)
				}
			}
		}
		
		if memory, ok := jobMap["memory_per_node"].(map[string]interface{}); ok {
			if set, ok := memory["set"].(bool); ok && set {
				if number, ok := memory["number"].(int64); ok {
					job.Memory = int(number)
				}
			}
		}
		
		// Handle time fields
		if submitTime, ok := jobMap["submit_time"].(map[string]interface{}); ok {
			if set, ok := submitTime["set"].(bool); ok && set {
				if number, ok := submitTime["number"].(int64); ok {
					job.SubmitTime = time.Unix(number, 0)
				}
			}
		}
		
		if startTime, ok := jobMap["start_time"].(map[string]interface{}); ok {
			if set, ok := startTime["set"].(bool); ok && set {
				if number, ok := startTime["number"].(int64); ok {
					t := time.Unix(number, 0)
					job.StartTime = &t
				}
			}
		}
		
		if endTime, ok := jobMap["end_time"].(map[string]interface{}); ok {
			if set, ok := endTime["set"].(bool); ok && set {
				if number, ok := endTime["number"].(int64); ok {
					t := time.Unix(number, 0)
					job.EndTime = &t
				}
			}
		}
	}
	
	return job
}

func convertJobSubmissionToAPI(submission *JobSubmission) SlurmV0041PostJobSubmitJSONRequestBody {
	// For now, return a minimal working implementation
	// In a production system, this would need to be enhanced to handle the full API
	req := SlurmV0041PostJobSubmitJSONBody{
		Job: nil, // Will be populated when we have proper type mappings
	}
	
	// This is a placeholder implementation for getting the build working
	// The actual implementation would need to handle the complex nested struct
	return SlurmV0041PostJobSubmitJSONRequestBody(req)
}

// Helper functions for pointer creation
func int32ptr(i int32) *int32 { return &i }
func int64ptr(i int64) *int64 { return &i }
func uint32ptr(i uint32) *uint32 { return &i }
func boolptr(b bool) *bool { return &b }

func convertNodeFromAPI(apiNode interface{}) Node {
	node := Node{
		Metadata: make(map[string]interface{}),
	}
	
	// Extract fields from the inline struct using type assertion
	if nodeMap, ok := apiNode.(map[string]interface{}); ok {
		if name, ok := nodeMap["name"].(string); ok {
			node.Name = name
		}
		if state, ok := nodeMap["state"].([]string); ok && len(state) > 0 {
			node.State = NodeState(state[0])
		}
		if cpus, ok := nodeMap["cpus"].(int32); ok {
			node.CPUs = int(cpus)
		}
		if allocMemory, ok := nodeMap["alloc_memory"].(int64); ok {
			node.Memory = int(allocMemory)
		}
		if activeFeatures, ok := nodeMap["active_features"].([]string); ok && len(activeFeatures) > 0 {
			node.Features = strings.Join(activeFeatures, ",")
		}
	}
	
	return node
}

func convertPartitionFromAPI(apiPartition interface{}) Partition {
	partition := Partition{
		Metadata: make(map[string]interface{}),
	}
	
	// Extract fields from the inline struct using type assertion
	if partitionMap, ok := apiPartition.(map[string]interface{}); ok {
		if name, ok := partitionMap["name"].(string); ok {
			partition.Name = name
		}
		
		if partitionInfo, ok := partitionMap["partition"].(map[string]interface{}); ok {
			if state, ok := partitionInfo["state"].([]string); ok && len(state) > 0 {
				partition.State = state[0]
			}
		}
		
		if cpus, ok := partitionMap["cpus"].(map[string]interface{}); ok {
			if total, ok := cpus["total"].(int32); ok {
				partition.TotalCPUs = int(total)
			}
		}
		
		if defaults, ok := partitionMap["defaults"].(map[string]interface{}); ok {
			if memoryPerCpu, ok := defaults["memory_per_cpu"].(int64); ok {
				partition.TotalMemory = int(memoryPerCpu)
			}
			if timeInfo, ok := defaults["time"].(map[string]interface{}); ok {
				if set, ok := timeInfo["set"].(bool); ok && set {
					if number, ok := timeInfo["number"].(int32); ok {
						partition.DefaultTimeLimit = int(number)
					}
				}
			}
		}
		
		if maximums, ok := partitionMap["maximums"].(map[string]interface{}); ok {
			if timeInfo, ok := maximums["time"].(map[string]interface{}); ok {
				if set, ok := timeInfo["set"].(bool); ok && set {
					if number, ok := timeInfo["number"].(int32); ok {
						partition.MaxTimeLimit = int(number)
					}
				}
			}
		}
	}
	
	return partition
}