// Code generated by tools/codegen/generate.go; DO NOT EDIT.

package v0_0_41

import (
	"context"
	"net/http"
	
	"github.com/jontk/slurm-client"
	"github.com/jontk/slurm-client/internal/factory"
)

// Client implements the SlurmClient interface for API version v0.0.41
type Client struct {
	apiClient *ClientWithResponses
	config    *factory.ClientConfig
}

// NewClient creates a new v0.0.41 client
func NewClient(config *factory.ClientConfig) (*Client, error) {
	// Create HTTP client with authentication
	httpClient := config.HTTPClient
	if httpClient == nil {
		httpClient = &http.Client{}
	}
	
	// Create oapi-codegen client
	apiClient, err := NewClientWithResponses(config.BaseURL, WithHTTPClient(httpClient))
	if err != nil {
		return nil, err
	}
	
	return &Client{
		apiClient: apiClient,
		config:    config,
	}, nil
}

// Version returns the API version
func (c *Client) Version() string {
	return "v0.0.41"
}

// Jobs returns the JobManager
func (c *Client) Jobs() slurm.JobManager {
	return &JobManager{client: c}
}

// Nodes returns the NodeManager  
func (c *Client) Nodes() slurm.NodeManager {
	return &NodeManager{client: c}
}

// Partitions returns the PartitionManager
func (c *Client) Partitions() slurm.PartitionManager {
	return &PartitionManager{client: c}
}

// Info returns the InfoManager
func (c *Client) Info() slurm.InfoManager {
	return &InfoManager{client: c}
}

// Close closes the client
func (c *Client) Close() error {
	// No resources to close for HTTP client
	return nil
}
