// Code generated by tools/codegen/generate.go; DO NOT EDIT.

package v0_0_43

import (
	"context"

	"github.com/jontk/slurm-client/internal/interfaces"
)

// JobManager implements the JobManager interface for API version v0.0.43
type JobManager struct {
	client *WrapperClient
	impl   *JobManagerImpl
}

// List jobs with optional filtering
func (m *JobManager) List(ctx context.Context, opts *interfaces.ListJobsOptions) (*interfaces.JobList, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.List(ctx, opts)
}

// Get retrieves a specific job by ID
func (m *JobManager) Get(ctx context.Context, jobID string) (*interfaces.Job, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.Get(ctx, jobID)
}

// Submit submits a new job
func (m *JobManager) Submit(ctx context.Context, job *interfaces.JobSubmission) (*interfaces.JobSubmitResponse, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.Submit(ctx, job)
}

// Cancel cancels a job
func (m *JobManager) Cancel(ctx context.Context, jobID string) error {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.Cancel(ctx, jobID)
}

// Update updates job properties
func (m *JobManager) Update(ctx context.Context, jobID string, update *interfaces.JobUpdate) error {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.Update(ctx, jobID, update)
}

// Steps retrieves job steps for a job
func (m *JobManager) Steps(ctx context.Context, jobID string) (*interfaces.JobStepList, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.Steps(ctx, jobID)
}

// Watch provides real-time job updates
func (m *JobManager) Watch(ctx context.Context, opts *interfaces.WatchJobsOptions) (<-chan interfaces.JobEvent, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.Watch(ctx, opts)
}

// GetJobUtilization retrieves comprehensive resource utilization metrics for a job
func (m *JobManager) GetJobUtilization(ctx context.Context, jobID string) (*interfaces.JobUtilization, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetJobUtilization(ctx, jobID)
}

// GetJobEfficiency calculates efficiency metrics for a completed job
func (m *JobManager) GetJobEfficiency(ctx context.Context, jobID string) (*interfaces.ResourceUtilization, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetJobEfficiency(ctx, jobID)
}

// GetJobPerformance retrieves detailed performance metrics for a job
func (m *JobManager) GetJobPerformance(ctx context.Context, jobID string) (*interfaces.JobPerformance, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetJobPerformance(ctx, jobID)
}

// GetJobLiveMetrics retrieves real-time performance metrics for a running job
func (m *JobManager) GetJobLiveMetrics(ctx context.Context, jobID string) (*interfaces.JobLiveMetrics, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetJobLiveMetrics(ctx, jobID)
}

// WatchJobMetrics provides streaming performance updates for a running job
func (m *JobManager) WatchJobMetrics(ctx context.Context, jobID string, opts *interfaces.WatchMetricsOptions) (<-chan interfaces.JobMetricsEvent, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.WatchJobMetrics(ctx, jobID, opts)
}

// GetJobResourceTrends retrieves performance trends over specified time windows
func (m *JobManager) GetJobResourceTrends(ctx context.Context, jobID string, opts *interfaces.ResourceTrendsOptions) (*interfaces.JobResourceTrends, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetJobResourceTrends(ctx, jobID, opts)
}

// GetJobStepDetails retrieves detailed information about a specific job step
func (m *JobManager) GetJobStepDetails(ctx context.Context, jobID string, stepID string) (*interfaces.JobStepDetails, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetJobStepDetails(ctx, jobID, stepID)
}

// GetJobStepUtilization retrieves resource utilization metrics for a specific job step
func (m *JobManager) GetJobStepUtilization(ctx context.Context, jobID string, stepID string) (*interfaces.JobStepUtilization, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.GetJobStepUtilization(ctx, jobID, stepID)
}

// ListJobStepsWithMetrics retrieves all job steps with their performance metrics
func (m *JobManager) ListJobStepsWithMetrics(ctx context.Context, jobID string, opts *interfaces.ListJobStepsOptions) (*interfaces.JobStepMetricsList, error) {
	if m.impl == nil {
		m.impl = NewJobManagerImpl(m.client)
	}
	return m.impl.ListJobStepsWithMetrics(ctx, jobID, opts)
}

// NodeManager implements the NodeManager interface for API version v0.0.43
type NodeManager struct {
	client *WrapperClient
	impl   *NodeManagerImpl
}

// List nodes with optional filtering
func (m *NodeManager) List(ctx context.Context, opts *interfaces.ListNodesOptions) (*interfaces.NodeList, error) {
	if m.impl == nil {
		m.impl = NewNodeManagerImpl(m.client)
	}
	return m.impl.List(ctx, opts)
}

// Get retrieves a specific node by name
func (m *NodeManager) Get(ctx context.Context, nodeName string) (*interfaces.Node, error) {
	if m.impl == nil {
		m.impl = NewNodeManagerImpl(m.client)
	}
	return m.impl.Get(ctx, nodeName)
}

// Update updates node properties
func (m *NodeManager) Update(ctx context.Context, nodeName string, update *interfaces.NodeUpdate) error {
	if m.impl == nil {
		m.impl = NewNodeManagerImpl(m.client)
	}
	return m.impl.Update(ctx, nodeName, update)
}

// Watch provides real-time node updates
func (m *NodeManager) Watch(ctx context.Context, opts *interfaces.WatchNodesOptions) (<-chan interfaces.NodeEvent, error) {
	if m.impl == nil {
		m.impl = NewNodeManagerImpl(m.client)
	}
	return m.impl.Watch(ctx, opts)
}

// PartitionManager implements the PartitionManager interface for API version v0.0.43
type PartitionManager struct {
	client *WrapperClient
	impl   *PartitionManagerImpl
}

// List partitions with optional filtering
func (m *PartitionManager) List(ctx context.Context, opts *interfaces.ListPartitionsOptions) (*interfaces.PartitionList, error) {
	if m.impl == nil {
		m.impl = NewPartitionManagerImpl(m.client)
	}
	return m.impl.List(ctx, opts)
}

// Get retrieves a specific partition by name
func (m *PartitionManager) Get(ctx context.Context, partitionName string) (*interfaces.Partition, error) {
	if m.impl == nil {
		m.impl = NewPartitionManagerImpl(m.client)
	}
	return m.impl.Get(ctx, partitionName)
}

// Update updates partition properties
func (m *PartitionManager) Update(ctx context.Context, partitionName string, update *interfaces.PartitionUpdate) error {
	if m.impl == nil {
		m.impl = NewPartitionManagerImpl(m.client)
	}
	return m.impl.Update(ctx, partitionName, update)
}

// Watch provides real-time partition updates
func (m *PartitionManager) Watch(ctx context.Context, opts *interfaces.WatchPartitionsOptions) (<-chan interfaces.PartitionEvent, error) {
	if m.impl == nil {
		m.impl = NewPartitionManagerImpl(m.client)
	}
	return m.impl.Watch(ctx, opts)
}

// InfoManager implements the InfoManager interface for API version v0.0.43
type InfoManager struct {
	client *WrapperClient
	impl   *InfoManagerImpl
}

// Get retrieves cluster information
func (m *InfoManager) Get(ctx context.Context) (*interfaces.ClusterInfo, error) {
	if m.impl == nil {
		m.impl = NewInfoManagerImpl(m.client)
	}
	return m.impl.Get(ctx)
}

// Ping tests connectivity to the cluster
func (m *InfoManager) Ping(ctx context.Context) error {
	if m.impl == nil {
		m.impl = NewInfoManagerImpl(m.client)
	}
	return m.impl.Ping(ctx)
}

// Stats retrieves cluster statistics
func (m *InfoManager) Stats(ctx context.Context) (*interfaces.ClusterStats, error) {
	if m.impl == nil {
		m.impl = NewInfoManagerImpl(m.client)
	}
	return m.impl.Stats(ctx)
}

// Version retrieves API version information
func (m *InfoManager) Version(ctx context.Context) (*interfaces.APIVersion, error) {
	if m.impl == nil {
		m.impl = NewInfoManagerImpl(m.client)
	}
	return m.impl.Version(ctx)
}
